### ISSUE TITLE
Improve style of current code and add PEP8 checking to Travis

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#116]
Much of the current repo does not conform to pep8. We should change that.

1. Do an initial run of something like `autopep8` to help fix all current style violations. We'll probably want to do this in one go so we can turn PEP8 checking on in Travis immediately after.
2. Run PEP8 checking in Travis, maybe using `flake8`?
3. Enforce better docstring documentation. I've found the [numpy docstring format](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt) to be the most sane. It's supported in Sphinx and is at least [partially supported](https://github.com/davidhalter/jedi/blob/master/docs/docs/features.rst#general-features) to type hint for autocompletion libraries like `jedi`.
4. Add a `contributing.md` file with style, docstring, and test requirements.

**Comment by stephendonner** [comment]
To update, post-merge of https://github.com/citp/OpenWPM/pull/199:

1.  We now ignore ```PEP8/flake8```'s E501, in the Travis-CI job/tests.
2. ```PEP8/flake8``` checking, via Travis CI, is also currently limited to /tests/*

This means we'll need/want to circle back, and:

1. Fix ```PEP8/flake8``` issues outside of /tests/*
2. Decide whether to continue ignoring E501, and/or at which character-number/line-length value to stop
3. Look at better docstrings, as in the original comment
4. Add the ```contributing.md``` file, as well

**Comment by englehardt** [comment]
TravisCI tests now enforce style checking, and the entire repo is complaint.
