### ISSUE TITLE
random_attributes dose not change navigator.platform, ...

### ISSUE THREAD

**Issue by najmeh-mir** [mozilla/OpenWPM#17]
When random_attributes is enabled, it only choose a user_agent_string randomly, but navigator.platform, navigator.appVersion, navigator.appName,... are not changed to be synced with that. So it can be detected easily that you are announcing fake platform and browser.

**Comment by englehardt** [comment]
Thanks for bringing this to my attention. The [navigator interface](https://developer.mozilla.org/en-US/docs/Web/API/Navigator) exposes several properties that could reveal the actual browser used. Several examples include:
```
navigator.appCodeName
navigator.appName
navigator.appVersion
navigator.platform
navigator.vendor
navigator.vendorSub
navigator.product
navigator.productSub
```
It is possible to override at least some of these in Firefox, by creating a profile with the preference `general.XXX.override = ...`, but the spoofing will still be trivially detectable. For example, the navigator in Firefox has the various `navigator.moz*` non-standard properties while Chrome's navigator doesn't. Chrome implements `navigator.getBattery()`, while Firefox exposes `navigator.battery`. Even if the APIs have the same name in both browsers, they may return results with a different precision as the [BatteryManager](https://eprint.iacr.org/2015/616.pdf) used to.

I'm not sure it makes sense to include these extra fields when random_attributes is enabled, as any adversary attempting to actively detect spoofing wouldn't have much more trouble doing so. In general, I think random_attributes needs an overhaul.

**Comment by englehardt** [comment]
See #745
