### ISSUE TITLE
Replace http_requests(content_policy_type) with human-readable type

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#188]
In the [http instrumentation](https://github.com/citp/OpenWPM/blob/7ee14e3bff2d14ec4f41aab9a6530908b8745d74/automation/Extension/firefox/lib/http-instrument.js#L232) we store the content type of the resource being requested as [classified by Firefox](https://searchfox.org/mozilla-central/source/dom/base/nsIContentPolicy.idl). Instead of storing the type as an integer and deferring to the IDL for the definition, we should just store the string types directly.

**Comment by turban1988** [comment]
Hi, 
I am not an Sqlite expert. Thus, I dont know if sqlite only saves references to equal strings or if it stores the string. If everytime a seperate Strign woudl be stored that might be a big overhead.

Maybe a view might help, if someonbe wants to look at the raw data.

Example: 
CREATE VIEW view_name
AS 
   SELECT hr.url, hr.method, hr.content_policy_type, cpt.name
   FROM http_requests as hr, new_content_type_header_db as cpt
   WHERE cpt.id = hr.content_policy_type

Cheers, 
Tobias

**Comment by englehardt** [comment]
This is no longer necessary with the new WebExtensions schema, which records the human readable type directly from the WebExtensions API.
