### ISSUE TITLE
Save the configuration parameters and environment details to crawl database

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#20]
It would be helpful to save the full configuration dictionary and version numbers to the crawl database to make it easier to keep track of these settings when distributing data.

The approach I see is:
- OpenWPM release number / commit
- Serialize `browser_params` (and possibly `manager_params`) and write the strings
- Save the `Firefox` and `Adobe Flash` version numbers
- Save the version numbers for any extensions launched (these can be pulled from extension file names)

**Comment by englehardt** [comment]
These should also be printed at the beginning of a crawl, and printed to the crawl's logfile.

**Comment by vringar** [comment]
This is handled by the crawl and task table isn't it? @englehardt 
We don't log the extension version but they can easily be restored from the git repository and the browser config contains if they were enabled or not
