### ISSUE TITLE
Consider introducing pipenv, to replace pip install + virtualenv

### ISSUE THREAD

**Issue by stephendonner** [mozilla/OpenWPM#205]
Look at introducing ```pipenv[0]``` as a replacement for both ```pip install``` and ```virtualenv```.  This will be especially easier after the Dockerization [sic] rewrite lands.

I'd/I'll happily take this, but feel free to "steal" in the interim!

[0] https://docs.pipenv.org/

**Comment by englehardt** [comment]
I've decided against Pipenv for the reasons discussed in #499
