### ISSUE TITLE
Ensure WebExtensions finish startup task before allowing the platform to submit the first request

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#224]
In #221 we started the move over to WebExtensions. Unfortunately, WebExtensions do not block the first page load on extensions startup, meaning that page content may load before the extension injects instrumentation. See [Bug 1378459](https://bugzilla.mozilla.org/show_bug.cgi?id=1378459). We've thus had to account for this in our tests, see: https://github.com/citp/OpenWPM/commit/643e45766a24fd2fd72c98b902599faa3422e423.

This is a problem for us since most of our crawls are stateless and will experience some delay on every load, meaning we'll miss a small amount of data at the start of each page.

Let's see if we can block on startup within the browser manager until the extension has fully loaded.

**Comment by englehardt** [comment]
Telemetry on startup time: https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2017-07-04&include_spill=0&keys=__none__!__none__!__none__&max_channel_version=nightly%252F56&measure=WEBEXT_BACKGROUND_PAGE_LOAD_MS&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_keys=submissions&start_date=2017-06-12&table=0&trim=1&use_submission_date=0

**Comment by englehardt** [comment]
Possibly related: https://github.com/gbaptista/luminous/issues/55 and https://github.com/EFForg/privacybadger/issues/1865.

**Comment by ghostwords** [comment]
There may be two separate kinds of issues here:
- Pages loading before the extension finished registering listeners or reading its config from extension storage on extension startup (tracked under https://github.com/EFForg/privacybadger/issues/1845 for Privacy Badger)
- Pages loading before content scripts have finished receiving their instructions (such as whether to continue to run).

**Comment by englehardt** [comment]
@ghostwords thanks for pointing that out. I updated the title and filed #242 to make it clear there are two potential issues.

**Comment by englehardt** [comment]
It's now possible to block requests on startup. See https://github.com/mozilla/contain-facebook/issues/206 and https://github.com/mdn/sprints/issues/1015 for a description.

**Comment by Grossdm** [comment]
@englehardt,
You've stated that this is now possible - can you provide more information for developers to implement this?
For example, I use uBlock Origin and there is a caution about this not working properly:
https://github.com/gorhill/uBlock/wiki/Advanced-settings#suspendtabsuntilready-experimental

Thank you,
Doug

**Comment by englehardt** [comment]
@Grossdm The mdn issue I linked to contains all the info I have. You may be able to follow up on IRC with the folks in the bug linked from the MDN issue above (https://bugzilla.mozilla.org/show_bug.cgi?id=1501159).

**Comment by Grossdm** [comment]
Unfortunately I haven't learned how to use IRC.

I suppose it's only a matter of selecting a client (or I think that some IRC servers host via HTTP/S) and diving in.

**Comment by nhnt11** [comment]
> It's now possible to block requests on startup until webextensions are ready. See [mozilla/contain-facebook#206](https://github.com/mozilla/contain-facebook/issues/206) and [mdn/sprints#1015](https://github.com/mdn/sprints/issues/1015) for a description.

Alright, I looked at the code landed in bug 1447551 and it's promising. It indeed allows us to write a blocking WebRequest listener that stalls page loads till the instrumentation is ready. I'm going to try and write a patch for this today.

**Comment by jallmann** [comment]
@nhnt11 Have you made any progress with this patch? Or otherwise, would you mind if I pick it up?

**Comment by nhnt11** [comment]
@jallmann ugh, I didn't see this. Please feel free to pick it up and let me know if I can help.

**Comment by nhnt11** [comment]
@englehardt Can we close this?

**Comment by englehardt** [comment]
@nhnt11 If I remember correctly from a few weeks back you mentioned that you had tested this manually by adding in a big delay into startup and didn't see any missed requests? Is that right?

**Comment by nhnt11** [comment]
Yes.

**Comment by nhnt11** [comment]
I think what we verified was that we can indeed use the blocking WebRequest listener to achieve this but I can't remember if we landed it. It doesn't seem like it.

**Comment by vringar** [comment]
The second part of the issue (the ack to the plattform) is being tracked in #135 and the first part was successfully implemented so I'm closing this
