### ISSUE TITLE
Remove built-in extensions

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#233]
(From #153) These extensions are far out of date, and we haven't come up with any general solution to automatically updating them (or the lists they rely on). Instead, we should pull them out of OpenWPM entirely to lower the core platform maintenance cost.

Studies which need to use extensions can add them manually. This ensures that users of the platform grab up-to-date versions.

We should file a follow-up issue to explore list update / profile priming options as discussed in #153. While we likely won't want to bundle extensions, it would still be nice to provide an interface to add a new extension and prime a profile with any lists it requires.

**Comment by valkyr13** [comment]
@englehardt can i work on this?

**Comment by englehardt** [comment]
@valkyr13 yes, and thank you!

**Comment by vringar** [comment]
@valkyr13 are you still working on this?

**Comment by Metropass** [comment]
I've been reading the Issues you referenced in the paragraph.

I noticed that `browser_params`have the extensions that you wanted to remove, should we replace them with a similar extension or should I just remove the block entirely? 

@englehardt @vringar 

https://github.com/mozilla/OpenWPM/blob/8ee163a88d160ca644733ba2b341b819969bc943/automation/DeployBrowsers/configure_firefox.py#L45

**Comment by vringar** [comment]
We don't want any extensions but our own to be part of OpenWPM. If users want to have extensions installed they should do so by setting up a profile that has the extension installed and setting that as a `seed_profile`
So please just remove the block entirely.
Do you want me to show you all parts of the code base that you'll need to touch for this issue or do you want to explore this on your own?

**Comment by Metropass** [comment]
> 
> 
> @Metropass We don't want any extensions but our own to be part of OpenWPM. If users want to have extensions installed they should do so by setting up a profile that has the extension installed and setting that as a `seed_profile`
> So please just remove the block entirely.
> Do you want me to show you all parts of the code base that you'll need to touch for this issue or do you want to explore this on your own?

At least from what I've seen inside the issues, you wanted Ghostery, Disconnect and uBlock to be removed. Are there any extensions that you also wanted to remove? 😄

**Comment by vringar** [comment]
We also want to get rid of HTTPS everywhere. Basically all that's in [here](https://github.com/mozilla/OpenWPM/tree/master/automation/DeployBrowsers/firefox_extensions) should be deleted. And all code that refers to these extensions (aka some of the browser_params) should be deleted as well.

**Comment by Metropass** [comment]
@vringar I have the extensions removed, however TravisCI fails a test with 

`The command "if [[ "$TESTS" != "webextension" ]]; then pre-commit run --all; fi" failed and exited with 1 during .`

I tried looking at the json to double check that I removed the references to the deleted extensions, and everything is fine. I might need some help debugging TravisCI.

**Comment by vringar** [comment]
We want all of our code to have the same format so we use black as an automated formatter
The easiest way to fix this would be to check out the code locally, run black there and then commit and push the changes
Sorry that this is inconvenient from the Web UI

**Comment by Metropass** [comment]
> 
> 
> We want all of our code to have the same format so we use black as an automated formatter
> The easiest way to fix this would be to check out the code locally, run black there and then commit and push the changes
> Sorry that this is inconvenient from the Web UI

I ran black, and nearly everything seems to be in order. However Test 2576.4 failed. Should I post the logs here?
