### ISSUE TITLE
Re-establish socket communication between the platform and extension

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#236]
In #221 we started the upgrade to Firefox 60  / WebExtensions. In the PR, we attempted to move everything over to WebExtension APIs and avoid all experiment APIs. This necessitated the move from sockets to web sockets via socket.io. @motin started adding support for this via #221, but did not fully integrate socket.io on the python side of the platform.

We've since decided that we're comfortable using WebExtension Experiment APIs for small, targeted APIs. This will let add experimental instrumentation that could be used in one-off studies or added to the `openwpm-webext-instrumentation` module if we're able to get it supported within the actual WebExtension API. Let's add back in the [current socket interface](https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/firefox/lib/socket.js) for the initial upgrade and revisit the move to web sockets later. This should minimize the changes necessary for the initial upgrade since we shouldn't have to change any platform code.

We'll want to inline this API similar to what was done here: https://github.com/motin/jestr-pioneer-shield-study/tree/develop/src/privileged/privacyContext

**Comment by nhnt11** [comment]
I think we can close this now.
