### ISSUE TITLE
Upgrade Selenium to a version that supports FF60 + WebExtensions

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#238]
As part of the Firefox upgrade process (#221, specifically https://github.com/SeleniumHQ/selenium/pull/6463) we patched Selenium to properly support our web extension use case. While waiting for that patch to make it for a version available via pip, we tried directly [pulling the repo](https://github.com/mozilla/OpenWPM/blob/c630c6a70b75e0ab84e7c57948ec3ddf5874edea/requirements.txt#L39) via pip but this [isn't supported](https://github.com/SeleniumHQ/selenium/issues/6470).

We should verify that the the newest selenium package on pip includes @motin's patch and move over to the official package. If that's not an option, we should include some documentation on how to build and copy over selenium from source and update the broken `requirements.txt` script.

**Comment by nhnt11** [comment]
I think we can close this now.
