### ISSUE TITLE
Ensure web extension instrumentation passes the test suite

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#240]
In #221 we started work upgrading OpenWPM to WebExtensions. In #223 we moved the OpenWPM over to the `openwpm-webext-instrumentation` repository and instead import the instrumentation as a node package. We should ensure that the instrumentation is imported correctly and passes the current OpenWPM test suite (which was written for the older addon-sdk extension). See also https://github.com/mozilla/openwpm-webext-instrumentation/issues/2.

We expect to lose certain columns, and have renamed other columns. See https://github.com/mozilla/openwpm-webext-instrumentation/issues/17.

Let's get the test suite passing in this repository and then file a follow-up bug to move the necessary tests over to the `openwpm-webext-instumentation` repository.

**Comment by nhnt11** [comment]
- [ ] test_crawl.py
- [ ] test_custom_function_command.py
- [ ] test_env.py
- [ ] test_extension.py
- [ ] test_http_instrumentation.py
- [ ] test_js_instrument.py
- [ ] test_profile.py
- [ ] test_simple_commands.py
- [ ] test_storage_vectors.py

**Comment by englehardt** [comment]
We completed this with the merge of #322
