### ISSUE TITLE
Ensure WebExtensions inject content script instrumentation before any page scripts run

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#242]
The instrumentation should block page script execution until all of the instrumentation injected by the `js_instrument` is set up. We should determine whether this is actually an issue or if we are only experience this during the initial page load as described in #224. See also: gbaptista/luminous#55 and EFForg/privacybadger#1865.

Note that even if this isn't an issue right now, we may experience it once we fix #68.

**Comment by englehardt** [comment]
In #291 we enabled "testing mode" for all content script injections. When we fix this, we should reverse that and rely on the `testing` parameter once again.

**Comment by nhnt11** [comment]
@jallmann Thanks for that investigation! I'm curious - could you share your test extension somewhere? Did you try putting a small delay in the content script and then checking if page scripts are affected by that delay?

**Comment by jallmann** [comment]
This is the extension I built for testing: 
https://github.com/jallmann/webExtTest

The repo includes a test page and script with some console prints to illustrate the order of events. 
The extension is currently configured to register content scripts 5 seconds after it loads. If the test page is loaded wihtin that interval, the page script runs without the content script being injected at all. 

>  Did you try putting a small delay in the content script and then checking if page scripts are affected by that delay?

I not sure what you mean. Some artificial, blocking delay in the content script? I haven't tried that, but I would expect it to delay page script execution as well.

**Comment by nhnt11** [comment]
> This is the extension I built for testing:
> https://github.com/jallmann/webExtTest

Thanks!

> The repo includes a test page and script with some console prints to illustrate the order of events.
> The extension is currently configured to register content scripts 5 seconds after it loads. If the test page is loaded wihtin that interval, the page script runs without the content script being injected at all.

That sounds right. 👍

> > Did you try putting a small delay in the content script and then checking if page scripts are affected by that delay?
> 
> I not sure what you mean. Some artificial, blocking delay in the content script? I haven't tried that, but I would expect it to delay page script execution as well.

Yup, that's what I meant.

**Comment by jallmann** [comment]
Yes, blocking the content script for some time delays execution of the page script as well, just as expected.

**Comment by nhnt11** [comment]
I think we can close this!
