### ISSUE TITLE
Add helper function to consume crawl list from a cloud queue

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#249]
We'd like to be able to deploy crawls across a cluster of machines. One thing this requires is a queue from which to serve site lists such that each crawler instance can grab a non-overlapping set of sites to access.

We've done this previously using an S3 bucket. See: https://github.com/jasonthomas/OpenWPM/commit/163d9fd58a9da9a8f597dd47219512e079172c9b.

**Comment by motin** [comment]
Fyi I am working on setting this up using https://kubernetes.io/docs/tasks/job/fine-parallel-processing-work-queue/ as per @jasonthomas suggestion.

**Comment by englehardt** [comment]
FYI I have some WIP patches for this as well. See:
* https://github.com/mozilla/openwpm-crawler/pull/6
* https://github.com/englehardt/OpenWPM/commit/fca287f98fa67018ba78198d924ed10ef626eccc

In case it's helpful. I'm planning to run a test crawl before preparing a commit for this repo.

**Comment by motin** [comment]
> FYI I have some WIP patches for this as well. See:
> 
>     * [mozilla/openwpm-crawler#6](https://github.com/mozilla/openwpm-crawler/pull/6)
> 
>     * [englehardt@fca287f](https://github.com/englehardt/OpenWPM/commit/fca287f98fa67018ba78198d924ed10ef626eccc)
> 
> 
> In case it's helpful. I'm planning to run a test crawl before preparing a commit for this repo.

This work has been consolidated into https://github.com/mozilla/openwpm-crawler/pull/7 and https://github.com/mozilla/OpenWPM/pull/401

**Comment by motin** [comment]
This was added in https://github.com/mozilla/OpenWPM/pull/401
