### ISSUE TITLE
localSotorage Tabel always empty

### ISSUE THREAD

**Issue by turban1988** [mozilla/OpenWPM#251]
Hi,
I noticed that the ``localStorage`` table of all of my measurements is always empty.
I did perform some large scale measurements (https://arxiv.org/pdf/1811.08660.pdf) but in all of my measurements the table is always empty. Do I need to add another command to save data to that table?

I used this openWPM configuration for my crawls:

```
for site in sites:
  command_sequence = CommandSequence.CommandSequence(site, reset=False)
  # Start by visiting the page
  command_sequence.get(sleep=config.CRAWL_SLEEP, timeout=config.TIMEOUT)
  # dump_profile_cookies/dump_flash_cookies closes the current tab.
  command_sequence.dump_profile_cookies(config.TIMEOUT)
  manager.execute_command_sequence(command_sequence)

# Shuts down the browsers and waits for the data to finish logging
manager.close()
```
To me the ``.get`` should save the local storage data since the documentation says
>Using cs.get(sleep, timeout) will execute a visit to the CommandSequence's url. The cookies, flash_cookies, http_request, http_response, and **localStorage**, and site_visits tables will be modified in the database.

Any help is appreciated.
Tobias

**Comment by turban1988** [comment]
I think the table is from an legacy version and not used anymore.

**Comment by englehardt** [comment]
That's correct. This table should be removed from the schema. I'll update the title to reflect that.

**Comment by englehardt** [comment]
Actually I see that we already did this in https://github.com/mozilla/OpenWPM/commit/68c36d9d81a36f90ee2bef5b9280ef750fe03513#diff-f6b77a8b9048ccf24dd9f33df199a4f6.
