### ISSUE TITLE
Disabling JavaScript?

### ISSUE THREAD

**Issue by malexmave** [mozilla/OpenWPM#252]
Is it possible to deactivate JavaScript in OpenWPM to simulate browsing with a browser that does not support JS? (This is particularly relevant when processing HTML documents that are not delivered via a website, but, for example, via eMail, where JS is not supported.)

Thanks in advance!

**Comment by englehardt** [comment]
Yes! I did some measurements of email tracking and had to do the same. You need to set `javascript.enabled` to `False`. I can't remember the reason why now, but I had to use `about:config` to flip the pref as opposed to just setting it on the profile. See: https://github.com/citp/email_tracking/blob/79c78b2de09b79639776fb576ae1497d2f3184fc/crawler_emails/automation/DeployBrowsers/deploy_firefox.py#L142-L152.
