### ISSUE TITLE
Function get_psl shoudl use logger instead of print

### ISSUE THREAD

**Issue by turban1988** [mozilla/OpenWPM#258]
Hi,
I noticed that the function` get_psl()` uses `print` statements instead of a logger. 

https://github.com/mozilla/OpenWPM/blob/b3ead7e38892095950806e8bcbb2e1129c27ca96/automation/utilities/domain_utils.py#L17-L28

If desired, I can try to fix this over the weekend.

**Comment by englehardt** [comment]
This would be a nice change. In general we have an odd setup of having a separate logging process that serlializes writes from the other python processes as well as from the Firefox extension. That might lead to some complications in fixing this.
