### ISSUE TITLE
Restore detailed logging in webextension

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#272]
We previously used the preference `fo.set_preference("extensions.@openwpm.sdk.console.logLevel", "all")` to ensure openwpm `console.logs` were visible in the browser console when debugging the extension. Is this still necessary with web extensions? If so, let's re-enable.

**Comment by nhnt11** [comment]
console.log calls are visible as long as you ensure `Show content messages` is enabled in the console. We manually verified this.
