### ISSUE TITLE
64-bit integer columns truncated in Javascript

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#277]
The max safe integer value in JS is [53 bits](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER). We generate 64-bit values for `visit_id` when the S3 aggregator is used, meaning some values get clipped when sent to the Javascript instrumentation. Since this same clipping doesn't happen in python, this means that the `visit_id` column is inconsistent between tables written directly in python (e.g., `site_visits`) and those written by the javascript instrumentation (e.g., `http_requests`). 

The simple solution here is to mask the [generated visit IDs](https://github.com/mozilla/OpenWPM/blob/b3ead7e38892095950806e8bcbb2e1129c27ca96/automation/DataAggregator/S3Aggregator.py#L320-L323) to 53 bits. We should also add a test for visit_id consistency across all tables when fixing this.

Note that the `expires` column of the `javascript_cookies` table is [also set to use 64 bits](https://github.com/mozilla/OpenWPM/blob/b3ead7e38892095950806e8bcbb2e1129c27ca96/automation/DataAggregator/parquet_schema.py#L149).

**Comment by nhnt11** [comment]
Another simple solution is to use doubles in python-land, I think.

**Comment by nhnt11** [comment]
I don't think we should mess with bits here - I assume 64-bit ints in pythonland are represented in 2's complement; whereas JS Numbers are IEEE 754 floats. Bitmasking would mess with the encoding.

**Comment by englehardt** [comment]
I'm not sure that the respective implementations matter. I think things will "just work" as long as we stay within a range of numbers that can be represented both in python and in JS. My suggestion was just to make sure that we keep the integers within that safe range with generating them in python.

**Comment by nhnt11** [comment]
Got it - I just saw the code that generates the ID and now understand what you mean!

**Comment by englehardt** [comment]
The ability to write tests for this depends on #294, since we only generate random visit IDs for the S3 Aggregator.
