### ISSUE TITLE
broken pipe

### ISSUE THREAD

**Issue by StevenRoosa** [mozilla/OpenWPM#282]
latest version is hanging with "broken pipe" on sites where fingerprinting is done on an illustration basis (panopticlick, amiunique, and uniquemachine).  Was using ubuntu 16.04, and reinstalled OS and OpenWPM and still happened.  Didn't happen on the build from 40 hours ago or so, but it does now.  Browser manager in automation directory was enabled to track javascript.  will update with traceback

**Comment by englehardt** [comment]
Interesting! We changed the master branch over to WebExtensions based instrumentation yesterday, so that's likely the culprit. A stack trace would be helpful!

If you'd still like to use the old branch it's available here: https://github.com/mozilla/OpenWPM/tree/firefox-52-archive

**Comment by StevenRoosa** [comment]
Broken pipe for panoptliclick:

I attempted to attach below the he terminal output in a .txt file; the log file generated by demo.py for the session; and a copy of the default browser params I used.  I can also load the same stuff for the broken pipe results for the uniquemachine fingerprinting site if that would be useful.  ...Just let me know.  I tried to fix myself, but I think this may surpasses my particular skill set!    

[output.txt](https://github.com/mozilla/OpenWPM/files/3090504/output.txt)

[default_browser_params_json.txt](https://github.com/mozilla/OpenWPM/files/3090518/default_browser_params_json.txt)

[openwpm.log](https://github.com/mozilla/OpenWPM/files/3090520/openwpm.log)

**Comment by englehardt** [comment]
Related to #255. Should be fixed by #442.

**Comment by englehardt** [comment]
@StevenRoosa has confirmed that this is now fixed.
