### ISSUE TITLE
Add optional site_rank column to site_visits table

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#285]
We're often using a top site list to crawl.

**Comment by vringar** [comment]
Created the column, but still need to figure out, where this data should be coming in as input (@englehardt any input on this?) and how to route this information through the application.

**Comment by englehardt** [comment]
This should be specified in the crawl script as an optional parameter for the [CommandSequence constructor](https://github.com/mozilla/OpenWPM/blob/bab2a629fcc3909a7ad6057e1d6740c7df70517c/automation/CommandSequence.py#L26-L40). That way, when someone ingests a site list in [the crawl script](https://github.com/mozilla/OpenWPM/blob/bab2a629fcc3909a7ad6057e1d6740c7df70517c/crawler.py#L121-L127) they can pass the site rank alongside the other visit information.
