### ISSUE TITLE
Add crawl deployment script for GCP

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#293]
Mozilla is currently running crawls on GCP. We've manually configured the last few crawls that we launched, but it would be much more efficient to have a helper script to launch new crawls.

It's not clear to me that this repo is the best place to put such a script. https://github.com/mozilla/openwpm-utils may be a better fit.

Desired configuration parameters:
* OpenWPM commit / branch to use
* Site list (e.g., the alexa top 1M list)
* crawl script (e.g., `demo.py`) -- maybe simply pointing to a Dockerfile which runs the crawl script is more appropriate
* Cluster configuration
    * Number of nodes
    * Node type / resource configuration

This script should upload the site list to a place where the crawler can pull down jobs from it, kick off the cluster in the requested configuration, and start the crawl. We should have a way to monitor the console output / terminate the cluster if necessary (probably just the GCP console).

Looking at the deployment script Jason used for the last crawl, we'll also need to add a helper function to the OpenWPM repo that pulls down chunks of the crawl list from S3 (or GCP?). See: https://github.com/englehardt/OpenWPM/compare/master...jasonthomas:englehardt-master-s3-docker-patch. Thus, the deployment script will have to pass the appropriate list location into the dockerfile/crawl script.

**Comment by englehardt** [comment]
See also: https://github.com/mozilla/OpenWPM/issues/249

**Comment by jasonthomas** [comment]
Overall everything above seems doable but I do have some questions and comments.

In the past we discussed running these sort of crawls at some frequency. Is that still desired? I am trying to understand what will invoke this crawl deployment script, such as a user via cli or some automated system like Airflow or Jenkins. This may change how we implement this script since something like Airflow has built in functionality for Kubernetes workloads. 

> OpenWPM commit / branch to use

If we are going to continue using Kubernates for the crawls we should automate the Docker image build process. We usually use CircleCI today and push the Docker images to Dockerhub. We could build an image on a new branch, tag the image with the branch name and use the Docker image as the deployment artifact. 

We should configure environment variables for run time parameters. We would need to add this support in the crawl script. 

> add a helper function to the OpenWPM repo that pulls down chunks of the crawl list from S3 (or GCP?).

I am not really a fan of this method and I think we could do this better. We could probably use redis either in a separate Kuberantes pod or GCP Memorystore as a queue, populate it with the site list and have the crawl script consume the queue.

**Comment by englehardt** [comment]
> In the past we discussed running these sort of crawls at some frequency. Is that still desired? I am trying to understand what will invoke this crawl deployment script, such as a user via cli or some automated system like Airflow or Jenkins. This may change how we implement this script since something like Airflow has built in functionality for Kubernetes workloads.

That is still desired. We'll want to do both: a crawl of the top 1m homepages that occurs regularly, and random manual crawls that do things like: visit a different top site lists, visit internal site pages, crawl with custom instrumentation, etc. If we have to prioritize between the two, the latter is more important since I can always manually trigger the top 1m homepages crawl until we have something automated in place.

> > OpenWPM commit / branch to use
> 
> If we are going to continue using Kubernates for the crawls we should automate the Docker image build process. We usually use CircleCI today and push the Docker images to Dockerhub. We could build an image on a new branch, tag the image with the branch name and use the Docker image as the deployment artifact.
>
> We should configure environment variables for run time parameters. We would need to add this support in the crawl script.

Makes sense. Does this mean that we'll only be able to launch crawls from branches off of the main repo, which will have the CircleCI --> Dockerhub setup? Or can someone (at Mozilla and with the right credentials) fork the main repo and kick off their own build of a Docker image that could be used with Kubernates?

> 
> > add a helper function to the OpenWPM repo that pulls down chunks of the crawl list from S3 (or GCP?).
> 
> I am not really a fan of this method and I think we could do this better. We could probably use redis either in a separate Kuberantes pod or GCP Memorystore as a queue, populate it with the site list and have the crawl script consume the queue.

Is it possible to do this dynamically, i.e., when the deployment script is run? If possible, it would be great to support arbitrary site lists.

**Comment by motin** [comment]
> Makes sense. Does this mean that we'll only be able to launch crawls from branches off of the main repo, which will have the CircleCI --> Dockerhub setup? Or can someone (at Mozilla and with the right credentials) fork the main repo and kick off their own build of a Docker image that could be used with Kubernates?

Yes, anyone can do it as long as the image is pushed to a registry that the Kubernetes cluster can access. GCP includes a registry for each GCP project so this is a no-brainer for anyone with GCP credentials.

> Is it possible to do this dynamically, i.e., when the deployment script is run? If possible, it would be great to support arbitrary site lists.

Yes. The workflow would be to load a site list into a redis service using a helper function / python script (the list is named, ie "foo-crawl-123") and then launch a crawl that consumes that particular list (set via an environment variable).

**Comment by motin** [comment]
Work on this is going on at https://github.com/mozilla/openwpm-crawler/pull/7

**Comment by motin** [comment]
This is now done and documented at https://github.com/mozilla/openwpm-crawler#run-a-crawl-in-google-cloud-platform
