### ISSUE TITLE
Add local saving to S3Aggregator alongside unit tests

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#294]
Both data aggregators are currently without unit tests, however the SqliteAggregator is at least tested through our integration tests. The `S3Aggregator` is never used in our test suite, which has led to a number of bugs:  https://github.com/mozilla/OpenWPM/issues/286, c01971088a21a47348ce8b861e2ee252ef9e60f6, among others.

Ideally we could do end-to-end tests that write and read from S3, but that would be a bit of a pain to set up. Instead, I think we should add in a config option to save parquet locally and use that to write a set of unit tests for the aggregator. This is a relatively easy change, and was a feature request from some folks at Mozilla. We'll also probably want to rename the Aggregator to ParquetAggregator for clarity.

**Comment by motin** [comment]
To clarify, the support for locally testing S3 using mock implementation was landed in https://github.com/mozilla/OpenWPM/pull/333, but this issue (#294) is about adding a config option to save parquet locally and use that to write a set of unit tests for the aggregator, without any involvement of S3. 

@englehardt, to clarify this in the code, we could consider adding ParquetAggregator, with S3ParquetAggregator extending it.

**Comment by englehardt** [comment]
> @englehardt, to clarify this in the code, we could consider adding ParquetAggregator, with S3ParquetAggregator extending it.

@motin That's an option. I actually just renamed the class to `ParquetAggregator`. See my WIP PR #390 and note the issues I identified while working on it. That's why I decided to stop working on it for the time being.

**Comment by motin** [comment]
Related: Using Mock S3 to run local crawls with crawl data stored in parquet format: https://github.com/mozilla/openwpm-crawler/tree/master/deployment/local

**Comment by englehardt** [comment]
I'm going to close this as I don't think it's the right direction anymore. The S3Aggregator should be optimized for cloud crawls and minimizing data loss. Constraining the future development there to also support an alternate local format doesn't seem right.

If we do want something like this, adding a new aggregator is the right approach.
