### ISSUE TITLE
Refactor Dockerfile and update documentation

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#304]
In the upgrade to WebExtensions we wiped out the old Dockerfile. Some of the previous steps were required, which had led to breakage (see #299). Let's revisit the [previous Dockerfile](https://github.com/mozilla/OpenWPM/blob/b8f23c97982ddf5a6a6739cbd656a08ca4d6fb91/Dockerfile), port whatever is necessary, and update [the documentation](https://github.com/mozilla/OpenWPM#docker-deployment-for-openwpm).

**Comment by eriktews** [comment]
There is a design choice to be made for the Dockerfile. Either it might be rather minimalistic and do almost nothing more than calling install.sh, or it might almost duplicate what is done by install.sh.

The advantage of the later version is that a Docker build runs much faster as long as only minor changes have been done to the OpenWPM code and almost all build steps can be cached. The negative aspect would be that when a new package is required for OpenWPM, it needs to be added to both, install.sh and the Dockerfile. That problem already exists a bit with for example _install-dev.sh_ and _install-mac-dev.sh_.

**Comment by eriktews** [comment]
Also, there might be a third option. We might split the _install.sh_ script into multiple smaller parts and then call them from _install.sh_ and also from the Dockerfile, which would give us fast (cached) Docker builds and it would also avoid duplicating code.

**Comment by englehardt** [comment]
Fixed in #314. Filed #317 as a final remaining task.
