### ISSUE TITLE
OpenWPM crashes on startup with WebDriverException on setWindowSize

### ISSUE THREAD

**Issue by malexmave** [mozilla/OpenWPM#306]
We're running the latest version of OpenWPM in the `firefox-52-archive` branch as part of an [Email privacy measurement platform](https://github.com/privacymail/privacymail). For about a week now, we've been encountering problems with OpenWPM refusing to start up, giving the following stack trace:

```
[13:13:51][ERROR] BROWSER 4: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 
[13:13:54][INFO] BROWSER 4: Crash in driver, restarting browser manager 
 Traceback (most recent call last):
  File "/opt/privacymail/privacymail/privacymail/OpenWPM/automation/BrowserManager.py", line 347, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/opt/privacymail/privacymail/privacymail/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 15, in deploy_browser
    manager_params, crash_recovery)
  File "/opt/privacymail/privacymail/privacymail/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 164, in deploy_firefox
    driver.set_window_size(*profile_settings['screen_res'])
  File "/opt/privacymail/privacymail/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 957, in set_window_size
    'windowHandle': windowHandle})
  File "/opt/privacymail/privacymail/venv/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 308, in execute
    self.error_handler.check_response(response)
  File "/opt/privacymail/privacymail/venv/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: setWindowSize
```

After this message, the system also has a number of geckodriver-processes that have broken free of the process tree of the cron job in which OpenWPM is called, and are just loitering around as children of the init process.

Deleting the OpenWPM install and deploying it anew fixed the problem for a few days, but a few days ago, it cropped up again. Given that the system ran fine for more than two months before these problems cropped up (without any changes on our part), we initially thought it may be related to the Addon signing problem that also happened a week ago, but [it looks like you disable addon signing in the Firefox settings automatically](https://github.com/mozilla/OpenWPM/blob/cc6403d6238829fbc254eb79f4da309e9744545c/automation/DeployBrowsers/configure_firefox.py#L213), so this shouldn't cause any issues, right?

[Here is how we call OpenWPM in our code](https://github.com/privacymail/PrivacyMail/blob/develop/privacymail/mailfetcher/models.py#L698), and [here is how we install it using Ansible](https://github.com/privacymail/PrivacyMail/blob/develop/ansible/deploy.yml). [Here's a gist with all dependency versions in our virtualenv](https://gist.github.com/malexmave/e296e3cde7607cd64df52e11060ae021). The server is running Ubuntu Server 18.04.2 LTS x64, and the machine has plenty of cores (12) and RAM (32 GB). The firefox binaries were installed via your install script on the 14th of May, and have the following md5 hashes, in case you want to compare to known-good versions:
```
0b04dd8e88576e145a9e87170e696775  firefox
9fd2c406a625f53b589485422b0dafbc  firefox-bin
```

Please let me know what additional information I can provide to help debug this.

**Comment by englehardt** [comment]
This sounds like it might be caused by https://github.com/mozilla/OpenWPM/issues/256#issue-407977408. If so, we don't plan to fix the 52 branch but Gunes was able to prevent the auto updates by redirecting requests to the update server to localhost (https://github.com/mozilla/OpenWPM/issues/256#issuecomment-464803853).

**Comment by malexmave** [comment]
Thanks for the tip and sorry for not responding earlier. I'll give this a try and report back if the problem crops up again. Will leave the issue open and close it if it the problem does not appear again within the next week.

**Comment by malexmave** [comment]
Looks like this fixed the issue, we did not encounter any more problems. Will reopen if it does crop up again, but closing it for the moment. Thanks for the quick help!
