### ISSUE TITLE
Installation and Updates

### ISSUE THREAD

**Issue by felix4webscience** [mozilla/OpenWPM#308]
Hi,

I am working with OpenWPM since the beginning of this year and would like to make some suggestions for improvements, as I run into some issues, which might be the same for other unexperienced User. 

I am using Ubuntu 16.04 and started on version 0.8. I am using PyCharm 2019.01 as it enables me to use also the Terminal and I am able to update my version from this github repository. 

However I've noticed that with major changes, my framework always broke and I have to debug some things. The error remain almost the same.

The first error always occurs in combination with the utility.py. This file is still within the folder 'tests' and should be moved to /automation/utilities as suggested in one of the issues (e.g #131).

When moving this file, you have to modify the imports in each related file of course.

Usually I am working with python 3.5 or even 3.7 and its always some kind of headache to work with python 2.7 because 'importing' files works slidely different. 

For instance if someone is just installing this repository total new from scratch and tries to run some tests from the test folder, the user will receive the following Error Message:

`ValueERror: Attempted relative import in non-package`

if you haved moved the file utility.py to the directory:  /automation/utility the correct command would be:

`from automation.utilities.utilities import BASE_TEST_URL, BASE_TEST_URL_DOMAIN # or the class you like`

This said, maybe it would be useful to update the file path for utility.py anyhow. And in addition update the way of importing files? 

However, I hope this will help some people to debug some problems.

**Comment by englehardt** [comment]
Would you mind to help me understand how you're using `test/utilities.py`? This file is only meant to be used by the tests and I have no trouble running the tests from the test directory. Are you following the steps listed in https://github.com/mozilla/OpenWPM#debugging-the-platform?

**Comment by felix4webscience** [comment]
Hey, 
sorry, for replying late. Well, I am using utilities almost in combination with the tests and you're correct its not necessary to move utilities.py to /automation/utilities/.
I am just doing it, because it - let's say- feels to be faster to change all the import errors, which automatically appear, because in the master branch its still written like this 'from .. import xyz' 

I also use py.test for debugging purposes. But the most headache after 'new installation' or using the update function for the github repository (in PyCharm) to merge is as I wrote the topic about relative imports. 

I don't know, if there is a way to write a script or something else to fix/ check and correct automatically all the relations. But its always taking some time, to correct everything, as new files and patches will extend the whole framework. (Or is it only me having this issue?)
