### ISSUE TITLE
"No module named six.moves" when using Docker

### ISSUE THREAD

**Issue by Perdu** [mozilla/OpenWPM#312]
Hello,
The latest changes to the Docker file seem to have broken the installation process: when trying to run the container, python dependencies are not found.
What I did:
`sudo docker build --tag=openwpm .`
`sudo docker run openwpm`
(or alternatively, using command in the readme:)
`mkdir -p docker-volume && sudo docker run -v $PWD/docker-volume:/home/tohwi/Desktop -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -it openwpm python /app/demo.py`
Result:
> ImportError: No module named six.moves

Opening a shell into the docker container, I see that python dependencies installed using the openwpm user are not found by root.
In my case, this issue is fixed by running install.sh as the root user inside the container.

**Comment by eriktews** [comment]
I did a major rewrite of the Dockerfile recently. Can you take a look at this version:

https://github.com/mozilla/OpenWPM/pull/314

**Comment by Perdu** [comment]
Oh it does work! I had other errors even after fixing the ones I reported above, and you patch fixes them too: I'm able to run demo.py.

**Comment by eriktews** [comment]
The new Dockerfile is now in master, so this can probably be closed.

**Comment by englehardt** [comment]
@eriktews thanks for helping with this.
