### ISSUE TITLE
OpenWPM Installation on Ubuntu 16.04 failed

### ISSUE THREAD

**Issue by felix4webscience** [mozilla/OpenWPM#321]
Hi,

I had some issues with my old openwpm version. Therefore I decided to create a new directory on my local storage and to clone the actual repository from today. Unfortunately this does not solve any of my problems. 

I followed the Set-UP instructions given at:

[https://github.com/mozilla/OpenWPM#installation](url) 

when I try to run the demo.py I get several error messages also related to the .xpi file. Unfortunately the install-dev.sh does not exist anymore, which in my understanding created the necessary additional files (?). However I am not sure where to start with debugging.

All tests fail as well.  Is there a way, to get back to an older release such as 0.80 (which was the last version, which worked fine for me)? Or what do you recommend?

I have added two screenshots of the error messages, when running the demo.py. 

![failures_demo_py_2019-06-12](https://user-images.githubusercontent.com/22968539/59372649-42d61980-8d48-11e9-90ee-73dc9588b507.PNG)
![failures02_demo_py_2019-06-12](https://user-images.githubusercontent.com/22968539/59372652-45d10a00-8d48-11e9-9025-0934aa7611d0.PNG)

**System:**
Virtual Env.: Virtual Box 6.0
OS: Ubuntu 16.04
IDEA: PyCharm Professional 2019.01

Any help would be appreciated. Please let me know, if you need any further information.
With kind regards
Felix

**Comment by englehardt** [comment]
I just cloned the repo and am not able to reproduce this.

It looks like the extension was not properly built. Do you mind to share the full output of the run of `install.sh`?

**Comment by felix4webscience** [comment]
hey,
sure but how can I do that?
is there any log file🤔? Is a screenshot feasible? Than I just repeat the
cloning and send you some, soon.
Greetings Felix

Steven Englehardt <notifications@github.com> schrieb am Mi. 12. Juni 2019
um 23:57:

**Comment by felix4webscience** [comment]
EDIT: I have run a new installation twice, made Screenshots from the installation.sh Output and added them to a powerpoint. I've send you the pptx via email. 
Thanks in advance,

**Comment by felix4webscience** [comment]
Hey,
I am just wondering if you got my mails with the total install.sh? 
So, I found another version from a forked repository, with an older version, which is working. 
However, that one is running only with python 2.7 and other older and probable unsecure tools, which are not up to date. So, it would be great to find out a solution for the newest release of openwpm. 
I really would appreciate any help.
Thank you in advance.

**Comment by englehardt** [comment]
@felix would you mind to past the output of the install script here, or using a site like https://pastebin.com/? thanks!

**Comment by felix4webscience** [comment]
@englehardt, hi i am sorry for replying late. I will pass it here in the next days. First, I will see, if things changed after all your work during the last days and try reinstalling again. Thanks for your support.
Greetings Felix

**Comment by felix4webscience** [comment]
@englehardt, thank you very much for your support. I found a workaround for my issues and stopped working with openwpm so far. So to avoid unecessary workload for you and your team, we can close this ticket here.
