### ISSUE TITLE
Clarify licensing moving forward

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#336]
* **I'm submitting a ...**
[ ] bug report
[ ] feature request
[X] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
This repository presumably contains code stemming from [GPLv3+](https://spdx.org/licenses/GPL-3.0-or-later.html)-licensed libraries:

```
Incorporating code from FourthParty,
http://fourthparty.info/
By Jonathan Mayer
Licensed GPLv3+

Incorporating code from Privacy Badger Firefox,
https://github.com/EFForg/privacybadgerfirefox
Copyright © 2015 Electronic Frontier Foundation and other contributors
Licensed GPLv3+
```

@englehardt 
1. Which part of the current codebase actually incorporates code from these libraries?
2. What are our options to eventually adopt [MPLv2](https://spdx.org/licenses/MPL-2.0.html) for this repository moving forward?

**Comment by motin** [comment]
@englehardt What do you think, as a first step, about clarifying which parts of this repository are licensed under GPLv3 and which do not stem from GPLv3 code and thus can be released under the MPLv2 license?

**Comment by englehardt** [comment]
The addon-on sdk extension started from https://github.com/fourthparty/fourthparty/tree/master/extension. As you can see, we've dropped a good deal of that code as part of the WebExtensions upgrade. There is still some code in the content.js file.

The content script injection method was pulled from https://github.com/EFForg/privacybadgerfirefox-legacy/blob/master/data/fingerprinting.js. This is still present.

The POST body collection and parsing code in the addon-sdk extension was pulled from https://github.com/redline13/selenium-jmeter/blob/master/content/library/recorder/HttpPostParser.js (and maybe other files in that repo). This code should be removed entirely.

So we can fairly say that we no longer include code from fourthparty or selenium-jmeter for most of the instrumentation (once we actually delete all of the commented out add-on sdk code). We definitely still include GPLv3 code from Privacy Badger and FourthParty in `content.js`, and have no plans to remove that.

**Comment by englehardt** [comment]
We are going to keep this library GPLv3 for now
