### ISSUE TITLE
Add a config option to control the stripping of data from data URLs

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#338]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Currently, we replace the actual content of `data:` URLs with `<data-stripped>`. We should add a config option `stripDataUrlData` (default: true), which controls this behavior.

* **Other information**
Since the escapeUrl function is used all over the instrumentation, this involves injecting the config option in many places - similar to how the crawl id is injected - or can we choose a better way?

**Comment by nhnt11** [comment]
We think we should just do #339 (and by default - i.e. sans a config option) - so this can be closed.
