### ISSUE TITLE
Combine `extension_session_uuid` and `crawl_id` into `browser_launch_id`

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#340]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**

In #11 we added `extension_session_uuid` which serves a similar purpose as `crawl_id`. We identified in https://github.com/mozilla/openwpm-webext-instrumentation/pull/11#discussion_r235098127 that we'd like to combine the two (quoted below)

>The `crawl_id` is generated by OpenWPM and passed to the browser upon startup. This matches the semantics of the `extension_session_uuid`. My understanding is that JESTr will leave the `crawl_id` column null right? I think it's better to combine the two.
>We could have a column named `session_id` and remove the `crawl_id`. Then in `extensionSessionUuid.ts` we could either pass in a ID as an argument during startup (which for the crawler would be a `crawl_id`), or fall back to generating a session UUID when that's not available.

**Comment by vringar** [comment]
The extension calls it crawlID instead of crawl_id but that's just following variable naming convention
