### ISSUE TITLE
Instrument future calls to overwritten methods / objects

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#347]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Since #19, we can't instrument future calls to overwritten methods / objects. This issue is about addressing this, without re-introducing issues similar to #16. 

* **Other information**
See https://github.com/mozilla/openwpm-webext-instrumentation/issues/16#issuecomment-438555032:

> Note that it's not the ideal solution since we can't instrument future calls to overwritten methods / objects. We could achieve that by using:
> 
> ```javascript
> Object.defineProperty(this, propertyName, {
>     get: instrumentedGetter,
>     set: instrumentedSetter,
> });
> ```
> 
> but this will require a bit of refactoring as we don't want to completely replicate all of the current getter/setter instrumentation.

**Comment by englehardt** [comment]
We've decided against doing this. We'd like to move instrumentation into Firefox, and this will require too much effort for the JS instrumentation with no certain benefit.
