### ISSUE TITLE
Report the width and height of loaded frame elements

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#349]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Reporting frame dimensions (at load time) allows for evaluation of new detection heuristics. 1x1 frames for instance may be more likely to be trackers than content loaded in larger frames.

* **Other information**
Frame dimensions are not supplied to the webRequest and webNavigation listeners, so reporting the frame dimensions requires waiting for the DOM to be available and then report the frame properties.
In order to be able to relate the reported frames with the frameAncestors urls, the src of the frame needs to be reported in the instrumentation.
Related: https://stackoverflow.com/questions/38685691/how-to-get-iframe-element-from-frameid-in-content-script

**Comment by englehardt** [comment]
This will have limited use. Likely better for folks to implement this if they need it.
