### ISSUE TITLE
Add context regarding privacy-related browser settings to navigation events

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#350]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
Having [this context](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/privacy) at the time of navigation is important when analyzing the logged instrumentation packets.

**Comment by englehardt** [comment]
Out of scope since these settings will be known for crawls.
