### ISSUE TITLE
Collect window.performance for every completed page load

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#351]
* **I'm submitting a ...**
[ ] bug report
[X] feature request
[ ] question about the decisions made in the repository
[ ] question about how to use this project

* **Summary**
[window.performance](https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API) allows quick access to a wealth of navigation and timing-related metrics that may prove useful in privacy-related research.

**Comment by englehardt** [comment]
If folks find a need for this in the future, they can file an issue/PR. No need for us to track in the interim.
