### ISSUE TITLE
Add a "save_all_cookies" command

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#379]
With the new webext instrumentation, it is trivial to dump the values of all cookies. Support for this is [already implemented](https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/webext-instrumentation/src/background/cookie-instrument.ts#L75) (in relation to https://github.com/mozilla/jestr-pioneer-shield-study/issues/2), but there is no command or integration point that uses this method at the moment.

Usage:
```
await this.cookieInstrument.saveAllCookies(config["crawl_id"]);
```

Related: https://github.com/mozilla/OpenWPM/issues/259

**Comment by englehardt** [comment]
The cookie instrument is more detailed. I don't think is necessary.

**Comment by nrllh** [comment]
@englehardt I think you should provide this functionality. At the moment, it's not directly possible to get cookies that are alive or not. Labeling a cookie as `deleted` won't also work if one wants to get all cookies with a simple query as in the last state cookie.jar. 

Maybe you can add a column `is_active ` and assign all cookies as `1` if these were in cookie.jar before crawler stoped.

**Comment by englehardt** [comment]
> @englehardt I think you should provide this functionality. At the moment, it's not directly possible to get cookies that are alive or not. Labeling a cookie as `deleted` won't also work if one wants to get all cookies with a simple query as in the last state cookie.jar.
> 
> Maybe you can add a column `is_active ` and assign all cookies as `1` if these were in cookie.jar before crawler stoped.

Hey! I'm not sure I understand what you're trying to achieve. Would you be able to share an example of a situation where the current instrumentation is insufficient?

**Comment by nrllh** [comment]
@englehardt  I want to get all cookies as in cookie.jar. So deleted cookies shouldn't be in my result. In that case, I see no way to retrieve these cookies with a simple query. Of course, it's possible with subqueries etc. But it'd be much easier if you label cookies that were not deleted.

**Comment by nrllh** [comment]
@englehardt just wanted to ping if there are any thoughts to implement such a function. Or am I missing something, and this function is already there?

**Comment by nrllh** [comment]
I tried to do this with the following SQL statement:
```

with r_cookies as( select name, host from (select * from javascript_cookies c inner join 
        (select name, host from javascript_cookies  group by name, host ) gc on gc.name=c.name and c.host=gc.host 
        WHERE gc.name in(select name from javascript_cookies j where j.name=gc.name and j.host=gc.host and j.record_type != 'deleted' order by time_stamp desc limit 1)
        ) group by name, host)

        select expiry, is_secure, is_http_only, same_site, name, host, path, time_stamp, c.visit_id, value, first_party_domain, is_session, is_host_only, s.site_rank
        from (select * from javascript_cookies j inner join r_cookies where id in (select id from javascript_cookies tmp where r_cookies.name=tmp.name and r_cookies.host=tmp.host order by id desc limit 1) 
        and j.record_type!='deleted') as c inner join site_visits as s on s.visit_id = c.visit_id 
```

So my goal is to get cookies with their last value and cookies that are not deleted. Do you think, I'm interpreting the table right and getting with the statement the cookies I want?

**Comment by vringar** [comment]
I'm sorry this level of SQL is completely unreadable to me. 
I'd probably implement this in either Pandas or Spark to be able to have intermediates with names and a syntax I'm familiar with.
