### ISSUE TITLE
Consider using the remote protocol / Chrome DevTools Protocol

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#380]
I did some digging regarding utilization of the remote protocol in order to avoid Web Extension Experiments for communication with the platform. Here is what I found:

A portion of the Chrome DevTools Protocol is implemented in Firefox (see [remote protocol](https://firefox-source-docs.mozilla.org/remote/index.html)).

[Puppeteer](https://pptr.dev/) seems to be the best way to utilize the Chrome DevTools Protocol in practice.

Puppeteer is meant to be used to test web UI and extension background pages using Node/JS and allows that to be done in a more native and faster manner than Selenium can offer. It also enables access to some DevTools capabilities such as [intercepting Console messages](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#event-console).

Puppeteer is traditionally Chromium only but 5 months ago, Puppeteer-Firefox (https://www.npmjs.com/package/puppeteer-firefox) was initiated and enables experimental support to use Puppeteer with Firefox. The initiative has [steady and recent Github activity](https://github.com/GoogleChrome/puppeteer/commits/master/experimental/puppeteer-firefox) and [large parts of the Puppeteer APIs are supported](https://aslushnikov.github.io/ispuppeteerfirefoxready/)

Note the difference between these two similarly named projects:
* Puppeteer-Firefox (https://www.npmjs.com/package/puppeteer-firefox) is the Puppeteer-project's experimental support for Firefox (for web UI and extension background pages)
* Mozilla's Firefox Puppeteer (https://firefox-puppeteer.readthedocs.io/en/master/) is a python Puppeteer-Page-interfaced implementation wrapping the browser UI, ie allowing testing the browser UI itself, not web UI and extensions. Used for functional  testing of the Firefox UI itself (https://developer.mozilla.org/en-US/docs/Mozilla/QA/Firefox_UI_tests)

Firefox remote debugging seems only be enabled for Unbranded/Dev/Nightly builds so whatever we gain by not using Web Extension Experiments, it is not being able to test using Branded versions of Firefox. Also, only Firefox 63 is expected to be somewhat supported at the moment (will probably change once Firefox is no longer experimental).

**However, a major advantage of using Puppeteer and the Chrome DevTools Protocol as the transport mechanism between the Web Extension and the platform is the ability to run OpenWPM crawls using Chrome/Chromium alongside Firefox, since we no longer depend on Web Extension Experiments to communicate with the platform.**

Chromium also supports Puppeteer API:s for [code coverage](https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#class-coverage) and [tracing](https://pptr.dev/#?product=Puppeteer&version=v1.18.1&show=api-class-tracing), something that may be useful for analyzing scripts and web-site behavior from a privacy perspective. (btw Tracing may be implemented for Firefox as well: https://github.com/GoogleChrome/puppeteer/issues/4044).

Note that Puppeteer does not allow any remote control of the Browser UI, for which Selenium is still the golden standard. Puppeteer as such would not replace Selenium in OpenWPM, at least not entirely.

To start using Puppeteer, I imagine that we as a first step could instruct Selenium to launch Firefox with remote debugging enabled, then launch a Node script that connects with Puppeteer and sends/receives events/messages to/from the Web Extension and relay those messages to/from the python socket interface.

Ping @englehardt @nhnt11

**Comment by nhnt11** [comment]
My personal opinion here is that a project to refactor our platform/client communication setup is not something we can resource any time soon. Aside from that, IMO we should go with something more standard/generic, like a simple HTTP api, which would be extensible, maintainable, not add technical debt, and open up possibilities for running clients remotely and so on.

**Comment by motin** [comment]
> My personal opinion here is that a project to refactor our platform/client communication setup is not something we can resource any time soon. 

Yes, this issue is indeed long-term.

> Aside from that, IMO we should go with something more standard/generic, like a simple HTTP api, which would be extensible, maintainable, not add technical debt, and open up possibilities for running clients remotely and so on.

Fully agree! So basically re-explore the approach with HTTP/WebSockets as in https://github.com/mozilla/OpenWPM/pull/221?

Puppeteer can still be useful for tracing and metrics, which could allow for extended lines of research (Using Chromium initially and later Firefox depending on the outcome of https://github.com/GoogleChrome/puppeteer/issues/4044). I can just imagine how much easier it may be to detect cryptomining by looking at performance profiles, and programmatic access to the devtools protocol may offer a solution vector for https://github.com/mozilla/OpenWPM/issues/352

**Comment by motin** [comment]
See https://github.com/teamnsrg/mida for an example of a crawler that uses the DevTools protocol.

**Comment by englehardt** [comment]
This is a direction we aren't planning to take for now.
