### ISSUE TITLE
Automatically manage Firefox version upgrades

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#381]
We're currently pulling the latest Firefox binary from `https://index.taskcluster.net/v1/task/gecko.v2.mozilla-release.latest.firefox.linux64-add-on-devel/artifacts/public/build/target.tar.bz2`. This means that we'll get the latest version of the binary as soon as a new version release happens. This may completely break OpenWPM (as the latest upgrade to FF68 has).

We should use an alternate taskcluster URL and pull a static build from that. See https://tools.taskcluster.net/index/gecko.v2 for our options. Upgrades to the Firefox binary version should happen manually with a new PR updating the taskcluster link. That will let us run the full test suite and discover any breaking changes. We should also check the version of Firefox that the user has installed, and suggest that they upgrade when it's outdated. See also #66.

**Comment by englehardt** [comment]
We could pull from `https://index.taskcluster.net/v1/task/gecko.v2.mozilla-release.pushdate.2019.07.01.20190701165736.firefox.linux64-add-on-devel/artifacts/public/build/target.tar.bz2` for example, which matches the build currently returned from `https://index.taskcluster.net/v1/task/gecko.v2.mozilla-release.latest.firefox.linux64-add-on-devel/artifacts/public/build/target.tar.bz2`.

We could pull in `https://index.taskcluster.net/v1/task/gecko.v2.mozilla-release.latest.firefox.linux64-add-on-devel/artifacts/public/build/target.json`, read the latest Firefox binary version from that and warn when an update is available.

**Comment by motin** [comment]
Related: https://github.com/freaktechnik/get-firefox/issues/61

**Comment by motin** [comment]
Coincidentally, I ran into this python script for downloading old versions of Firefox today: https://github.com/jrbenny35/experiment-test-automation-suite/blob/master/utilities/download_old_firefox.py

**Comment by englehardt** [comment]
In #385 we hard code a specific unbranded Firefox build. My plan is to write a simple cron job to nudge me when builds with a new FF version are released, but this is just a stopgap solution to better crawl management. Ideally, we have some cloud job running that checks the latest version and stages a PR if a new build is available. That way we will run the new build against the test suite and upgrade if necessary.

**Comment by motin** [comment]
Good thoughts @englehardt. We could also consider configuring Travis to test against a matrix of Firefox versions that could correspond to nightly, beta, release or similar. In travis, we could allow the builds corresponding to nightly and beta to fail, so that they don't block passing PRs that work against release, but still continously warn us about breakage in upcoming versions - and let those issues optionally be mitigated in each PR as they arrive.

**Comment by motin** [comment]
As per https://github.com/mozilla/OpenWPM/pull/396/files, we probably need to monitor/parse that wiki page to get the builds that corresponds to specific releases.

**Comment by birdsarah** [comment]
You will soon be able to `conda install firefox` - https://github.com/conda-forge/staged-recipes/pull/9234. All other dependencies are already conda installable (give or take).

**Comment by motin** [comment]
> You will soon be able to conda install firefox - conda-forge/staged-recipes#9234. All other dependencies are already conda installable (give or take).

Thanks for sharing! That, together with dependabot creating PRs automatically on version upgrades, would definitely take us a big step towards automatic Firefox version upgrades! :)

**Comment by birdsarah** [comment]
Main firefox is now available. https://github.com/conda-forge/firefox-feedstock

I now need to make a `firefox-unbranded` which is what we need to install OpenWPM. But this should be trivial at this point. I'll keep everyone posted.

**Comment by vringar** [comment]
Alternative:
1. Go find the latest tag here:  https://hg.mozilla.org/releases/mozilla-release/tags
2. Go the hash provided for that tag
2. https://firefox-ci-tc.services.mozilla.com/tasks/index/gecko.v2.mozilla-release.revision.{tag goes here}.firefox/{linux64/macosx}-add-on-devel/target.{tar.bz2/dmg}

**Comment by englehardt** [comment]
It looks like we'll need to do this manually for now as part of the release process.
