### ISSUE TITLE
Define versioning and pypi publishing routines

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#391]
OpenWPM has historically had very sporadic and inconsistent versioning (entirely my fault). We can be better about this going forward, but we should first agree on which versioning routines we'd like to follow explore the option of publishing to pypi.

**Comment by motin** [comment]
Related to this, will the upcoming web extension-based version be v0.10 or v1.0 (presumably with a round of v1.0-betaN before tagging it as v1.0)?

**Comment by englehardt** [comment]
There's now a release checklist. See #716
