### ISSUE TITLE
Define issue culling policy

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#393]
This repository has over a hundred open issues, of which many are from 2015-2018. 
I assume that many of them either are either fixed, abandoned or irrelevant. Given resource constraints, it may be relevant to only keep up to date issues open that are known to affect users of the latest version of the platform.

Closing abandoned issues after a period of inactivity is easy to set up with https://github.com/apps/stale and would help with the type of issues that only appear once and does not get commented on / interacted with - something that indicates that it does not affect new users of the platform. 

Manually culling all old issues / feature requests / ideas and moving them to a wiki page for "Unsorted ideas/suggestions from previous years" could also be scheduled and done rather efficiently. This can be followed up with identifying patterns/themes in such old issues in order to discover potential overarching root causes and filing issues to address them specifically.

Ping @englehardt

**Comment by englehardt** [comment]
We are taking a manual approach to culling issues and it's working well.
