### ISSUE TITLE
Docker container

### ISSUE THREAD

**Issue by Zernez** [mozilla/OpenWPM#400]
Hello,
I try to build a docker file, but seems don't work. I see option with docker build--help  "-f" is for the name of file ("Dockerfile" in this case). "-t" option for a name:tag option.
It build something only out of "OpenWPM" directory with command "docker build /path-of-OpenWPM" but it don't work with commands write in the instruction. I have lost some things? Thank you.

fernandez@fernandez-ThinkCentre-M51:~/OpenWPM$ docker build -f Dockerfile -t openwpm
"docker build" requires exactly 1 argument.
See 'docker build --help'.

Usage:  docker build [OPTIONS] PATH | URL | -

Build an image from a Dockerfile

**Comment by motin** [comment]
Hi @Zernez, try this (from [here](https://github.com/mozilla/OpenWPM#docker-deployment-for-openwpm)):

```
docker build -f Dockerfile -t openwpm .
```

Notice the dot at the end :)

**Comment by Zernez** [comment]
Thank you :) But I had miss the dot in the past, I think. I try now to write manually without dot, and do the same....

**Comment by englehardt** [comment]
@Zernez did this fix it for you? If so, let's close.

**Comment by Zernez** [comment]
@englehardt no fix, because i was writing without dot at the start.

**Comment by Zernez** [comment]
The error now report the "permission denied" when I want to run. I have build the container correctly and added the permission on local server: "xhost +local:docker" (I have to modify xhost?) . I have tried with sudo too in OpenWPM directory. Thank you.

ferna@ferna-pc:~/OpenWPM$ mkdir -p docker-volume && docker run -v $PWD/docker-volume:/root/Desktop \
> -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix \
> -it openwpm python /opt/OpenWPM/demo.py
docker: Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post http://%2Fvar%2Frun%2Fdocker.sock/v1.39/containers/create: dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'

**Comment by motin** [comment]
@Zernez did you try this from [here](https://github.com/mozilla/OpenWPM#building-the-docker-container)?

> Note, in order to run Docker without root privileges, add your user to the docker group (sudo usermod -a -G docker $USER). You will have to logout-login for the change to take effect, and possibly also restart the Docker service.

**Comment by Zernez** [comment]
@motin I try to re-insert the command that you have linked and with closing-open session, launch the run for docker, and it is ok. It create all file and logs in a directory described. Thank you!

**Comment by motin** [comment]
Happy to hear that it works! :)
