### ISSUE TITLE
Clarify to Mozilla that the Firefox profiles are not owned by humans

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#405]
We should clarify to Mozilla that the Firefox profiles are not owned by humans, so that usage of OpenWPM does not affect general user retention / behavioral metrics. Neither should Firefox profiles used in OpenWPM be targeted for studies, auto-updates etc.

**Comment by motin** [comment]
Possible configurations to discuss:
* Disable studies?
* Disable telemetry?
* Leave enhanced tracking protection on by default?

**Comment by tdsmith** [comment]
Geckodriver switches updates and studies off and throws away telemetry by default: https://searchfox.org/mozilla-central/source/testing/geckodriver/src/prefs.rs -- would those prefs be applied for openwpm?

**Comment by englehardt** [comment]
They should be. We also apply our own set of prefs (though these need an audit / cleanup to make sure they're up to date): https://github.com/mozilla/OpenWPM/blob/master/automation/DeployBrowsers/configure_firefox.py#L89

**Comment by motin** [comment]
I love issues that require no further intervention :)
And I see that tracking protection is turned off by OpenWPM and that there is an issue regarding enabling it again (https://github.com/mozilla/OpenWPM/issues/101)
Closing.
