### ISSUE TITLE
Push Docker images in CI

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#411]
We already build Docker images in CI. [Pushing them](https://docs.travis-ci.com/user/docker/#pushing-a-docker-image-to-a-registry) allows for immediate access to these images without requiring users to build and push these images themselves.

**Comment by englehardt** [comment]
+1. This is especially helpful if one is on a low bandwidth connection.

**Comment by motin** [comment]
Docker images are now pushed by CI: https://hub.docker.com/r/openwpm/openwpm/tags
