### ISSUE TITLE
Simplify S3Aggregator using dask

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#427]
The S3Aggregator manually works with pyarrow and manually pushes to s3

dask handles reading and writing to s3 (and other remote storage) seamlessly in my experience. the api is very pandas like so should only be a code clean-up.

https://docs.dask.org/en/latest/remote-data-services.html

the same code could also write parquet locally.

```
file = 'local.parquet' or 's3://bucket/remote.parquet'
df.to_parquet(file)
```

**Comment by englehardt** [comment]
I don't think this is relevant anymore given the changes we're planning in #561 and #652, but please re-open if it is.
