### ISSUE TITLE
WebExt doesn't load on fresh nightly profile

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#428]
Steps to reproduce:

* On Nightly (70.0a1 (2019-07-29) (64-bit)) create a fresh profile
* Go to about:config and set `xpinstall.signatures.required` to false
* Go to about:addons and install openwpm.xpi built from latest build (a337b52eb172ceed9e2ab092a4ba0e1f7421ad29)
* Go to about:debugging -> This Nightly -> OpenWPM -> Inspect
* Console shows the following error:
![Screenshot from 2019-07-29 08-57-24](https://user-images.githubusercontent.com/1796208/62068023-cb2a5400-b1fa-11e9-94ae-0e7ee40b2089.png)

Expected OpenWPM messages, something like: 
![Screenshot from 2019-07-29 09-00-44](https://user-images.githubusercontent.com/1796208/62068035-d2e9f880-b1fa-11e9-90dc-40d4251b7b24.png)

**Comment by birdsarah** [comment]
I am also seeing this with a fresh profile on Developer Edition 69.0b8 (64-bit)

I am on Linux.

**Comment by birdsarah** [comment]
I can repeat on Windows with a fresh Developer Edition profile

**Comment by englehardt** [comment]
Did you set these prefs: https://github.com/mozilla/OpenWPM/blob/a337b52eb172ceed9e2ab092a4ba0e1f7421ad29/automation/DeployBrowsers/configure_firefox.py#L211-L213?

**Comment by englehardt** [comment]
The `browser.sockets` is undefined means that the extension is unable to access the sockets experiments API. We use an unbranded release build for that reason, but experiment APIs should work on all pre-release builds. See https://webextensions-experiments.readthedocs.io/en/latest/faq.html#why-is-my-experiment-undefined-on-beta-and-release

**Comment by birdsarah** [comment]
woot - thanks @englehardt.

* `xpinstall.signatures.required` was done otherwise install doesn't work
* `extensions.legacy.enabled` I had tried this once already BUT you have to uninstall and reinstall the addon after changing this pref.

Having completed that it worked! 

Thank you.
