### ISSUE TITLE
localstack dependency import issues

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#439]
The latest release of localstack (0.10.X) appears to have some dependency install issues. Specifically, it appears to fail to install any of the required dependent packages.

For examples, see:
* https://travis-ci.org/mozilla/OpenWPM/jobs/567950566#L2225
* https://travis-ci.org/mozilla/OpenWPM/jobs/568040169#L2236

Pinning to an older version (0.9.6) seems to fix the issue (https://github.com/mozilla/OpenWPM/pull/438/commits/413ce79c2f1075baac90cc0f44d0cdb91eedcf0a)

**Comment by motin** [comment]
> Pinning to an older version (0.9.6) seems to fix the issue

Sounds like a good solution for now.

**Comment by englehardt** [comment]
Closed by #440
