### ISSUE TITLE
Remove support for flash cookie saving

### ISSUE THREAD

**Issue by crankycoder** [mozilla/OpenWPM#444]
See: https://github.com/mozilla/OpenWPM/pull/426#issuecomment-517845707

We should disable Flash cookie support in OpenWPM.  

The `test_flash_cookies` test has been disabled in PR #426 already.

**Comment by englehardt** [comment]
This will require:
* removing flash from the [linux install script](https://github.com/mozilla/OpenWPM/blob/07fe54d08d9e758e40bd908ab95eb62085c13dbb/install-system.sh#L23-L39) and possibly the mac install script
* removing the [`mini-amf` dependency](https://github.com/mozilla/OpenWPM/blob/07fe54d08d9e758e40bd908ab95eb62085c13dbb/requirements.txt#L9)
* removing the [config option](https://github.com/mozilla/OpenWPM/blob/07fe54d08d9e758e40bd908ab95eb62085c13dbb/automation/default_browser_params.json#L12)
* removing the [dump command](https://github.com/mozilla/OpenWPM/blob/07fe54d08d9e758e40bd908ab95eb62085c13dbb/automation/Commands/profile_commands.py#L47-L104) and any related code for this command
* removing the [profile management commands](https://github.com/mozilla/OpenWPM/blob/07fe54d08d9e758e40bd908ab95eb62085c13dbb/automation/Commands/profile_commands.py#L47-L104) and any related code that calls these functions
* removing flash cookie [parsing utilities](https://github.com/mozilla/OpenWPM/blob/07fe54d08d9e758e40bd908ab95eb62085c13dbb/automation/Commands/utils/lso.py)
* removing any related documentation from `README.md`
* removing any related tests

**Comment by Abhi-khandelwal** [comment]
Can I work on this issue?

**Comment by englehardt** [comment]
@Abhi-khandelwal please feel free to :)!

**Comment by vringar** [comment]
@Abhi-khandelwal are you still working on this or could this be reassigned?

**Comment by svensevenslow** [comment]
If nobody is working on it can I pick this issue to work on?

**Comment by englehardt** [comment]
> body is working on it can I pick this issue to work on?

Yes, please do. Thanks :)

**Comment by svensevenslow** [comment]
Hi! I have opened a [PR](https://github.com/mozilla/OpenWPM/pull/593). Let me know what you think. Also this test [errored ](https://travis-ci.org/github/mozilla/OpenWPM/jobs/665443725?utm_medium=notification&utm_source=github_status)but re-triggering the build made the test [pass.](https://travis-ci.org/github/mozilla/OpenWPM/jobs/665453558?utm_medium=notification&utm_source=github_status).

**Comment by svensevenslow** [comment]
@vringar @englehardt Could please have a look at my [PR](https://github.com/mozilla/OpenWPM/pull/593)?

**Comment by englehardt** [comment]
This was almost entirely fixed by #593. #612 will finish it up.
