### ISSUE TITLE
Stateful crawl mechanics

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#446]
I have seen two methods in the literature for performing stateful crawls. There may be more.

In one: 
- a crawl of n k sites is run serially and the resulting profile is saved. 
- subsequently that profile (or manually tweaked versions of it) is loaded into many parallelized browsers to see the response

In another:
- two crawls of n k sites are run serially and the resulting profiles are saved and compared

I believe that support for stateful crawl involves the ability to save a profile at any point in time and load a profile at any point in time. But I just wanted to clarify that. 

It would likely be time efficient to crawl say 50 sites, then checkpoint (aka dump profile), then continue, and restart from the previous checkpoint if the current 50 fail for some reason. Perhaps this feature isn't necessary.

I just wanted to be super clear on what stateful support should look like.

**Comment by englehardt** [comment]
OpenWPM should support any model of stateful crawling the user wants once we have stateful crawling enabled again (via profile loading and saving). If there's a specific model that isn't supported please file a new issue for that.
