### ISSUE TITLE
Minimize data loss during unexpected shutdown

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#450]
In a recent pair of 108k crawls in GCP, this is what happened:

1. After an initial crawl run, about 83k crawl_history records were found in the S3 bucket (about 70%)
2. After creating a new crawl list (n = 25k) with the items of the original seed list that did not yet have a crawl_history record, about 18k more, or 101k crawl_history records in total, were found in the S3 bucket (about 72% of the 25k crawled made it)
3. After step 2 repeated with now a 7k list, about 107k crawl_history records were found in total  (about 85% of the 7k crawled made it)

I am filing this separate to https://github.com/mozilla/OpenWPM/issues/255, which addresses percentage of command failures in relation to the total number of commands submitted. This issue does not relate the value of bool_success in the crawl_history table, but to the existence of a record at all, and currently it seems that the data for around 15-30% of crawled sites in each crawl-attempt gets dropped.

**Comment by vringar** [comment]
With registering a [preStop Hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/) we should be able to flush an aggregator before the instance gets killed

**Comment by nhnt11** [comment]
We can use the preStop hook to run a script that sends a signal to the task manager which then shuts everything down and flushes data. Ideally we should also log the success/failure of this process.

**Comment by vringar** [comment]
Apparently we have a default grace period of 30s to clean up after ourselves, as per [the kubernetes docs](https://kubernetes.io/docs/concepts/workloads/pods/pod/#termination-of-pods)

**Comment by vringar** [comment]
MainThread: Inform everybody else to shutdown
WorkerThreads: Inform Extension of shutdown, wait for extension to report done, save profile, shutdown
Aggregator: Wait for WorkerThreads (possibly in the main thread), flush all data to Storage, and report crawl incomplete sites

**Comment by vringar** [comment]
Apparently we still might be forced to use non preemtible nodes as [per the GKE docs](https://cloud.google.com/kubernetes-engine/docs/how-to/preemptible-vms#kubernetes_constraint_violations) any nodes on preemptible instances might be terminated without any notice (including not running the preStop hook)

**Comment by vringar** [comment]
or we bother with [this complexity](https://medium.com/google-cloud/stateful-services-on-preemptible-nodes-with-google-kubernetes-engine-c73ac10b8253)

**Comment by englehardt** [comment]
This was addressed in several recent PRs
