### ISSUE TITLE
Support running OpenWPM crawls using Chrome

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#465]
For tracking support for running OpenWPM crawls using Chrome.

Some background:
In Dec 2016, [the stubs of the initially planned support for Chrome was removed](https://github.com/mozilla/OpenWPM/commit/fe04301f0a4ec983bc9b7410be01afd99dea3f9d), with the following comment from https://github.com/mozilla/OpenWPM/issues/118#issuecomment-266222837:

> Chrome support was one of our original goals that unfortunately never materialized. Despite that a code stub for launching Chrome was still hanging around, but it has no integration with the current platform. In fe04301 I've removed that code stub and throw an exception when chrome is specified.
> 
> We don't have any immediate plans to support Chrome. Doing so will require a bit of refactoring of OpenWPM to remove coupling with Firefox and a rewrite of most of the instrumentation (since we use an addon-sdk Firefox extension). That being said, I'm happy to provide specific pointers on what needs to be changed to support Chrome if you're interested in working on it.

Today, we no longer use an addon-sdk Firefox extension, but rather a Firefox web extension which with modest tweaking should run fine in Chrome. 

To support Chrome in the platform we'd need to rid ourselves of the privileged web extension experiments used for platform communication ([re-evaluate http/websockets](https://github.com/mozilla/OpenWPM/issues/464) or the [Devtools Protocol](https://github.com/mozilla/OpenWPM/issues/380) instead?), add Chrome configuration/deployment logic and in general run many tests to ensure compatibility.

**Comment by motin** [comment]
As mentioned, these are the parts to this: 
1. Tweak the webextension instrumentation to run properly in Chrome
2. Find a solution for platform communication without using Firefox-only privileged web extension experiments ([re-evaluate http/websockets](https://github.com/mozilla/OpenWPM/issues/464) or the [Devtools Protocol](https://github.com/mozilla/OpenWPM/issues/380) instead?)
3. (Re-)add Chrome configuration/deployment logic in python-land
4. Make tests pass when running against Chrome

**Comment by englehardt** [comment]
Out of scope for now. We don't have the resources to do it, and are already tied into FF-specific APIs.
