### ISSUE TITLE
Investigate changes necessary to drop support for Python 2

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#466]
[Python 2.7 life ends in 4 months and 15 days](https://pythonclock.org/). I noticed that our crawls run Python 2 by default, albeit OpenWPM supports Python 3 since quite a while back. Code maintenance will be easier with support for Python 2 dropped. I wonder if we could simply drop support for Python 2 as is?

**Comment by englehardt** [comment]
I'm fully supportive of dropping python 2.7 support. Perhaps more importantly, many of the dependencies are going to Python 3 only in 2020 (https://python3statement.org/). Here are the steps as I see them:
1. Simply disable the Travis tests to not constrain ourselves to continue writing code that's compatible with both, and make it clear in the documentation that OpenWPM is Python 3 only.
2. Remove dependency on the `six` package, and update all uses to Python 3 syntax
3. Remove all imports from `__future__`

That said. I don't think it's a priority to drop 2.7 support. Aside from (1), I think we should focus on other higher priority issues for the moment.

**Comment by motin** [comment]
Ok great, I think we could summarize this as follows:

1. Do this year

- [ ] Configure crawls to run Python 3 by default
- [ ] Disable the Python 2 Travis tests to not constrain ourselves to continue writing code that's compatible with both
- [ ] Make it clear in the documentation that OpenWPM is Python 3 only

2. Future cleanup

- [ ] Remove dependency on the six package, and update all uses to Python 3 syntax
- [ ] Remove all imports from __future__

Investigation complete :)

**Comment by englehardt** [comment]
With the merging of #532 these tasks are now all complete. Python 2 support is now fully removed.
