### ISSUE TITLE
Rely on external tools to achieve parallelism

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#470]
From https://github.com/mozilla/OpenWPM/pull/468/files#r315900063:
> Long-term we should think about removing a bunch of the worker management logic from OpenWPM and instead rely on external tools to achieve parallelism (like we're doing with kubernetes).

I agree, it should make the codebase leaner and easier to maintain.

**Comment by englehardt** [comment]
There may be some simplification possible here, but closing until we specific recommendations that we can discuss.
