### ISSUE TITLE
Add a method to S3Aggregator to synchronously commit data to S3

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#476]
The batching used by the S3Aggregator can lead to data loss as described in #450. This also makes it difficult to record basic diagnostic information regarding command success because the batched diagnostic data may also be lost if a node dies unexpectedly.

If we have a method that synchronously writes records to S3 this allows us to ensure that certain information is written before continuing the crawl. One use case is described in https://github.com/mozilla/OpenWPM/pull/468#pullrequestreview-277410535, but I also think this kind of synchronous writing can be combined with job queue batches and lease expiration to ensure that all batches are successfully collected (see: https://github.com/mozilla/OpenWPM/issues/443#issuecomment-519989829).

**Comment by Vishal19111999** [comment]
Is this repo good for first timers? Can anyone suggest me a good repo for python first timers?

**Comment by vringar** [comment]
Superseded by #562 as that is a non blocking approach
