### ISSUE TITLE
No log

### ISSUE THREAD

**Issue by Zernez** [mozilla/OpenWPM#482]
Hello,
I'm trying to run demo.py a simply scan of 2 site modified properly in "NUM_BROWSERS" and "sites". After running message with GET and no error, finally "BaseAggregator       - INFO     - Received shutdown signal!" it never create any log or database. Here the setting of the new files settings in "default_manager_params.json":   
   
    "extension_enabled": true,
    "cookie_instrument": true,
    "js_instrument": true,
    "js_instrument_modules": "fingerprinting",
    "http_instrument": true,
    "navigation_instrument": true,
    "save_content": true,

    "random_attributes": true,
    "bot_mitigation": true,
    "disable_flash": false,
    "profile_tar": null,
    "profile_archive_dir": null,
    "headless": true,
    "browser": "firefox",
    "prefs": {},

    "tp_cookies": "always",
    "donottrack": false,
    "disconnect": false,
    "ghostery": false,
    "https-everywhere": true,
    "adblock-plus": false,
    "ublock-origin": false,
    "tracking-protection": false

In "default_browser_params.json":

    "data_directory": "/home/fernex/Desktop/",
    "log_directory": "/home/fernex/Desktop/",
    "output_format": "local",
    "database_name": "crawl-data.sqlite",
    "log_file": "openwpm.log",
    "failure_limit": null,
    "testing": false,
    "s3_bucket": null,
    "s3_directory": null

This problem is started with the upgrading to the last version of various program files. I've missing something?

**Comment by englehardt** [comment]
Closing because of this bug's age. If you're still having issues feel free to file a new one. Sorry we never got back to you!
