### ISSUE TITLE
Some javascript URLs have "line XX > function" after them

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#49]
Will need to update [this regex](https://github.com/citp/OpenWPM/blob/master/automation/Extension/firefox/data/content.js#L104) to fix it. Should be able to check for eval or function.

**Comment by gunesacar** [comment]
Please see my PR. I added two new fields to the `javascript` table.
* `func_name` will hold the calling function name (when available). OpenWPM was discarding this.
* `script_loc_eval` will hold the eval/Function call details (e.g. "line XX > Function"). This is the optional part between the script URL and the line number.

From now on, `script_url` field will only contain the URL of the calling script, excluding the details of the eval/Function calls.

See, also: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error/Stack#Stack_of_eval%27ed_code

**Comment by gunesacar** [comment]
I realized that in some cases stack frame only contains the script filename, e.g.:
`function_name@xyz.js:489:7`

I suppose that's why it's called `filename` :)
https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIStackFrame

If we don't match the (now removed) regular expression, we may misinterpret the script filename `xyz.js` as the script URL. Not sure if that's desirable.

@englehardt , would you please reopen? Or let me know and I'll file a new issue.

**Comment by englehardt** [comment]
Good catch! Are the filenames which cause this issue relative filenames (similar to a relative url)? Or does it seem to be random? It would be helpful to know the cause.

**Comment by gunesacar** [comment]
I guess they should be relative to address bar or iframe URL, but this needs to be checked.
I'm also curious to find out about the cause.

**Comment by gunesacar** [comment]
`select * from javascript where script_url like "%line%" and script_url like "%>%" `
-> 0 rows (2017-06-23-passive_identity database)

So, line number problem seems to be addressed.

**Comment by gunesacar** [comment]
It seems relative script URLs are relative to the `document_url` - without the path.

I picked an example from the 2017-06-23-passive_identity crawl, where the `top_url` and `document_url` are different. I confirmed that the script is served from a URL under the `document_url`  domain. 

If needed, we can reconstruct the absolute script URL during the analysis.

**Comment by englehardt** [comment]
Okay, it seems like the best thing to do then would be to add a note to the documentation / instrumentation that this is possible and close this issue?
