### ISSUE TITLE
`save_javascript` does not save javascript, throw an error

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#493]
previously to save javascript, in demo.py you would set `browser_params[i]['save_javascript'] = True`. If I understand correctly, the correct call is now `browser_params[i]['save_content'] = ['javascript', ]`. 

The old command does not throw an error, meaning people with old crawling scripts may attempt to reuse them only to find javascript has not been saved. Suggest throwing an error for this deprecated argument or co-ercing it the new format if it's observed.

**Comment by englehardt** [comment]
Filed #495 for this request.
