### ISSUE TITLE
Document OpenWPM instrumentation and schema

### ISSUE THREAD

**Issue by Zernez** [mozilla/OpenWPM#496]
Hello, there is a info file or .py file (some method for insert values) that explain the columns into the tables of the output crawl-data.sqlite? Some columns are difficult to understanding like "frame_id", "parent_frame_id" ecc ecc, in "http_requests" or others. I've searched in "automation" folder all .py files to find some information, and I discover an array "data[]" that cointain some information in "DataAggregator" folder, but with few returns. Thank you.

**Comment by englehardt** [comment]
We have some outdated documentation [here](https://github.com/mozilla/OpenWPM/wiki/Instrumentation-Schema-Documentation), but I agree this is sorely needed.

**Comment by vringar** [comment]
This seems like a bit of a duplicate of #342

**Comment by englehardt** [comment]
> This seems like a bit of a duplicate of #342

Not exactly a duplicate, but I agree the tasks are linked. I've expanded the scope of that bug slightly to include this.
