### ISSUE TITLE
Memory watchdog monitors the geckodriver process instead of the Firefox process

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#501]
The [memory watchdog](https://github.com/mozilla/OpenWPM/blob/960fc5040cbeb188310fd89c8b7b93d7a8e35989/automation/TaskManager.py#L199-L211) in the `TaskManager` is meant to monitor the memory usage of the Firefox and decide whether the process should be restarted. Since the update to a multi-process version of Firefox, this instead monitors the memory consumption of the geckodriver process since this is the process that Selenium [returns a handle to](https://github.com/mozilla/OpenWPM/blob/960fc5040cbeb188310fd89c8b7b93d7a8e35989/automation/DeployBrowsers/deploy_firefox.py#L201-L207). To restore the intended functionality, we should instead traverse the process chain and sum the total memory used by the main Firefox process and all of its child processes.

Here's some sample code on how to do that when testing with `python -m test.manual_test --selenium`:

```python
import psutil

geckodriver = psutil.Process(pid=driver.service.process.pid)
firefox = geckodriver.children()[0]
for child in firefox.children():
    print(child.memory_info()[0] / float(2**20))
```

**Comment by boolean5** [comment]
Hi, I'd like to work on this. May I?

**Comment by vringar** [comment]
Go right ahead :)

**Comment by boolean5** [comment]
Hello again. I submitted a PR along with a few questions and comments here: https://github.com/mozilla/OpenWPM/pull/596
