### ISSUE TITLE
Restore XVFB-based headless mode

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#504]
By moving from XVFB to Firefox's built-in headless mode in #426 we no longer properly support WebGL. WebGL is likely not the only web API that doesn't work correctly under headless mode. This means that OpenWPM is even more detectable as a bot (see #448), but this also means that we won't be able to properly measure WebGL and may end up messing with the many fingerprinting scripts that use WebGL.

There's no need to remove the support for Firefox's built-in headless mode, but we should add back in support for XVFB under a different configuration parameter. The code removed in #426 is a good place to start.

**Comment by Flnch** [comment]
One thing I wonder about: XVFB works in combination with headful Firefox, does not it? Then the difference is that the screen output is not rendered on some screen but virtually in memory. Is the gained performance compared to Firefox headful without XVFB so big that this makes a difference? Or is there another reason why you would prefer XVFB over native headful Firefox?

**Comment by englehardt** [comment]
@Flnch The reason to prefer Firefox's native headless mode is cross-OS functionality. XVFB only work when X would normally be used to render the GUI. That's the case for Ubuntu, but not MacOS or Windows.

**Comment by birdsarah** [comment]
agreed at weekly meeting:

Add a new config parameter: display-mode

- Native
- Xvfb
- Headless
