### ISSUE TITLE
xhost replacements on macOS Catalina?

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#507]
I was trying to run a docker image on macOS Catalina 10.15 .
As a first issue I got:
```
./run-on-osx-via-docker.sh: line 18: xhost: command not found
```
And as a result of the broken X sharing, I got same result @SchnockNicolas in #474 

Now my question would be, is this a setup error on my part or has xhost been removed and we should replace it with something in ```./run-on-osx-via-docker.sh```.

**Comment by englehardt** [comment]
It looks like that run script requires [XQuartz](https://www.xquartz.org/) (unfortunately). You should be able to install it through brew and should follow [these instructions](https://stackoverflow.com/a/47309184). This is currently linked in the README, but I can see that it's easy to skim past. Let me make a quick update to clarify that.

**Comment by englehardt** [comment]
Requested your review on https://github.com/mozilla/OpenWPM/pull/510
