### ISSUE TITLE
Can't run on Ubuntu18.04.3 in virtual machine

### ISSUE THREAD

**Issue by linwhitehat** [mozilla/OpenWPM#537]
after installing OpenWPM  by running `./install.sh`
when I run python3 demo.py , error shows like these:
```
BrowserManager       - INFO     - BROWSER 1: Launching browser...
BrowserManager       - ERROR    - BROWSER 1: Crash in driver, restarting browser manager
Traceback (most recent call last):
  File "/home/lin/lxj/OpenWPM/automation/BrowserManager.py", line 409, in BrowserManager
    status_queue, browser_params, manager_params, crash_recovery)
  File "/home/lin/lxj/OpenWPM/automation/DeployBrowsers/deploy_browser.py", line 14, in deploy_browser
    manager_params, crash_recovery)
  File "/home/lin/lxj/OpenWPM/automation/DeployBrowsers/deploy_firefox.py", line 48, in deploy_firefox
    firefox_binary_path = get_firefox_binary_path()
  File "/home/lin/lxj/OpenWPM/automation/utilities/platform_utils.py", line 57, in get_firefox_binary_path
    "The `firefox-bin/firefox-bin` binary is not found in the root "
RuntimeError: The `firefox-bin/firefox-bin` binary is not found in the root of the  OpenWPM directory (did you run the install script (`install.sh`)?). Alternatively, you can specify a binary location using the OS environment variable FIREFOX_BINARY.
BrowserManager       - ERROR    - BROWSER 1: Spawn unsuccessful  | Proxy Ready: False  | Profile Created: False  | Profile Tar: False  | Display: False  | Launch Attempted: False  | Browser Launched: False  | Browser Ready: False 
^CTraceback (most recent call last):
Process Process-1:
  File "/home/lin/lxj/OpenWPM/automation/BrowserManager.py", line 150, in launch_browser_manager
    spawned_profile_path = check_queue(launch_status)
  File "/home/lin/lxj/OpenWPM/automation/BrowserManager.py", line 130, in check_queue
    'Browser spawn returned failure status')
automation.Errors.BrowserCrashError: Browser spawn returned failure status
```
How to fix up the problem?

**Comment by vringar** [comment]
Is there a firefox-bin folder in your project directory and does it contain an executable called firefox-bin?

**Comment by linwhitehat** [comment]
> Is there a firefox-bin folder in your project directory and does it contain an executable called firefox-bin?

No, I just downloaded the project by "git clone https://github.com/mozilla/OpenWPM.git" and followed the install steps to test OpenWPM.

**Comment by linwhitehat** [comment]
> Is there a firefox-bin folder in your project directory and does it contain an executable called firefox-bin?

I followed the steps from link "https://github.com/mozilla/OpenWPM/wiki/Setting-Up-OpenWPM", is there other guidance notes for me learning how to installing and use OpenWPM?

**Comment by linwhitehat** [comment]
> Is there a firefox-bin folder in your project directory and does it contain an executable called firefox-bin?

I followed the steps from [link,](https://github.com/mozilla/OpenWPM/wiki/Setting-Up-OpenWPM) is there other guidance notes for me to learn how to install and use OpenWPM?

**Comment by linwhitehat** [comment]
Add a note that I am in china and can not connect to archive.canonical.com，I have tried to use proxy but it didn't work for me.  The info shows below.

Would you like to install Adobe Flash Player? (Only required for crawls with Flash) [y,N]
Not installing Adobe Flash Plugin
Hit:1 http://mirrors.aliyun.com/ubuntu bionic InRelease                    
Hit:2 http://mirrors.aliyun.com/ubuntu bionic-security InRelease               
Hit:3 http://mirrors.aliyun.com/ubuntu bionic-updates InRelease                
Hit:4 http://mirrors.aliyun.com/ubuntu bionic-proposed InRelease               
Hit:5 http://mirrors.aliyun.com/ubuntu bionic-backports InRelease              
Err:6 http://archive.canonical.com bionic InRelease                            
  Cannot initiate the connection to archive.canonical.com:80 (2001:67c:1562::1c). - connect (101: Network is unreachable) Cannot initiate the connection to archive.canonical.com:80 (2001:67c:1360:8c01::1b). - connect (101: Network is unreachable) Cannot initiate the connection to archive.canonical.com:80 (2001:67c:1360:8c01::16). - connect (101: Network is unreachable) Could not connect to archive.canonical.com:80 (91.189.91.15). - connect (111: Connection refused) Could not connect to archive.canonical.com:80 (91.189.92.150). - connect (111: Connection refused) Could not connect to archive.canonical.com:80 (91.189.92.191). - connect (111: Connection refused)
Reading package lists... Done                                    
W: Failed to fetch http://archive.canonical.com/dists/bionic/InRelease  Cannot initiate the connection to archive.canonical.com:80 (2001:67c:1562::1c). - connect (101: Network is unreachable) Cannot initiate the connection to archive.canonical.com:80 (2001:67c:1360:8c01::1b). - connect (101: Network is unreachable) Cannot initiate the connection to archive.canonical.com:80 (2001:67c:1360:8c01::16). - connect (101: Network is unreachable) Could not connect to archive.canonical.com:80 (91.189.91.15). - connect (111: Connection refused) Could not connect to archive.canonical.com:80 (91.189.92.150). - connect (111: Connection refused) Could not connect to archive.canonical.com:80 (91.189.92.191). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by vringar** [comment]
Can you run `sudo apt-get update` on your VM and see if that completes successfully?

Our script exits at the first line that returns with an error code and I believe  `sudo apt-get update` fails for you because you have mirrors in your `/etc/apt/sources.list` that you can't reach.

If the command also fails if you run it from the command line then I would suggest you remove all non chinese entries from the mirror list and maybe consider  using [this file](https://gist.github.com/linkdesu/0cb141d26e067d116fcc) instead.

**Comment by linwhitehat** [comment]
> Can you run `sudo apt-get update` on your VM and see if that completes successfully?
> 
> Our script exits at the first line that returns with an error code and I believe `sudo apt-get update` fails for you because you have mirrors in your `/etc/apt/sources.list` that you can't reach.
> 
> If the command also fails if you run it from the command line then I would suggest you remove all non chinese entries from the mirror list and maybe consider using [this file](https://gist.github.com/linkdesu/0cb141d26e067d116fcc) instead.

thanks for the suggestion, I changed the source.list and it worked, I can run `apt-get update`  but while installing Openwpm, the warning occurred like this：
![image](https://user-images.githubusercontent.com/20349381/70389281-2f0a2800-19f8-11ea-915c-57d1dfb68bca.png)

**Comment by linwhitehat** [comment]
> Can you run `sudo apt-get update` on your VM and see if that completes successfully?
> 
> Our script exits at the first line that returns with an error code and I believe `sudo apt-get update` fails for you because you have mirrors in your `/etc/apt/sources.list` that you can't reach.
> 
> If the command also fails if you run it from the command line then I would suggest you remove all non chinese entries from the mirror list and maybe consider using [this file](https://gist.github.com/linkdesu/0cb141d26e067d116fcc) instead.

thanks for your suggestion！After I changed the source.list, I can run `sudo apt-get update` successfully and I installed Openwpm successfully! It worked for me, thanks a lot! The question has been solved perfectly and I need to add a suggestion that users in china install Openwpm with proxies in terminal.

**Comment by vringar** [comment]
:+1: Happy to help
