### ISSUE TITLE
Add `visit_id` to the keyword arguments of `run_custom_function`

### ISSUE THREAD

**Issue by hadiasghari** [mozilla/OpenWPM#539]
Is it possible to know the sequence's visit_id inside a custom function? (This would help matching database records for inserts done in the custom function.)

**Comment by englehardt** [comment]
Not currently, but it's an easy change:

1. Add `RUN_CUSTOM_FUNCTION` to https://github.com/mozilla/OpenWPM/blob/12b23cc2c490033d8e6e9c7381e3a4432b3ae361/automation/TaskManager.py#L446-L452

2. Pass this visit id into the argument dictionary https://github.com/mozilla/OpenWPM/blob/12b23cc2c490033d8e6e9c7381e3a4432b3ae361/automation/Commands/command_executor.py#L59-L66

3. Access the visit id using the keyword args dictionary, as is done here: https://github.com/mozilla/OpenWPM/blob/12b23cc2c490033d8e6e9c7381e3a4432b3ae361/test/test_custom_function_command.py#L33

**Comment by englehardt** [comment]
@hadiasghari if you happen to add this, we'd happily accept a PR :)

**Comment by vringar** [comment]
@svensevenslow Once you have finished work on your current issue, this might be a good follow-up to show how this is now easier to do

**Comment by svensevenslow** [comment]
According to the changes that will be made for[ issue#571](https://github.com/mozilla/OpenWPM/issues/571)

`visit_id = arg_dict["command"].visit_id`

this should give us the visit_id

**Comment by vringar** [comment]
This is now exposed in the way that @svensevenslow described it.
