### ISSUE TITLE
TypeError: exceptions must derive from BaseException

### ISSUE THREAD

**Issue by turban1988** [mozilla/OpenWPM#547]
I encounter the following exception when in the `TaskManager`.

```Python
Traceback (most recent call last):
  File "collect_links.py", line 55, in <module>
    manager.execute_command_sequence(command_sequence)
  File "<path>OpenWPM/automation/TaskManager.py", line 565, in execute_command_sequence
    self._distribute_command(command_sequence, index)
  File "<path>OpenWPM/automation/TaskManager.py", line 334, in _distribute_command
    thread = self._start_thread(browser, command_seq)
  File "<path>OpenWPM/automation/TaskManager.py", line 395, in _start_thread
    self._check_failure_status()
  File "<path>OpenWPM/automation/TaskManager.py", line 301, in _check_failure_status
    raise pickle.loads(self.failure_status['Exception'])
TypeError: exceptions must derive from BaseException
```

**Comment by vringar** [comment]
Can you figure out the type and the content of ` pickle.loads(self.failure_status['Exception']` ?

**Comment by englehardt** [comment]
Would you mind to share more of your logs so we can get an idea of when/where this happens. A reproducible website / test case would be very helpful as well.

**Comment by vringar** [comment]
I've started to see this in cloud crawls as well. Maybe we should just throw in an assert to then get better error messages

**Comment by vringar** [comment]
When messing around with #735 I found this error message in the logs, it appears that the error is the first element of the tuple.
Object was of type <class 'tuple'> and looked like (<class 'AssertionError'>, AssertionError("Result was False of <class 'bool'>\nassert F
alse"), <traceback object at 0x7f14954dfec0>).
