### ISSUE TITLE
Provide a way to change the Firefox binary location and other platform-wide settings

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#55]
There are many hardcoded constants.
- The Firefox binary location [here](https://github.com/citp/OpenWPM/blob/master/automation/platform_utils.py#L18) and [here](https://github.com/citp/OpenWPM/blob/master/automation/DeployBrowsers/deploy_firefox.py#L131)
- Timeouts [here](https://github.com/citp/OpenWPM/blob/master/automation/TaskManager.py#L252), [here](https://github.com/citp/OpenWPM/blob/master/automation/TaskManager.py#L216), and [here](https://github.com/citp/OpenWPM/blob/master/automation/BrowserManager.py#L37).
- Default screen resolution [here](https://github.com/citp/OpenWPM/blob/master/automation/DeployBrowsers/deploy_firefox.py#L15).
- Many others

We should move all of these to a central config/common file that we can import elsewhere.

**Comment by vringar** [comment]
Many of those are now part of the browser_params or manager_params and can be fully customized.
