### ISSUE TITLE
Create a script folder and create one main entry script

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#550]
There should only be one `setup.sh`/`install.sh` in the top level directory.
It should automatically detect arch and have a command line argument so you can run the dev setup as well ( `./install.sh dev`). This would allow us to more easily support multiple distributions and clean up the top level directory.

**Comment by vringar** [comment]
Good first issue because it's only tangentially related to the project and only requires knowledge of bash

**Comment by LilyLME** [comment]
Hello @vringar please assign this to me. :) I would like to work on it

**Comment by englehardt** [comment]
@LilyLME done! Thank you.
