### ISSUE TITLE
Remove is_full_page and is_frame_load in http_requests

### ISSUE THREAD

**Issue by eriktews** [mozilla/OpenWPM#565]
In the current version of OpenWPM, is_full_page and is_frame_load are used a bit inconsistently. The documentation on https://github.com/mozilla/OpenWPM/wiki/Instrumentation-Schema-Documentation#http-requests says:

is_frame_load - True if the request is for an iframe document
is_full_page - True if the request is for a top-level (i.e. tab) document

However, the code that determines those attributes on https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/webext-instrumentation/src/background/http-instrument.ts#L357 sets is_full_page to true for every request that is executed on behalf of the top level frame such as for example loading an image for a site that has no frame/iframes. However, is_frame_load is only set to true for requests that populate an entire frame/iframe with content, so in general only for requests that are supposed to return an HTML document. When an image is loaded from within an iframe, the is_frame_load attribute is false.

From my point of view, this is not very consistent, so I would suggest to do one of the following things:
- Either update the documentation to clearly state that what exactly the meaning of is_frame_load and is_full_page is according to what is currently being done in the source code.
- Update the source code to mark only those requests that load the top of an frame/iframe true here which means checking whether the type of the request is either main_frame or sub_frame according to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/ResourceType
- Update the source code so that all requests that are executed on behalf of the top frame are marked as is_full_page (frameId === 0) and those which are executed on behalf of a frame/iframe are marked as is_frame_load (frameId !== 0)
- Introduce two new fields in the database (for example is_for_full_page, is_for_frame), which takes the values from the previous item.

I'm happy to submit a patch for each of the variants, but first I would like to hear which variant is best.

**Comment by englehardt** [comment]
Thanks for the thorough submission!

> However, the code that determines those attributes on https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/webext-instrumentation/src/background/http-instrument.ts#L357 sets is_full_page to true for every request that is executed on behalf of the top level frame such as for example loading an image for a site that has no frame/iframes.

That's an error. The intended functionality is what's in the documentation.

>However, is_frame_load is only set to true for requests that populate an entire frame/iframe with content, so in general only for requests that are supposed to return an HTML document. When an image is loaded from within an iframe, the is_frame_load attribute is false.

That's expected, and matched the documentation.

> From my point of view, this is not very consistent, so I would suggest to do one of the following things:
> 
>     * Either update the documentation to clearly state that what exactly the meaning of is_frame_load and is_full_page is according to what is currently being done in the source code.
> 
>     * Update the source code to mark only those requests that load the top of an frame/iframe true here which means checking whether the type of the request is either main_frame or sub_frame according to https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/webRequest/ResourceType

This is the right fix.

>     * Update the source code so that all requests that are executed on behalf of the top frame are marked as is_full_page (frameId === 0) and those which are executed on behalf of a frame/iframe are marked as is_frame_load (frameId !== 0)
> 
>     * Introduce two new fields in the database (for example is_for_full_page, is_for_frame), which takes the values from the previous item.
> 
> 
> I'm happy to submit a patch for each of the variants, but first I would like to hear which variant is best.

**Comment by LilyLME** [comment]
@englehardt can I work on this?

**Comment by eriktews** [comment]
From my point of view it looks like an easy task. Don't forget to update the sqlite scema and the code for the pa file as well.

Am 19. März 2020 01:04:10 MEZ schrieb Asongfac Lily Rospeen <notifications@github.com>:
>@englehardt can I work on this?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/mozilla/OpenWPM/issues/565#issuecomment-600916946

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by englehardt** [comment]
> @englehardt can I work on this? and regarding the conclusion are we taking off both options or using `const isFullPageLoad = details.type === "main_frame";`?

Yes you can, thanks!

We'd like to remove both of these, and update the sql and parquet schemas as well.

**Comment by englehardt** [comment]
This was fixed by #590
