### ISSUE TITLE
Collect data on most popular trackers and website with most trackers

### ISSUE THREAD

**Issue by say-yawn** [mozilla/OpenWPM#569]
# About this Issue
As an engineer working on the Shavar services I want to know what are the trackers that are used most in the websites so that when a change in block list or the entity list is introduced in the [shavar-prod-lists](https://github.com/mozilla-services/shavar-prod-lists) I can warn the reviewer about the likelihood to cause breakage based on the popularity of the tracker. Also, to test for trackers being blocked or causing breakage, it would be helpful to get information on select websites with the most number of trackers to easily test these for potential breakage. 

# Acceptance Criteria
- [ ] Collect data on the top 500 trackers most frequently found on landing page of the website
- [ ] Collect data on websites with the most trackers to use as a testing website for breakages

#
Side Note: I think this would be an interesting way to measure how anti-tracking causes the change/shift in trackers.

**Comment by PatSpiegel** [comment]
link is broken, you meant? https://github.com/mozilla-services/shavar-prod-lists/

**Comment by englehardt** [comment]
This is something that should be tracked in another repo. We aren't going to track crawl requests here.
