### ISSUE TITLE
javascript execution without profile tar

### ISSUE THREAD

**Issue by MaazBinMusa** [mozilla/OpenWPM#570]
So i was trying to run the following function in the run_custom_function
```python
def callGet(path,mode,**kwargs):
    driver = kwargs['driver']
    js = "var output = [];"\
      "function getCPM()"\
      "{"\
      " var responses = pbjs.getBidResponses();"\
      " Object.keys(responses).forEach(function(adUnitCode){"\
      " var response = responses[adUnitCode];"\
      "     response.bids.forEach(function(bid)"\
      "     {"\
      "         output.push({"\
      "         ad: bid"\
      "         "\
      "         "\
      "         "\
      "         "\
      "         });"\
      "     });"\
      " });"\
      "}"\
      "getCPM();"\
      "return output;"
    status = driver.execute_script(js)
    #save the result in a file
    path = os.path.join(path,"Header_Bidding"+mode)
    if(not os.path.exists(path)):
        f = open(path,'w')
        f.close()
    f = open(path,'w')
    stl = [str(i) for i in status]
    st = ' '.join(stl)
    #print(st)
    f.write('\r\n')
    f.write(st)
    f.close()
    return
```
- I visit a site where doing pbjs.getBidresponses() works e.g accuweather
- I run the custom function that gathers ads
- It fails by saying:

![image](https://user-images.githubusercontent.com/19577994/75714779-ee861780-5c91-11ea-8319-e3334a7dfe45.png)

When I load a profile tar before doing this, it works smooth. The main issue is I manually wrote a selenium script that loads no profile and does this and it works, so it is an openwpm issue

**Comment by vringar** [comment]
Can you share the selenium script that you wrote?
Because from first impression this something that's happening in Selenium code (as `driver` is a Selenium class)

**Comment by MaazBinMusa** [comment]
> Can you share the selenium script that you wrote?
> Because from first impression this something that's happening in Selenium code (as `driver` is a Selenium class)

I use my own config files and not the default config but it has the same key value pairs plus a few of my own.


os.chdir('opt/OpenWPM')
config_path  = sys.argv[1] ## Config File Path
mode         = sys.argv[2] ## Flag for Mode ## 1 is ad collection 2 is persona without intent 3 in persona with intent

def callGet(path,mode,**kwargs):
    driver = kwargs['driver']
    js = "var output = [];"\
      "function getCPM()"\
      "{"\
      " var responses = pbjs.getBidResponses();"\
      " Object.keys(responses).forEach(function(adUnitCode){"\
      " var response = responses[adUnitCode];"\
      "     response.bids.forEach(function(bid)"\
      "     {"\
      "         output.push({"\
      "         ad: bid"\
      "         "\
      "         "\
      "         "\
      "         "\
      "         });"\
      "     });"\
      " });"\
      "}"\
      "getCPM();"\
      "return output;"
    status = driver.execute_script(js)
    #save the result in a file
    path = os.path.join(path,"Header_Bidding"+mode)
    if(not os.path.exists(path)):
        f = open(path,'w')
        f.close()
    f = open(path,'w')
    stl = [str(i) for i in status]
    st = ' '.join(stl)
    #print(st)
    f.write('\r\n')
    f.write(st)
    f.close()
    return

if(os.path.exists(config_path)):
    data = open(config_path,'r').read()
    data = json.loads(data)
    persona_path = data['Persona_Path']
    persona_name = data['Persona_Name']
    persona_numb = data['Persona_Numb']
    browser_params_path = data['Browser_Config']
    manager_params_path = data['Manager_Config']
    d_browser_params_path = data['Browser_Config_Def']
    d_manager_params_path = data['Manager_Config_Def']
    NUM_BROWSERS        = data['Number_of_Browsers']
    storage_file        = data['Storage_File']
    sites               = data['Sites']
    Ad_Sites       = data['Ad_Sites']
    Intent_Sites        = data['Intent_Sites']
else:
  print(config_path)
  print("Config File Does Not Exist")
  exit()


if(os.path.exists(persona_path)):
    if (os.path.exists(os.path.join(persona_path,persona_name))):
        print("[Starting Persona Training]-----")
    else:
        print("[Persona Type Does Not Exist] ----- CRITICAL, EXITING")
        exit()
else:
    print("[Persona Folder Not Available] ----- CRITICAL, EXITING")
    exit()

sites = data['Sites']

# Loads the manager preference and 3 copies of the default browser dictionaries
manager_params, browser_params = TaskManager.load_default_params(browser_params_path,manager_params_path,NUM_BROWSERS)
# Update TaskManager configuration (use this for crawl-wide settings)
# path = persona_path+'/../'+persona_name.replace(".json","").lower()+"_"+str(persona_numb)

path = browser_params[0]['profile_tar']
#path = '.'

# Update browser configuration (use this for per-browser settings)
for i in range(NUM_BROWSERS):
    #print(os.path.join(path,"profile.tar.gz"))
    # Record HTTP Requests and Responses
    browser_params[i]['http_instrument'] = True
    # Enable flash for all three browsers
    browser_params[i]['disable_flash'] = False
    browser_params[i]['headless'] = True  # Launch all browsers headless

    if(not os.path.exists(os.path.join(path,"profile.tar.gz"))):
        browser_params[i]["profile_tar"] = None
        print("set to None")
    browser_params[i]['storage_file']    = storage_file


os.chdir('../..')
manager_params['data_directory'] = os.path.join(os.path.dirname(os.path.abspath(__file__)),path)
manager_params['log_directory']  = os.path.join(os.path.dirname(os.path.abspath(__file__)),path)
os.chdir('opt/OpenWPM')

# Instantiates the measurement platform
# Commands time out by default after 60 seconds

manager = TaskManager.TaskManager(manager_params, browser_params)
# Persona Training Without Intent
# Persona Training Without Intent

if(mode != '1'):
  for site in sites:
      command_sequence = CommandSequence.CommandSequence(site)
      command_sequence.get(sleep=60, timeout=600)
      command_sequence.dump_profile_cookies(120)
      manager.execute_command_sequence(command_sequence, index='**')

  # Showing Intent if Needed
  # Showing Intent if Needed
  Intent_Sites = []
  if Intent_Sites != []:
      site = random.choice(Intent_Sites)
      command_sequence = CommandSequence.CommandSequence(site)
      command_sequence.get(sleep=60, timeout=600)
      command_sequence.dump_profile_cookies(120)
      manager.execute_command_sequence(command_sequence, index='**')

# Collecting Ads if Needed
# Collecting Ads if Needed
if(mode == '1'):
    Ad_Sites = ['https://www.accuweather.com/']
    for site in Ad_Sites:
        command_sequence = CommandSequence.CommandSequence(site)
        command_sequence.get(sleep=3, timeout=100)
        path = browser_params[0]['profile_tar']
        command_sequence.run_custom_function(callGet,(path,mode,))
        command_sequence.dump_profile_cookies(120)
        manager.execute_command_sequence(command_sequence, index='**')
# Shuts down the browsers and waits for the data to finish logging
manager.close()

**Comment by MaazBinMusa** [comment]
The issue was a resource loading issue. Increasing the timeout generously to 90 seconds solved this issue. No profile was needed.
