### ISSUE TITLE
Simplify command issuing in Task Manager

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#571]
https://github.com/mozilla/OpenWPM/blob/59e79a7adbb41b2a801b7f8fb9c2863cb6222cc7/automation/TaskManager.py#L443-L454

* Remove `start_time`, and entire `elif` block for dump profile cookies and dump flash cookies
* Change all other commands to accept the visit id, pass it to all commands (i.e., remove the `if` condition)
* Pass `crawl_id` to all commands for clarity.

**Comment by svensevenslow** [comment]
Hi! I'd like to work on this. Please assign me this issue.

**Comment by vringar** [comment]
Hey, there is some context to this issue that hasn't been written down yet. 
I'll quickly summarize of the top of my head:  
There should be a base class that contains visit_id and crawl_id and subclasses for every single command that may provide additional names fields.
[The command executor](https://github.com/mozilla/OpenWPM/blob/master/automation/Commands/command_executor.py) would then use [isInstance()](https://docs.python.org/3.5/library/functions.html#isinstance) to match on the type.
This way we have named attributes everywhere and no longer have to deal with `command[0]` and similiar

**Comment by svensevenslow** [comment]
So, I need to write these base classes and sub classes where specifically. I mean create a separate file or write in the TaskManager.py file. Also I would need to remove all instances of command[0] etc used in this repo and use isInstance() to check the type ?

**Comment by vringar** [comment]
I would expect you to create a `Commands.py` in automation/Commands.
Yes, that would be the goal of this. I'm hoping that this way everything is more explicit and easier to change in the future

**Comment by svensevenslow** [comment]
Hi! I have opened a Work in Progress [PR](https://github.com/mozilla/OpenWPM/pull/580). Please have a look.
