### ISSUE TITLE
Improve python development experience

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#579]
Currently when building the extension there are lots of linters and so on running to make sure to catch errors.
On the python side we currently only run flake8 for formatting and nothing else.
My list of tools to enhance the python developer experience is:
- [black](https://pypi.org/project/black/) as a formatter that removes the need to manually add line breaks or remove unneeded whitespace
- [pylint](https://www.pylint.org/) for error reports with more information than just style  
(this will probably need to be customized)
- [mypy](https://mypy.readthedocs.io/en/latest/) for type safety in combination with [pyannotate](https://github.com/dropbox/pyannotate) to generate type hints from execution

**Comment by vringar** [comment]
mypy --ignore-missing-imports --check-untyped-defs  --disallow-incomplete-defs  --disallow-untyped-defs

**Comment by shubhank-saxena** [comment]
@vringar can use Tox for multiple version python testing instead of running so many Travis test, as tox provides the facility to run it.
Also, implementing tox will help us clean travis.yml file

**Comment by vringar** [comment]
We have discussed internally that we don't want to/ have the staffing to actually support multiple versions of python and the tests already take way too long to run.
So I don't want to have multiple versions of python running the tests to multiply my test time.
I appreciate you thinking about this though.

**Comment by vringar** [comment]
Closing this issue as too broad.
