### ISSUE TITLE
Error in wiki

### ISSUE THREAD

**Issue by LilyLME** [mozilla/OpenWPM#588]
In the first like of the Wiki where WPM is describe, serves has to services

Web Privacy Measurement is the observation of websites and ~serves~ services to detect, characterize and quantify privacy-impacting behaviors.

**Comment by englehardt** [comment]
Thanks for the report. I think "serves" here was intended to refer to Web privacy Measurement. I.e., "Web Privacy Measurement serves to detect, characterize, and quantify..." but I like your phrasing :) I've updated it.
