### ISSUE TITLE
sqlite3.ProgrammingError: Cannot operate on a closed database in TestSimpleCommands.test_browse_wrapper_http_table_valid

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#594]
See https://travis-ci.org/github/mozilla/OpenWPM/jobs/664956158#L3994

**Comment by boolean5** [comment]
@englehardt, the above link points to a successful test run. I've seen this error appear in `TestExtension.test_canvas_fingerprinting` here though: https://travis-ci.org/github/mozilla/OpenWPM/jobs/664047781#L1862

**Comment by LilyLME** [comment]
This test happens to pass locally for me.

**Comment by englehardt** [comment]
Closing for now. We can file a new issue if we see this again.
