### ISSUE TITLE
Restore functionality of process watchdog

### ISSUE THREAD

**Issue by boolean5** [mozilla/OpenWPM#598]
The [process watchdog](https://github.com/mozilla/OpenWPM/blob/5a67ce87cd925eafc6831e4d6171ca781b9c1de4/automation/TaskManager.py#L216-L234) stopped being supported in 1db64ed. This issue investigates what would be required in order to make it functional again. Here are some ideas and questions. Any feedback is welcome.

1. First of all, is the process watchdog a feature we still need?

2. In a related discussion with @vringar in https://github.com/mozilla/OpenWPM/pull/596 we reached the conclusion that [this check](https://github.com/mozilla/OpenWPM/blob/5a67ce87cd925eafc6831e4d6171ca781b9c1de4/automation/TaskManager.py#L227) should change from `process.name() == 'firefox'` to `process.name() == 'geckodriver'`.
Then, if an unused geckodriver process is found, we should `kill()`/`terminate()` it along with all its descendant processes. But how exactly should this be implemented? Is [the approach](https://github.com/mozilla/OpenWPM/blob/5a67ce87cd925eafc6831e4d6171ca781b9c1de4/automation/BrowserManager.py#L324-L350) of `kill_browser_manager()` suitable here as well?

3. As far as I understand, the reason for disabling the process watchdog in 1db64ed is described in the [docstring](https://github.com/mozilla/OpenWPM/blob/5a67ce87cd925eafc6831e4d6171ca781b9c1de4/automation/TaskManager.py#L196-L197) of `_manager_watchdog()`:

        TODO: process watchdog needs to be updated since `psutil` won't
              kill browser processes started by Selenium 3 (with `subprocess`)

    Is this statement still valid?

4. Once 2 and 3 are resolved, we should remove the `ValueError` that [is raised](https://github.com/mozilla/OpenWPM/blob/5a67ce87cd925eafc6831e4d6171ca781b9c1de4/automation/TaskManager.py#L126) when the process watchdog is enabled. Finally, we should remove [comments](https://github.com/mozilla/OpenWPM/blob/5a67ce87cd925eafc6831e4d6171ca781b9c1de4/automation/TaskManager.py#L82) that point to https://github.com/mozilla/OpenWPM/issues/174 as the reason why the process watchdog is currently broken.

**Comment by boolean5** [comment]
I guess [this comment](https://github.com/mozilla/OpenWPM/pull/596#issuecomment-608228451) by @englehardt answers 2. Should we move [the code](https://github.com/mozilla/OpenWPM/blob/5a67ce87cd925eafc6831e4d6171ca781b9c1de4/automation/BrowserManager.py#L324-L350) that kills geckodriver and firefox processes into a separate `kill_browser()` function so that we can reuse it in the process watchdog? If yes, where should that function be implemented?

Also, @englehardt, could you provide some input about 3?

**Comment by englehardt** [comment]
This fix has already landed. Follow ups happening in #778 and #749
