### ISSUE TITLE
Fix crawl_history for RunCustomFunction command

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#604]
Currently saving our `crawl_history` uses `json.dumps` when completing a command which breaks on a function handle
https://github.com/mozilla/OpenWPM/blob/29a213456d65ce6e8256a452336e588d2753adc2/automation/TaskManager.py#L448
This might be a fix
```python
class CommandEncoder(json.JSONEncoder): 
   def default(self, o): 
       if type(o) == types.FunctionType: 
             return repr(o) 
        return json.JSONEncoder.default(self, o)                                                   
```
I don't understand why this doesn't show up in tests...

**Comment by vringar** [comment]
Apparently we just fail silently and never notice ....

**Comment by englehardt** [comment]
Fixed in https://github.com/mozilla/OpenWPM/pull/693
