### ISSUE TITLE
Rename and move some properties to where they belong

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#605]
`browser_pid` -> `geckodriver_pid` as this is no longer the Firefox pid
Move `visit_id` to be a property of the `command_sequence` instead of the `browser`
Edit: Scoped this more narrowly as #701 is for the discussion of crawl, browser and task

**Comment by shreyagupta30** [comment]
Hello @vringar can I work on this?

**Comment by vringar** [comment]
Sure :)

**Comment by vringar** [comment]
Hey @shreyagupta30  are you still on this?
Otherwise I'd pick this up myself.

**Comment by shreyagupta30** [comment]
Hi @vringar, you can take this up. Sorry!

**Comment by birdsarah** [comment]
@vringar can we scope down this issue to just:

* `browser_pid` -> `geckodriver_pid` as this is no longer the Firefox pid
* Move `visit_id` to be a property of the command_sequence instead of the browser

And have 701 for the task / crawl / browser?

**Comment by vringar** [comment]
Moving visit_id into the command_sequence is more work than expected, since we never pass the `CommandSequence`  to the `BrowserManager` only singular commands over the `command_queue`
