### ISSUE TITLE
run_custom_function test is silently failing

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#608]
See https://travis-ci.org/github/mozilla/OpenWPM/jobs/673635080#L2928-L2944. The failure is silent because it occurs in the command execution thread during cleanup. @vringar I know we discussed this general issue, just want to be sure this specific problem is on your radar.

**Comment by vringar** [comment]
This is a duplicate of #604 I just haven't gotten around to creating a PR for it yet
