### ISSUE TITLE
Start testing with pytest-localstack instead of localstack[full]

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#613]
A quick scroll brought me to this https://github.com/localstack/localstack#integration-with-nosetests

**Comment by vringar** [comment]
After a bit of investigation I can am fairly certain that this only works if you have a `[full]` installation of localstack.
`localstack start` is just a very elaborate wrapper around calling `docker run localstack/localstack` with the right parameters and such set.
We should probably just explore using [pytest-localstack](https://pytest-localstack.readthedocs.io/en/latest/)

**Comment by vringar** [comment]
Unfortunately the package doesn't seem well maintained so we might need to put some effort into upstreaming some fixes.
This however seems to be worth it, as removing our dependency on localstack[full] is currently blocking us on moving forward with conda

**Comment by birdsarah** [comment]
More worth it than doing the decoupling we discussed in the last meeting and splitting out the code that writes parquet locally?

**Comment by vringar** [comment]
I understood that as a seperate issue. Or did we just want to write out to filesystem and then let s3fs handle the syncing? Because then we once again loose the feedback if our data has actually been saved out, don't we?

**Comment by vringar** [comment]
I thought this was just another aggregator we wanted to implement, not a replacement for the current S3Parquet aggregator. I might have missed something in our discussion though.

**Comment by birdsarah** [comment]
> Or did we just want to write out to filesystem and then let s3fs handle the syncing?
That's my suggestion

> Because then we once again loose the feedback if our data has actually been saved out, don't we?
My general rule is that you don't need to test other people's libraries. We can assert the call to `s3fs.put` is made and assume `s3fs` knows how to put.

**Comment by birdsarah** [comment]
> I thought this was just another aggregator we wanted to implement, not a replacement for the current S3Parquet aggregator. I might have missed something in our discussion though.

That's not my understanding. My point was the the collection of data into parquet and the storage of them on a third party service do not need to be coupled. Decoupling them is a better technical solution and can allow easy integration of lots of 3rd party destinations.

**Comment by vringar** [comment]
> My general rule is that you don't need to test other people's libraries. We can assert the call to `s3fs.put` is made and assume `s3fs` knows how to put.
Does this mean we would just call `fs.close()` on shutdown and hope everything gets synced out before we get killed?

**Comment by vringar** [comment]
Using #618 or #427 we should remove all dependency on S3 explicitly and as such can remove localstack from our dependencies, which rn seems like the better solution.
