### ISSUE TITLE
Manage openwpm dependencies with conda

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#615]
We can use conda instead of running scripts that install programs into people's environments.

We need to consider how to handle a clean integration with pip requirements. Do we keep a requirements file? How do we pin things and keep things up to date?

Original WIP PR: #429

**Comment by vringar** [comment]
Whenever this gets addressed we should close #66

**Comment by shubhank-saxena** [comment]
@birdsarah any specific reason to go for conda packages? It would again cause conda as a dependency. If we want more generic, we can consider poetry as one (Plus its methods comply to PEP 518).

**Comment by birdsarah** [comment]
I'm afraid I've never heard of poetry before you mentioned it. Can you use poetry to install: firefox, node, redis, ....?

If yes, as best as I can tell from poetry it's still relatively young. 

Having worked for anaconda, I am not unbiased and it would be good to get additional input.

But conda / anaconda back AWS's EMR, Google's Dataproc, it's used at hundreds of very large companies along with over 19million users worldwide who've downloaded literally billion packages - it's really been put through the ringer and is a tried and tested cross-platform package-management solution.

**Comment by shubhank-saxena** [comment]
> I'm afraid I've never heard of poetry before you mentioned it. Can you use poetry to install: firefox, node, redis, ....?
> 
> If yes, then poetry and conda would be on par in terms of the desired functionality. But I would still think that conda is a safer option because, as best as I can tell, poetry is still relatively young. Conda is very well established:
> 
> * conda / anaconda back AWS's EMR, Google's Dataproc,
> * it's used at hundreds of very large companies along with
> * over 19million users worldwide who've downloaded literally billions of packages
> * it's really been used a lot, and is a tried and tested cross-platform package-management solution.
> 
> All that said, if poetry is feature compatible, given that I used to work for anaconda, I am not unbiased, and it would be good to get additional input.
> 
> [edited for clarity was typing on mobile]

Wow, these are really good features! Thanks for letting me know! Will study more about condo packaging. It sounds way more better than poetry
