### ISSUE TITLE
Expand saved Firefox profile to full directory

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#62]
Right now we restrict ourselves to just copying a few subcomponents of the profile. i.e. cookies and localStorage. Why not copy all files?

There may be some additional concerns such as extensions present in the profile directory that a user may not expect, but we can either constrain the browser configuration to be the same, or load and save the configuration alongside the profile.

**Comment by englehardt** [comment]
A full profile after a year or so of browsing can be around 500 MB. A new profile with very few page visits is around 20MB.

**Comment by boolean5** [comment]
When we expand the saved profile to the full directory we should also consider the following:
Now, [when restarting a crashed browser](https://github.com/mozilla/OpenWPM/blob/cb95ecc05fb4618e4275faecbc62b84123ebf1b0/openwpm/browser_manager.py#L101L115), we archive its profile in a tar file and then extract the contents of this tar file into the profile of a freshly started browser. Maybe we could skip this intermediate step and reuse the old profile directly instead.
