### ISSUE TITLE
IndexError in _manager_watchdog

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#626]
During a recent cloud crawl of a 1000 sites, I got the following error 3 times from the newly revamped _manager_watchdog.

We just need to handle the case where geckodriver has no children - presumably because of an unexpected failure.

```
IndexError: list index out of range
  File "threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "automation/TaskManager.py", line 215, in _manager_watchdog
    firefox = geckodriver.children()[0]
```

@boolean5 - am I right in thinking there's nothing more complicated to worry about here, just check if geckodriver has children before contininuing.

**Comment by boolean5** [comment]
@birdsarah, yes, checking if the geckodriver process has children before trying to access the Firefox process should be enough to avoid this. Thanks for pointing this out. I can send a patch if you haven't started working on it already. Let me know if I should. Thanks!

**Comment by birdsarah** [comment]
Lovely. Thanks!

**Comment by boolean5** [comment]
Here it is: https://github.com/mozilla/OpenWPM/pull/629
