### ISSUE TITLE
`prefs` isn't used anywhere (that i can tell)

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#632]
It's an empty dictionary in the default_browser_params.json and it's set in `crawler.py` but i can't see anywhere that it's used in the codebase. what's it for? setting additional custom preferences? that seems useful. would we add that here: https://github.com/mozilla/OpenWPM/blob/2f978c4cfba43df154431842e23754f78296ef66/automation/DeployBrowsers/deploy_firefox.py#L178?

**Comment by englehardt** [comment]
It's used here: https://github.com/mozilla/OpenWPM/blob/01dd4e12332527730ae4df50329f968de1c62785/automation/DeployBrowsers/deploy_firefox.py#L187-L193

And yes, it's meant for settings custom preferences.

**Comment by birdsarah** [comment]
Thanks! github search failed me! sorry for the noise.
