### ISSUE TITLE
Make "visitID is null when trying to insert into table" into a useful message

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#637]
This issue is the place to discuss how the visitID being unset should be handled by the extension
## The expected Flow
1. A ['GetCommand`](https://github.com/mozilla/OpenWPM/blob/master/automation/Commands/browser_commands.py#L116) sets the visitID  [in the extension](https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/firefox/feature.js/loggingdb.js#L36)
2. The `GetCommand` proceeds to visit a website, which causes the instrumentation to pick up information which is sent to `loggingdb.saveRecord`.
3. Once it is there the record is [assigned the current visitID](https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/firefox/feature.js/loggingdb.js#L171) and then saved out.
4. Once the CommandSequence is complete and a  [`FinalizeCommand`](https://github.com/mozilla/OpenWPM/blob/master/automation/Commands/browser_commands.py#L347) has been sent, [the extension unsets the visitID](https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/firefox/feature.js/loggingdb.js#L22) in the assumption that everything happening between now and the next visit is plattform internal stuff like visit `about:blank`
5. To make us aware of the broken assumption we [log all writes that are happening between visits](https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/firefox/feature.js/loggingdb.js#L180) as critical failures

## The faulty assumption
I somehow assumed that the tab would get closed after a visit but after looking at the code that this assumption was wrong.

## The Problem that arose in @birdsarah s test crawl
- The website isn't closed so we just write this information out with `visitID=-1`
- The logging is marked as critical which is way too high given that we expected this behaviour
- The message is formatted in a way that sentry can't effectively group them making the log aggregation ineffective

## Proposed fixes
1. Actually close the tab or at least navigate away once a visit is done. Making sure that this navigation away doesn't appear as website activity
2. Lower the log level of entries without visitIDs. The messages are still getting written out, it's just painful to match them to the visit they belong to
3. Fix the logging so that the extension logs get stripped of BrowserID as this is harmful to aggregation similiar to what is happening here [to the plattform logs](https://github.com/mozilla/OpenWPM/blob/master/automation/MPLogger.py#L174)

**Comment by birdsarah** [comment]
Given that this is all expected behavior, I would suggest a logLevel of debug.

**Comment by birdsarah** [comment]
> Actually close the tab or at least navigate away once a visit is done.

I thought we did this. But I see we just "close other windows"

https://github.com/mozilla/OpenWPM/blob/e1b0c2e89239d8ccbf9f9aec9cd22a26345f85b0/automation/Commands/browser_commands.py#L136

**Comment by vringar** [comment]
> Given that this is all expected behavior, I would suggest a logLevel of debug.
I would aim for warn because it indicates that our assumptions are wrong, @englehardt and the both of us assumed that there wouldn't be any more information. 
And once I've figured out a way to close the only open tab without closing the browser I'd like to go back to making that assumption because it's really helpful.
Also maybe there are like window.close listeners that send out some tracking stuff, that we would want to catch.

**Comment by englehardt** [comment]
> > Given that this is all expected behavior, I would suggest a logLevel of debug.
> 
> I would aim for warn because it indicates that our assumptions are wrong, @englehardt and the both of us assumed that there wouldn't be any more information.
> And once I've figured out a way to close the only open tab without closing the browser I'd like to go back to making that assumption because it's really helpful.
> Also maybe there are like window.close listeners that send out some tracking stuff, that we would want to catch.

Can we move https://github.com/mozilla/OpenWPM/blob/01dd4e12332527730ae4df50329f968de1c62785/automation/Commands/browser_commands.py#L113 to the end of the get command, instead of the beginning of a new command?

**Comment by vringar** [comment]
No, because that would e.g. break the keyboard command and all custom scripts would no longer have access to the current open window.
But we can move it into the beginning of the finalize command 
So that we go to about:blank and then unset the visit id

**Comment by englehardt** [comment]
@vringar this will be fixed by #589 right?

**Comment by vringar** [comment]
Yes. I should have put a comment for that somewhere sorry

**Comment by englehardt** [comment]
Fixed by https://github.com/mozilla/OpenWPM/pull/589
