### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by agogodavid** [mozilla/OpenWPM#643]
I'm trying to install openwpm on an ubuntu server (18.04) hosted on GCP and I keep getting this error - even with a vanilla install.

19 error code ELIFECYCLE
20 error errno 1
21 error OpenWPM@1.0.0 prebuild: `cd ../webext-instrumentation && npm run build && cd - && webpack`
21 error Exit status 1
22 error Failed at the OpenWPM@1.0.0 prebuild script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by vringar** [comment]
Hey @agogodavid,
Could you give us the full log as just this part doesn't seem to contain the information we need.

**Comment by agogodavid** [comment]
Thanks for the reply. I set this up successfully just last week, unsure what I'm doing wrong now.

  GNU nano 2.5.3                File: 2020-05-11T19_53_48_019Z-debug.log                                        
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/lib/node_modules/npm/bin/npm-cli.js',
1 verbose cli   'run',
1 verbose cli   '--@openwpm/webext-instrumentation:commitizen_path=./node_modules/cz-conventional-changelog',
1 verbose cli   'clean' ]
2 info using npm@6.14.4
3 info using node@v10.20.1
4 verbose run-script [ 'preclean', 'clean', 'postclean' ]
5 info lifecycle @openwpm/webext-instrumentation@0.4.0~preclean: @openwpm/webext-instrumentation@0.4.0
6 info lifecycle @openwpm/webext-instrumentation@0.4.0~clean: @openwpm/webext-instrumentation@0.4.0
7 verbose lifecycle @openwpm/webext-instrumentation@0.4.0~clean: unsafe-perm in lifecycle true
8 verbose lifecycle @openwpm/webext-instrumentation@0.4.0~clean: PATH: /usr/lib/node_modules/npm/node_modules/n$
9 verbose lifecycle @openwpm/webext-instrumentation@0.4.0~clean: CWD: /home/agogodavid/OpenWPM/automation/Exten$
10 silly lifecycle @openwpm/webext-instrumentation@0.4.0~clean: Args: [ '-c', 'trash build test' ]
11 silly lifecycle @openwpm/webext-instrumentation@0.4.0~clean: Returned: code: 74  signal: null
12 info lifecycle @openwpm/webext-instrumentation@0.4.0~clean: Failed to exec clean script
13 verbose stack Error: @openwpm/webext-instrumentation@0.4.0 clean: `trash build test`
13 verbose stack Exit status 74
13 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/index.js$
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spaw$
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid @openwpm/webext-instrumentation@0.4.0
15 verbose cwd /home/agogodavid/OpenWPM/automation/Extension/webext-instrumentation
16 verbose Linux 4.15.0-1061-gcp
17 verbose argv "/usr/bin/node" "/usr/lib/node_modules/npm/bin/npm-cli.js" "run" "--@openwpm/webext-instrumenta$
18 verbose node v10.20.1
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 74
22 error @openwpm/webext-instrumentation@0.4.0 clean: `trash build test`
22 error Exit status 74
23 error Failed at the @openwpm/webext-instrumentation@0.4.0 clean script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 74, true ]

**Comment by verybiigcat** [comment]
Hey @agogodavid, did you resolve this? I'm having the same on a fresh AWS EC2 Ubuntu 18.04 instance.

**Comment by verybiigcat** [comment]
@agogodavid I had a similar issue; not sure if you're experiencing the same but in case it helps:
I did not have the "build" directory created, hence why trash build was failing.
So I had to manually build it by performing "sudo npm install" under the /automation/Extension/webext-instrumentation folder; which created the build folder.
Then I went back and re-run install.sh
Hope this helps.

**Comment by agogodavid** [comment]
interesting. I'll try that. I ended up doing a work around. I used the
docker installation instructions, however, I edited the demo.py file with
my own list of domains to crawl first.

**Comment by birdsarah** [comment]
With #648 merged the install process has been completely reworked, so you may want to try a fresh install.

Not much has changed for building the extension, but when I was reworking the docker script I had a very similar issue to you @agogodavid, I'm not sure it's the same problem, but it sounds like it. As a result I tweaked the build_extension script to do an npm install in both directories and it seemed to help. The new Dockerfile also contains the minimal additional installs you need to make everything work on an minimal ubuntu: https://github.com/mozilla/OpenWPM/blob/master/Dockerfile#L14-L16

**Comment by birdsarah** [comment]
If you're willing to do a fresh install, I'd be really eager to know if we have sorted the issue you were facing with #648.

**Comment by agogodavid** [comment]
Actually, I tried @verybiigcat 's fix and it worked and then tried a fresh
install and that worked as well - so issue looks fixed!

**Comment by birdsarah** [comment]
@agogodavid - I understand that you fixed your issue, so I'll close this issue, but the new install infrastructure just got merged so if you are able to help us test it out by doing a fresh install that would be gratefully received.

**Comment by agogodavid** [comment]
Oh yes, that was what I meant. I fixed the issue using @verybiigcats work
around... and then I decided to run a fresh install and write up the steps
for a blogpost, and then doing that worked without the workaround. So yes,
the merge appears to have worked.
