### ISSUE TITLE
Wait for instrumentation to complete before navigating to page

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#646]
As I've been working on implementing generic JS instrumentation, it occurred to me, why don't we wait for the instrumentation to finish initializing before navigating to the page.

I'm aware that currently @vringar has implemented some shenanigans with going to about:blank initially. It maybe that this already covers this eventuality.

But, in theory, we could send a signal from the instrumentation.

(Maybe we already do, and I just didn't know).

**Comment by vringar** [comment]
I've just quickly scanned over this as it's quite late for me but from what I understand #135 is what you'd want.
We just haven't gotten around to it yet.

**Comment by birdsarah** [comment]
I thought so @vringar, but I just realized I'm wrong (and have updated issue name accordingly).

I realized that the JS instrumentation happens on every page load, so loading about:blank wouldn't help. 

We'd need to interrupt dom parsing to stop everything, load our instrumentation and then continue dom parsing. I can't imagine that is possible from a web extension, so closing.
