### ISSUE TITLE
ui-instrument: Instrument specific user interface properties / interactions

### ISSUE THREAD

**Issue by motin** [mozilla/OpenWPM#669]
I propose a ui-instrument for instrumenting specific user interface properties and interactions, such as:
 - Clicks
 - Scrolls
 - Keyboard event metadata
 - Frame dimensions / Viewport dimensions
 - Document/Page visibility (indicates if the window/tab is active)
 - HTML5 Media states (is a sound/video playing etc)
 - etc

Track basic user interaction was desired in a previous study, comparing data collected during genuine user traffic vs crawls (https://github.com/mozilla/jestr-pioneer-shield-study/issues/5). One use-case is to detect violations of cookie policies where user consent / interaction is required before cookies are set.

Frame dimensions (useful to detect small/hidden iframes) has its own issue (https://github.com/mozilla/OpenWPM/issues/349), and is related to this issue as a possible home for its implementation.

Document/page visibility is useful to differentiate between activity from background vs foreground windows/tabs. 

HTML5 media states are useful to understand if there is video/audio (could be ads) playing / auto-playing during capture.

**Comment by englehardt** [comment]
See https://github.com/mozilla/OpenWPM/pull/675#issuecomment-645683737
