### ISSUE TITLE
DNS Resolve Integration and write to Database

### ISSUE THREAD

**Issue by normannator** [mozilla/OpenWPM#670]
I am a beginner on working with OpenWPM and I want to integrate a dns resolve ([Tool](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dns/resolve))
 in the crawl, so that each first party cookie, that was created, go through a dns resolve and this result should be written in a separate SQLite table. Could you please give me a hint, where I can integrate this functionality? Greetings

**Comment by turban1988** [comment]
Hi everyone,
I would also welcome a feature that allows storing DNS data related to each request in a separate table in the database. This feature would enable one to reason about the origin/destination of each request, which might be interesting concerning legislation like the GDPR or CCPA. The named [dns.resolve()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/dns/resolve) API of Firefox seems to be an excellent candidate to integrate this feature into OpenWPM.
Best,
Tobias

**Comment by turban1988** [comment]
Hello,
I worked a little bit on this. 

- I created an` browser_params[i]['dns_instrument'] = True` command that indicates if the DNS requests should be resolved and written to the database.
- I wrote an `DnsInstrument` class in the extension that utilizes the `dns` API of Firefox  (see below) and made several smaller adjustments that the class is used and that the data is written to the database, if necessary.

However, I get several ``visitID is null while attempting to insert `` errors when running the crawler. I am not very familiar with the inner workings of the extensions and would be happy if you could hint where I should look for the problem. The errors are not for every request and across different tables. I also attached a logfile of a crawl,
[openwpm.log](https://github.com/mozilla/OpenWPM/files/4723048/openwpm.log)

### DnsResolver class:
```
import { PendingRequest } from "../lib/pending-request";
import { DnsResolved } from "../schema";
import BlockingResponse = browser.webRequest.BlockingResponse;
import RequestFilter = browser.webRequest.RequestFilter;
import ResourceType = browser.webRequest.ResourceType;
import {
  WebRequestOnBeforeRequestEventDetails,
} from "../types/browser-web-request-event-details";


export class DnsInstrument {
  private readonly dataReceiver;
  private onBeforeRequestListener;
  private pendingRequests: {
    [requestId: number]: PendingRequest;
  } = {};
  
  constructor(dataReceiver) {
    this.dataReceiver = dataReceiver;
  }
  
  public run(crawlID){
    const allTypes: ResourceType[] = [
      "beacon",
      "csp_report",
      "font",
      "image",
      "imageset",
      "main_frame",
      "media",
      "object",
      "object_subrequest",
      "ping",
      "script",
      // "speculative",
      "stylesheet",
      "sub_frame",
      "web_manifest",
      "websocket",
      "xbl",
      "xml_dtd",
      "xmlhttprequest",
      "xslt",
      "other",
    ];
    const filter: RequestFilter = { urls: ["<all_urls>"], types: allTypes };
    
    const requestStemsFromExtension = details => {
        return (
          details.originUrl && details.originUrl.indexOf("moz-extension://") > -1 && details.originUrl.includes("fakeRequest") !== -1
        );
    };
    /*
     * Attach handlers to event listeners
     */
    this.onBeforeRequestListener = (
      details: WebRequestOnBeforeRequestEventDetails,
    ) => {      
      //TODO: Why are there so many "visitID is null while attempting to insert " errors? The following code is not helping... I think
      // Ignore requests made by extensions
      if (requestStemsFromExtension(details)) {
        return blockingResponseThatDoesNothing;
      }
      const blockingResponseThatDoesNothing: BlockingResponse = {};
      const pendingRequest = this.getPendingRequest(details.requestId);
      pendingRequest.resolveOnBeforeRequestEventDetails(details);
          
      this.onBeforeRequestDnsHandler(
        details,
        crawlID,
      );
      
      return blockingResponseThatDoesNothing;
    };
    
    browser.webRequest.onBeforeRequest.addListener(
      this.onBeforeRequestListener,
      filter,
    );
  }
    
  public cleanup() {
    if (this.onBeforeRequestListener) {
      browser.webRequest.onBeforeRequest.removeListener(
        this.onBeforeRequestListener,
      );
    }
  }
  
  private getPendingRequest(requestId): PendingRequest {
    if (!this.pendingRequests[requestId]) {
      this.pendingRequests[requestId] = new PendingRequest();
    }
    return this.pendingRequests[requestId];
  }

  private handleResolvedDnsData(dnsRecordObj, dataReceiver) {
    // Curring the data returned by API call.
    return function(record) {
      // Get data from API call
      dnsRecordObj.addresses = record.addresses.toString()
      dnsRecordObj.canonical_name = record.canonicalName 
      dnsRecordObj.is_TRR = record.isTRR

      // Send data to main OpenWPM data aggregator.
      dataReceiver.saveRecord("dns_responses", dnsRecordObj);
    }
  }
  
  private async onBeforeRequestDnsHandler(
    details: WebRequestOnBeforeRequestEventDetails,
    crawlID,
  ) {
      // Create and populate DnsResolve object
      const dnsRecord = {} as DnsResolved;
      dnsRecord.crawl_id = crawlID;
      dnsRecord.request_id =  details.requestId;
      const currentTime = new Date(details.timeStamp);
      dnsRecord.time_stamp = currentTime.toISOString();
      
      // Query DNS API
      const url = new URL(details.url);
      dnsRecord.hostname = url.hostname;
      const dnsResolve = browser.dns.resolve(dnsRecord.hostname, 
					["bypass_cache", "canonical_name"]);
      dnsResolve.then(this.handleResolvedDnsData(dnsRecord, this.dataReceiver));
    }
    
}
```
### Example error I get:
`visitID is null while attempting to insert {"incognito":0,"crawl_id":1,"extension_session_uuid":"55ec3346-b771-482a-ba41-04675cb79561","event_ordinal":176,"window_id":1,"tab_id":1,"frame_id":0,"request_id":"66","url":"https://static.juicer.io/fonts/fontawesome-webfont.woff","method":"GET","time_stamp":"2020-06-03T11:37:48.987Z","referrer":"https://www.princeton.edu/sites/default/files/css/css_Y-CBClkz8jke08nngnzwoA3lT4dOqKHchFLt2DxUUIo.css","headers":"[[\"Host\",\"static.juicer.io\"],[\"User-Agent\",\"Mozilla/5.0 (X11; Linux x86_64; rv:75.0) Gecko/20100101 Firefox/75.0\"],[\"Accept\",\"application/font-woff2;q=1.0,application/font-woff;q=0.9,*/*;q=0.8\"],[\"Accept-Language\",\"en-US,en;q=0.5\"],[\"Accept-Encoding\",\"identity\"],[\"Referer\",\"https://www.princeton.edu/sites/default/files/css/css_Y-CBClkz8jke08nngnzwoA3lT4dOqKHchFLt2DxUUIo.css\"],[\"Origin\",\"https://www.princeton.edu\"],[\"Connection\",\"keep-alive\"]]","is_XHR":0,"triggering_origin":"https://www.princeton.edu","loading_origin":"https://www.princeton.edu","loading_href":"https://www.princeton.edu/","resource_type":"font","top_level_url":"https://www.princeton.edu/","parent_frame_id":-1,"frame_ancestors":"[]","visit_id":null} into table http_requests`

**Comment by turban1988** [comment]
If there is a general interest in this feature, I could send some cycles developing it.
