### ISSUE TITLE
Add column to crawl_history table to capture how long command took

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#679]
I'd like to get some kind of idea of how long different commands are taking. 
My motivation is to be able to debug "performance" when instrumenting lots of APIs. I'm thinking about a very crude python timer added around here: 
https://github.com/mozilla/OpenWPM/blob/a811af1c9c1f8efa4b9d2a008c6cbb3e5be6d1e8/automation/TaskManager.py#L469
Obviously this number will need to be understood carefully, but I still think it'll be useful.

The other place I think it could be useful in the future is in quantifying the amount of time we spend in "finalize". Now that we can introspect this part of the crawl, it feels like an area we may want to tune in the future in order to optimize cost of crawling.

For this issue to be closed the following things need to be done:
1. Add a  `duration` column of type `int` to the `crawl_history` table both for the [SQL](https://github.com/mozilla/OpenWPM/blob/a811af1c9c1f8efa4b9d2a008c6cbb3e5be6d1e8/automation/DataAggregator/schema.sql#L41) as well as for the [Parquet](https://github.com/mozilla/OpenWPM/blob/a811af1c9c1f8efa4b9d2a008c6cbb3e5be6d1e8/automation/DataAggregator/parquet_schema.py#L26) schema
2. Add 
    ```python
    t1 = time.time()
    ``` 
    before
    https://github.com/mozilla/OpenWPM/blob/a811af1c9c1f8efa4b9d2a008c6cbb3e5be6d1e8/automation/TaskManager.py#L469
3. Add another line here
https://github.com/mozilla/OpenWPM/blob/a811af1c9c1f8efa4b9d2a008c6cbb3e5be6d1e8/automation/TaskManager.py#L521-L537
saying
```python
"duration": time.time()-t1
```

**Comment by vringar** [comment]
@joy2306 does this list make this a little clearer?

**Comment by vringar** [comment]
@ankushduacodes Is this something you'd be interested in working on?

**Comment by ankushduacodes** [comment]
@vringar For sure!... Do you have any pointer for me to look for?

**Comment by vringar** [comment]
I'd suggest you first fix the watchdog before having a look at this. However can you tell me what is unclear to you after reading the issues description?

**Comment by ankushduacodes** [comment]
@vringar I am gonna start working on this one now.

**Comment by ankushduacodes** [comment]
@vringar I added a new column named duration to both [SQL](https://github.com/mozilla/OpenWPM/blob/a811af1c9c1f8efa4b9d2a008c6cbb3e5be6d1e8/automation/DataAggregator/schema.sql#L41) and [Parquet schema](https://github.com/mozilla/OpenWPM/blob/a811af1c9c1f8efa4b9d2a008c6cbb3e5be6d1e8/automation/DataAggregator/parquet_schema.py#L26)
and I have also added the time.time() lines in accordance with issue description.

But when I try to run demo.py file, I get a sql operational error saying `<class 'sqlite3.OperationalError'>
table crawl_history has no column named duration`

What could be the reason? How can I rebuild the schema?

**Comment by vringar** [comment]
You need to delete the existing database for the table to be rewritten. So consider deleting or moving the database on your Desktop. Then everything should work.

**Comment by ankushduacodes** [comment]
@vringar Shouldn't the new duration column be of type `float` instead of `int`?

**Comment by vringar** [comment]
I think casting these `float`s to `int`s is acceptable since dealing with `int` values is a lot nicer when having to do data analysis.
Maybe use [time_ns](https://docs.python.org/3/library/time.html#time.time_ns) and then save the result in milliseconds.

**Comment by ankushduacodes** [comment]
@vringar I have made a pull request regarding this, Please let me know if any changes are required....
