### ISSUE TITLE
Javascript instrumentation should be configurable per-API

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#68]
In the current implementation, javascript instrumentation is configured at the bottom of [content.js](https://github.com/citp/OpenWPM/blob/master/automation/Extension/firefox/data/content.js#L390-L442). As the number of APIs grows and the number of logging options increases, this will not scale and will lead a much unnecessary instrumentation.

Instead, we should consider having `content.js` parse an external configuration file. One format we've considered is the following:

```
'<API Name>: {
    logging: <all, none>,
    excluded_properties: [],
    included_properties: [],
    logging_flags: [logCallBack, logFunctionsAsStrings, ...]
},
'CanvasRenderingContext2D.prototype': {
...
},
...
```

**Comment by englehardt** [comment]
Tracking in https://github.com/mozilla/openwpm-webext-instrumentation/issues/8

**Comment by vringar** [comment]
https://github.com/mozilla/openwpm-webext-instrumentation/issues/8 was migrated to #353 which is closed. So I'm closing this as well
