### ISSUE TITLE
Enable dump_profile

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#680]
@MphDevelopment needs stateful crawling for an experiment they wanted to run. This issue outlines the steps that need to be taken to get to a version of stateful crawling that works to satisfy [the given requirements](https://view.matrix.org/room/!pFJihVSEWzcMCcOzSH:mozilla.org/?anchor=$jitB6DiHAZJwyYeu08yE8E51v_VfUejEQApxjNGs6zw&offset=-10&highlight=$jitB6DiHAZJwyYeu08yE8E51v_VfUejEQApxjNGs6zw)
Since we are aiming for a minimum viable product we only care about the happy path and ignore all error handling.
As such the only thing needed is restoring the functionality of [dump_profile](https://github.com/mozilla/OpenWPM/blob/5ffde00ecd5ecaa9105b74935490e5e267596eb7/automation/Commands/profile_commands.py#L38).

The envisioned workflow would look something like:
- Visit the site at 8am with no given profile and afterwards dump out a profile to `8am_profile.tar.gz`
- At 1PM you'd set `browser_params[0]['profile_tar'] = absolute path of 8am_profile.tar.gz`,
visit the site and then dump_profile to `1pm_profile.tar.gz`
- At 8 PM you'd do the same as at 1PM

There is an [old issue](https://github.com/mozilla/OpenWPM/issues/253) discussing this, but quite a lot has changed since then so anything in that issue might be out of date.

**Comment by MphDevelopment** [comment]
Thanks for the information, i'll look into it !

**Comment by englehardt** [comment]
This issue is a bit confusing without context from matrix. @vringar would you mind to add context here? Not sure if this is just for helping MphDevelopment?

**Comment by vringar** [comment]
@MphDevelopment just checking in. Do you need guidance or assistance on anything?

**Comment by MphDevelopment** [comment]
Thanks for checking !
We haven't started on the issue yet, we're still in the research part of the study..
I'll let you know if i need assistance on this ! 

For now i've only tried running OpenWPM with docker, and met some bugs related to npm that seems to magically not be triggered sometimes, i'm trying to understand the issue with it.
