### ISSUE TITLE
Problem in Json serializable

### ISSUE THREAD

**Issue by alexsavv** [mozilla/OpenWPM#692]
Hi, i try to create a task in OpenWPM and i have the error "Object of type function is not JSON serializable"

The task works fine but there is problem in TaskManager.py (line 489) ,which tries to convert "command.__dict__"  to a json format.
I send also two photos. The one shows my task and the other the error.
Please answer me if it is a problem due to my code.  

![task](https://user-images.githubusercontent.com/58025460/85272780-4b961b00-b485-11ea-8bfd-3b616a24748a.png)

![error](https://user-images.githubusercontent.com/58025460/85272532-f4904600-b484-11ea-90b8-a9a077ea94e1.png)

Thanks a lot,
   Alexandros

**Comment by vringar** [comment]
Hey Alexandros,
I don't think this is an issue with your code.
I remember seeing this issue but thought we had fixed it. I'm sorry about that.
Would you mind posting the code as text so it's easier for me to reproduce the issue?
