### ISSUE TITLE
An issue in Json format

### ISSUE THREAD

**Issue by Christlev** [mozilla/OpenWPM#698]
Hi, i am new in the OpenWPM tool. I want to visit some websites and get the title of them but i have an exception. I search it and i found that it is from OpenWPM code

The exception is:
  TaskManager          - INFO     - BROWSER 41: Received failure status while executing command: RunCustomFunctionCommand(<function  get_title at 0x7f47dfff7830>,())                                                 

  TypeError: Object of type function is not JSON serializable

  This exception is referred to TaskManager.py line 489  --> <"arguments": json.dumps(command.__dict__).encode('utf-8')>

Thanks a lot

**Comment by englehardt** [comment]
@Christlev would you mind to share the crawl script you're using to run the crawl? (Your version of demo.py)

**Comment by Christlev** [comment]
As you will see the script doesn't crash ,but it throws a Type Error.
    TypeError: Object of type function is not JSON serializable

The code is at:
    https://github.com/Christlev/DemoOpenWPM/blob/master/openwpm_demo.py

**Comment by Christlev** [comment]
> As you will see the script doesn't crash ,but it throws a Type Error.
> TypeError: Object of type function is not JSON serializable
> 
> The code is at:
> https://github.com/Christlev/DemoOpenWPM/blob/master/openwpm_demo.py

**Comment by vringar** [comment]
Why did you reopen this when https://github.com/mozilla/OpenWPM/pull/693 closed this?

**Comment by englehardt** [comment]
> @englehardt Why did you reopen this when #693 closed this?

Ah I missed that this was fixed by #693. We can close then
