### ISSUE TITLE
Clean up un-context-managed use of open

### ISSUE THREAD

**Issue by birdsarah** [mozilla/OpenWPM#708]
I somehow came to the opinion that `open()` no longer needed to be used with `with` as best practice. This is wrong.
Should be cleaned up from some commits in my recent PRs.

Good practice reference: https://docs.python.org/3/tutorial/inputoutput.html#reading-and-writing-files: "It is good practice to use the `with` keyword when dealing with file objects. The advantage is that the file is properly closed after its suite finishes, even if an exception is raised at some point."

**Comment by birdsarah** [comment]
Having done a quick search there are also some other instances. Let's clean them up all in one go. As an example, it's this kind of change: https://github.com/mozilla/OpenWPM/pull/642/commits/95465a8d1e4945265b70aeaed9215a2a6919a073

**Comment by jyothisjagan** [comment]
Hi @birdsarah , Can I work on this issue?

I was trying to setup the environment on my Debian 10.5 system. I did run tests after running install.sh. Currently two tests are resulting in error(see the output of py.test -vv [here](https://bin.disroot.org/?f913dfa09ad7f4a7#DwRgf6auj7vm55eRyWS4aGkQzzk7kbsfisd5yhhgMSn1)). But when I run only those two tests, it passes(see the [output](https://bin.disroot.org/?42f12dec4472c731#8Ftevu24pPSNcXfYUGWX69Zq6uVEKMnQwiXWCfWsxcXb)). Could you please help me to solve this?

**Comment by vringar** [comment]
Hey @jyothisjagan, thank you for expressing interest in this issue.

As for the tests breaking have you looked at point 3 in our troubleshooting section of our README.md 
> If you see errors related to incompatible or non-existing python packages, try re-running the file with the environment variable PYTHONNOUSERSITE set. E.g., PYTHONNOUSERSITE=True python demo.py. If that fixes your issues, you are experiencing issue 689, which can be fixed by clearing your python user site packages directory, by prepending PYTHONNOUSERSITE=True to a specific command, or by setting the environment variable for the session (e.g., export PYTHONNOUSERSITE=True in bash). 

If the tests are still broken then file another issue for this

**Comment by jyothisjagan** [comment]
Hi @vringar, thank you for the response.

I have tried setting PYTHONNOUSERSITE, but it did not solve the issue. I found that the error happens only when running TestS3Aggregator with TestCallbackCommand::test_s3_callbacks(see [this](https://bin.disroot.org/?cb7153aa45bed4df#GHiHmrADkGcMQ8Af2GSrY3G1dSQ1ukjD6GpUXtfdibga))

I tried to find out why this is happening, and it seems I am facing [this](https://github.com/localstack/localstack/issues/378) issue with localstack.

I am not familiar with localstack and its usage. But If I do the following, I am getting same error.
```
from localstack.services import infra
infra.start_infra(asynchronous=True, apis=["s3"])
infra.stop_infra()
infra.start_infra(asynchronous=True, apis=["s3"])
```
([output](https://bin.disroot.org/?2782e3585ffa7c6e#FW6QVNRPi52oBrDardSJDZYQEqZMqs3QM2qMSPqom72C))

**Comment by vringar** [comment]
Hey @jyothisjagan, thanks for breaking this down into a minimal testcase. Would you mind filing a seperate issue for this?
While I don't like our tests being broken, I expect the issue to be non trivial, so I'd suggest you ignore them afterwards and I'll try to figure the localstack issue out.

**Comment by jyothisjagan** [comment]
Sure @vringar. Will create a new issue for this. :)

**Comment by vringar** [comment]
Hey @jyothisjagan, did you have time/capacity to work on this issue or do you need any help from our side?
If you're still working on this, I'll assign you the issue otherwise I'd consider it up for grabs.

**Comment by jyothisjagan** [comment]
Hi @vringar , sorry for the late response. Can I keep this instance as it is?<https://github.com/mozilla/OpenWPM/blob/6a8bd88b87f3dea93f84ac07017e045859d989e3/automation/DeployBrowsers/selenium_firefox.py#L117-L129>
If we use with, we need to write `BaseService.__init__` multiple times.

**Comment by vringar** [comment]
@jyothisjagan Sorry for dropping the ball on this.
I think this can't be refactored since the filehandle needs to stay open
So yes, please keep this instance as is.
