### ISSUE TITLE
How does the content hash saved to levelDB evaluated?

### ISSUE THREAD

**Issue by nayanamana** [mozilla/OpenWPM#711]
When running OpenWPM over a set of URLs, I observed that it computes different content hashes (md5) for the same script (https://connect.facebook.net/en_US/fbevents.js) used in different first party URLs (e.g., http://jacquescartierchamplain.ca/?lang=en and http://jacquescartierchamplain.ca/circulation-travaux/reseau-en-direct/pont-honore-mercier/). Although the content hash (MD5) of the script URL (https://connect.facebook.net/en_US/fbevents.js) is different for the first party URLs, the source content of the script is identical. So, does this mean that the content hash is computed from the rendered content of the script (i.e., not from the script source)?

**Comment by birdsarah** [comment]
Interesting!

>  So, does this mean that the content hash is computed from the rendered content of the script
I'm not sure what this would mean. The content hash is generated from the response body. If you're seeing the same exact code in the leveldb database under different hashes, my first guess would be that there's something wrong with our hashing.

The hash is created of the content in the JS before being sent to python for deduplicated insertion into the database [here](https://github.com/mozilla/OpenWPM/blob/7c678d604ef47225d37ead073598b74617be917b/automation/DataAggregator/LocalAggregator.py#L141-L143)

On the JS side, there are two pieces:

* https://github.com/mozilla/OpenWPM/blob/master/automation/Extension/webext-instrumentation/src/lib/response-body-listener.ts#L14-L34
* https://github.com/mozilla/OpenWPM/blob/46647469bbe64ac42fe1b37db3da2b7e595476f2/automation/Extension/webext-instrumentation/src/lib/sha256.ts#L19-L23

I don't fully understand how this code works on quick glance, but the one thing I noticed: the sha256 code references https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest which in the "Converting a digest to a hex string" as an `await` on the `crypto.subtle.digest`, so maybe we're not finishing to wait for all the response data to stream in before making the hash.

Before we dig deeper into this theory, can you confirm that you're seeing the same content in your leveldb under different hashes. The best way of doing this would be getting the entries from leveldb and using python, or whatever, to hash those values. I think that's something like

```python
import hashlib
hashlib.sha256(b"Nobody inspects the spammish repetition").hexdigest()
```
source: https://docs.python.org/3/library/hashlib.html#hash-algorithms

**Comment by birdsarah** [comment]
@englehardt @motin - maybe seperately, looking at https://github.com/mozilla/OpenWPM/blob/v0.11.0/automation/Extension/webext-instrumentation/src/lib/sha256.ts and https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest, they have this pretty simple looking example:

```
const text = 'An obscure body in the S-K System, your majesty. The inhabitants refer to it as the planet Earth.';

async function digestMessage(message) {
  const msgUint8 = new TextEncoder().encode(message);                           // encode as (utf-8) Uint8Array
  const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);           // hash the message
  const hashArray = Array.from(new Uint8Array(hashBuffer));                     // convert buffer to byte array
  const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join(''); // convert bytes to hex string
  return hashHex;
}

const digestHex = await digestMessage(text);
console.log(digestHex);
```

Is there any reason we can't use that simpler code?

Lastly, our code has this comment at the top:

```
 * Note: Using SHA256 instead of the previously used MD5 due to
 * the following comment found at the documentation page linked above:
 *
 * Warning: Older insecure hash functions, like MD5, are not supported
 * by this method. Even a supported method, SHA-1, is considered weak,
 * has been broken and should be avoided for cryptographic applications.
```

We are not a cryptographic application, we just want a hash for de-duping. Perhaps md5 would be faster, which can't be a bad thing. Even if we want to keep sha256 can we remove this message as I think it's confusing?

**Comment by nayanamana** [comment]
I used the below code to extract the content from levelDB by providing the content_hash (as the key). For the example I mentioned, I am getting the same content for different content_hashes (validated using "diff"), where I was expecting different content in corresponding JavaScript source code. Again this is observed for the same script URL with different content_hashes.

-------------------------

#!/usr/bin/python3

import leveldb
import sys
import traceback
import pprint

idb_file_path = '/home/naya/Desktop/content.ldb_bak/'


db = leveldb.LevelDB(idb_file_path)
hash='0db5cab943f4d486fa896e9a5272fc82270e97268a4b8ba86b7a9f32eac14d4a'

content = db.Get(hash.encode('utf-8'))
print(content.decode())

**Comment by englehardt** [comment]
> @englehardt @motin - maybe seperately, looking at https://github.com/mozilla/OpenWPM/blob/v0.11.0/automation/Extension/webext-instrumentation/src/lib/sha256.ts and https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto/digest, they have this pretty simple looking example:
> 
> ```
> const text = 'An obscure body in the S-K System, your majesty. The inhabitants refer to it as the planet Earth.';
> 
> async function digestMessage(message) {
>   const msgUint8 = new TextEncoder().encode(message);                           // encode as (utf-8) Uint8Array
>   const hashBuffer = await crypto.subtle.digest('SHA-256', msgUint8);           // hash the message
>   const hashArray = Array.from(new Uint8Array(hashBuffer));                     // convert buffer to byte array
>   const hashHex = hashArray.map(b => b.toString(16).padStart(2, '0')).join(''); // convert bytes to hex string
>   return hashHex;
> }
> 
> const digestHex = await digestMessage(text);
> console.log(digestHex);
> ```
> 
> Is there any reason we can't use that simpler code?

I'll defer to @motin since he originally implemented this. I'd need to dig in myself.

> Lastly, our code has this comment at the top:
> 
> ```
>  * Note: Using SHA256 instead of the previously used MD5 due to
>  * the following comment found at the documentation page linked above:
>  *
>  * Warning: Older insecure hash functions, like MD5, are not supported
>  * by this method. Even a supported method, SHA-1, is considered weak,
>  * has been broken and should be avoided for cryptographic applications.
> ```
> 
> We are not a cryptographic application, we just want a hash for de-duping. Perhaps md5 would be faster, which can't be a bad thing. Even if we want to keep sha256 can we remove this message as I think it's confusing?

My understanding is that the built-in crypto library we're relying on no longer supports md5. We used to use md5 for this, but that relied on internal APIs that are no longer accessible post-WebExtensions.

**Comment by birdsarah** [comment]
> I am getting the same content for different content_hashes (validated using "diff")

The reason I was asking to confirm with python hashing is, just in case, diff is glossing over different whitespace which isn't meaningful for a text diff, but could result in a different hash.

**Comment by birdsarah** [comment]
> My understanding is that the built-in crypto library we're relying on no longer supports md5.

Missed that in the mdn page. You're right. I think we should remove this comment.

**Comment by nayanamana** [comment]
Using Python I computed the MD5 hash for content returned from both content_hashes and the hash values are the same (so I don't think this is a space/special character issue).

**Comment by birdsarah** [comment]
> Using Python I computed the MD5 hash for content returned from both content_hashes and the hash values are the same (so I don't think this is a space/special character issue).

Brilliant. Thanks. 

Now the gross part. This seems like it could be very hard to setup a test for.

@nayanamana can you now confirm the opposite. In the original report, I assume you were able filter the requests table and see the same script URL having different content hashes. Can you now look for the opposite: a script URL that has multiple requests to it, but has the same content hash.

**Comment by englehardt** [comment]
@nayanamana Separately, can I also ask you to share the contents of the two files retrieved from the leveldb database that are the same but have different hashes. It would be helpful if you could share the URLs from which that content has originally retrieved (if you have an example of URLs that return static content that would be helpful) and the site that loads those URLs. That would let me see if this is reproducible / debug the code on OpenWPM's side

**Comment by nayanamana** [comment]
With my limited data set, I did that verification to some extent. But I couldn't find having the same content (i.e., script source) for same script URL where there are multiple requests.

**Comment by birdsarah** [comment]
> With my limited data set, I did that verification to some extent. But I couldn't find having the same content (i.e., script source) for same script URL where there are multiple requests.

I don't understand. You have said you have a leveldb database with two copies of the same file but with different hashes. So that's one instance of multiple requests.

**Comment by nayanamana** [comment]
> > With my limited data set, I did that verification to some extent. But I couldn't find having the same content (i.e., script source) for same script URL where there are multiple requests.
> 
> I don't understand. You have said you have a leveldb database with two copies of the same file but with different hashes. So that's one instance of multiple requests.

Sorry. I mistyped my reply. Corrected the reply above. Not sure if I answered your question.

**Comment by nayanamana** [comment]
If you want to recreate here is an example:

I used below first party URLs to crawl.
https://ici.radio-canada.ca/conditions-utilisation/espace-numerique
https://ici.radio-canada.ca/info

Then selected the following content hash_values for script: https://static.chartbeat.com/js/chartbeat_video.js

c1 --> 'ba607af2c8d414ab6d4bac90c526d90a939cb0adf507b6ba063265347479159d'
c2 --> '0db5cab943f4d486fa896e9a5272fc82270e97268a4b8ba86b7a9f32eac14d4a'

Although these content hash values are different, the source content of those scripts are identical 

[c2.txt](https://github.com/mozilla/OpenWPM/files/4898042/c2.txt)
[c1.txt](https://github.com/mozilla/OpenWPM/files/4898045/c1.txt)

Please let me know if you need more malformation to recreate the problem

**Comment by birdsarah** [comment]
Running a crawl locally, to those two sites, I see chartbeat_video on both but in my responses table, the content hash is the same (5ae4aa074b868e28804c31a420423d8647ea6771fe61b2793095479260fed5e7) - I'm not sure whether it should be the same as yours.

Some questions:
* When you rerun your crawl for just these two sites do you get the same? i.e. is this error reproduceable for you?
* Are you running on v0.11 (just came out yesterday) version of openwpm.

**Comment by nayanamana** [comment]
> Running a crawl locally, to those two sites, I see chartbeat_video on both but in my responses table, the content hash is the same (5ae4aa074b868e28804c31a420423d8647ea6771fe61b2793095479260fed5e7) - I'm not sure whether it should be the same as yours.
> 
> Some questions:
> 
> * When you rerun your crawl for just these two sites do you get the same? i.e. is this error reproduceable for you? Yes and Yes. Below are the 2 content hashes for the same chartbeat_video script:
* 0db5cab943f4d486fa896e9a5272fc82270e97268a4b8ba86b7a9f32eac14d4a
* 3d1d8ff6a670771a57b34176bea3f233febf93f5decf11d45932646ee6c9235b
> * Are you running on v0.11 (just came out yesterday) version of openwpm. - I am using version 0.10.0
> 
> Here's my [demo.py](https://github.com/mozilla/OpenWPM/files/4898962/demo.py.txt).

**Comment by birdsarah** [comment]
If we could get another person to try my demo.py and report their results, this may help triangulate the problem.

**Comment by nayanamana** [comment]
> If we could get another person to try my demo.py and report their results, this may help triangulate the problem.

From my side, I am the only user using OpenWPM at the moment. Was there any updates that would have rectified this issue when going from 0.10.0 to 0.11.0 ?

**Comment by birdsarah** [comment]
No. There is nothing that has changed in at least a year that I would expect to have changed this. I'm doing a quick look to see if the problem exists on one of our large crawls.

**Comment by birdsarah** [comment]
I did a very quick analysis on the Feb 2020 crawl (@englehardt @vringar you know what I mean) - an Alexa top 100k crawl.

See my notebook here: https://gist.github.com/birdsarah/41dcb10751ecb52f7e4fbc14ae10076a

If researchers are relying on the content hash for analysis, then I would call this a bug. 

@nayanamana this is a great spot. Thanks. If you're interested, the reason I haven't even thought about this before is because I've only ever used the content hashes for lookup, rather than considering them a data point for making assertions about content that's loaded.
