### ISSUE TITLE
Instrument specific JavaScript function

### ISSUE THREAD

**Issue by turban1988** [mozilla/OpenWPM#717]
Hey, 
I want to log calls to the JavaScript function[ `window.postMessage()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage). OpenWPM implements the instrumentation of JavaScript based on objects and properties. My problem is that logging all access to the  `window` object is probably too noisy and I might still miss calls to that specific function. 
How can I instrument calls to a specific function?

Best,

**Comment by vringar** [comment]
I know it's possible, but I don't know exactly how
Pinging @birdsarah since she implemented this

**Comment by birdsarah** [comment]
It's documented here: https://github.com/mozilla/OpenWPM#instrumentation-and-data-access

    browser_params['js_instrument_settings'] = {"window": ["postMessage",]}

Should do it.

If you have tried that and it fails then please open an issue.

> OpenWPM implements the instrumentation of JavaScript based on objects and properties.

I believe the documentation contains a more accurate statement "Records all method calls (with arguments) and property accesses for configured APIs".

**Comment by turban1988** [comment]
Great, thanks!
