### ISSUE TITLE
JS instrumentation

### ISSUE THREAD

**Issue by turban1988** [mozilla/OpenWPM#720]
@birdsarah In response to #717:

When I add

`browser_params[i]['js_instrument_settings'] = {"window": ["postMessage"]}` 

to the demo, I get

```
Traceback (most recent call last):
  File "demo.py", line 45, in <module>
    manager = TaskManager.TaskManager(manager_params, browser_params)
  File "/home/openwpm/OpenWPM/automation/TaskManager.py", line 119, in __init__
    cleaned_js_settings = clean_js_instrumentation_settings(
  File "/home/openwpm/OpenWPM/automation/js_instrumentation.py", line 246, in clean_js_instrumentation_settings
    raise TypeError(
TypeError: js_instrumentation_settings must be a list.               Received {'window': ['postMessage']}


------------------
(program exited with code: 1)
Press return to continue

```
I get the same error when I use other examples from the documentation: https://github.com/mozilla/OpenWPM#instrumentation-and-data-access

**Comment by birdsarah** [comment]
Right. Apologies. The documentation does say "In summary, a list is passed with JS objects to be instrumented and details about how that object should be instrumented." But the example snippets in the doc should be updated to reflect that.

The correct invocation should be:

    browser_params[i]['js_instrument_settings'] = [{"window": ["postMessage"]}, ]

The good news is that the validation error worked nicely.

**Comment by birdsarah** [comment]
Assuming, my suggestion above works, I propose updating this issue to be a documentation one to improve the current docs section.

**Comment by turban1988** [comment]
> 
> ```
> browser_params[i]['js_instrument_settings'] = [{"window": ["postMessage"]}, ]
> ```

Worked just fine
