### ISSUE TITLE
Put expected values for tests into the test_*.py file they are used in

### ISSUE THREAD

**Issue by dreisman** [mozilla/OpenWPM#73]
It's confusing to have a separate file with the expected values, even if it saves some reuse - they should be defined at the top of the file where they are used to make reasoning about tests easier.

**Comment by boolean5** [comment]
It seems that `expected.py` and the expected values defined within it are no longer used by any tests.
If someone confirms this I can send a PR that removes this file.

**Comment by englehardt** [comment]
After a quick pass that seems to be right. Feel free to create a PR and we'll see if any tests fail. (cc\ @skim1102)

**Comment by boolean5** [comment]
Done. The tests are passing too.
