### ISSUE TITLE
TestS3Aggregator tests results in error while running with TestCallbackCommand::test_s3_callbacks test

### ISSUE THREAD

**Issue by jyothisjagan** [mozilla/OpenWPM#732]
I was setting up environment for this project on Debian GNU/Linux 10.5 after showing interest to work on #708 .

When I run tests using `py.test -vv`, I got errors([output](https://bin.disroot.org/?dfd33fa61f932088#BNmMidi9sJ1tmR85Q8nZFZDR7KUy2CBXbJLSfQZpXt2t)) for tests `test_s3_aggregator.py::TestS3Aggregator::test_basic_properties` and `test_s3_aggregator.py::TestS3Aggregator::test_commit_on_timeout`. I have tried setting PYTHONNOUSERSITE, but it did not solve the issue. But if I omit the test `test_callback.py::TestCallbackCommand::test_s3_callbacks`, the TestS3Aggregator tests are passing.

I tried to find out why this is happening, and it seems I am facing [this](https://github.com/localstack/localstack/issues/378) issue with localstack.

If I do the following, I am getting the same error that I got during test run([output](https://bin.disroot.org/?2782e3585ffa7c6e#FW6QVNRPi52oBrDardSJDZYQEqZMqs3QM2qMSPqom72C)).
```
from localstack.services import infra
infra.start_infra(asynchronous=True, apis=["s3"])
infra.stop_infra()
infra.start_infra(asynchronous=True, apis=["s3"])
```

**Comment by vringar** [comment]
This is due to `infra.stop_infra()` only sending a signal to the infra to shutdown and not waiting for the shutdown to actually happen.

**Comment by englehardt** [comment]
I'm going to close this as our workaround in #736 does fix the failing tests. We have a desire to move away from localstack (see: #652), so I don't see a reason to track / try to fix the underlying localstack issue.
