### ISSUE TITLE
Different types for `request_id` in parquet_schema.py

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#748]
https://github.com/mozilla/OpenWPM/blob/181920fb229b708ec6b4010b9f85dab66d9baff5/automation/DataAggregator/parquet_schema.py#L47
https://github.com/mozilla/OpenWPM/blob/181920fb229b708ec6b4010b9f85dab66d9baff5/automation/DataAggregator/parquet_schema.py#L194
The only place where we use int is in the callstacks instrument. But it also should be an int, because it's obviously a number.
Like 25 or smt.

**Comment by vringar** [comment]
If we decide to change this we also need to update the .ts schemas.

**Comment by vringar** [comment]
Resoltion: Update all `request_id` types to integer

**Comment by richardgreg** [comment]
Hi @vringar I would like to work on this.

**Comment by vringar** [comment]
Go right ahead!

**Comment by vringar** [comment]
@richardgreg If you need any support feel free to ask here or in the Matrix channel linked in the readme.md

**Comment by richardgreg** [comment]
Okay! Will do. I was having some problems running the test suite in conda virtual environment. I have resolved it. running `py.test -vv` test takes around 40 mins to complete on my system. Are there faster alternatives?

**Comment by vringar** [comment]
Unfortunately our test suite is just that slow :( The only way you could possibly work around that is by just pushing the changes and checking whether they pass on CI or not.
