### ISSUE TITLE
Reactivate process_watchdog now that it's fixed

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#749]
https://github.com/mozilla/OpenWPM/blob/181920fb229b708ec6b4010b9f85dab66d9baff5/automation/TaskManager.py#L69
change this to True?

**Comment by vringar** [comment]
And remove this guard
https://github.com/mozilla/OpenWPM/blob/1d01187cef8194578033602be7d565f8bee234e7/automation/TaskManager.py#L141-L145

**Comment by vringar** [comment]
Maybe we should wait with this until #778 is done.

**Comment by vringar** [comment]
We should also move process_watchdog to the manager_params.

**Comment by ankushduacodes** [comment]
@vringar May I take this one as well?

**Comment by vringar** [comment]
Go ahead :)

**Comment by ankushduacodes** [comment]
@vringar Do you want process watchdog to be active by default?

**Comment by vringar** [comment]
No, I think you got the default right.

This comment is outdated and should be removed.
