### ISSUE TITLE
Running install.sh gives ResolvePackageNotFound error in Ubuntu 18.04

### ISSUE THREAD

**Issue by Prajwal7842** [mozilla/OpenWPM#759]
I tried installing the OpenWPM repo on my OS : Ubuntu 18.04. When I run the file ./install.sh, the terminal gave me this error given in the picture
![2020-10-06-1602000034_screenshot_1920x1080](https://user-images.githubusercontent.com/34996624/95227042-40d87980-081b-11eb-8569-159c8968bffc.jpg)

Also I tried installing it in gitpod. I got the same error. 

My temporary solution : I removed the version from environment.yaml file. (geckodriver=0.27.0  -->  geckodriver). This worked and the repo was install successfully. 
I already tried to find any existing issue regarding this but could not find it(if it existed).

**Comment by vringar** [comment]
This is super weird given that we test against bionic (18.04) on Travis 
https://github.com/mozilla/OpenWPM/blob/a811af1c9c1f8efa4b9d2a008c6cbb3e5be6d1e8/.travis.yml#L2
but I have had the same problem before under OpenSuSe (see #742)
Would you mind creating a branch where you run `repin.sh` in the `scripts` folder to update all of our dependencies?
If the test pass on there, I'll merge it and nobody should have this problem anymore.

**Comment by Prajwal7842** [comment]
okay, I can create a new branch and run repin.sh file. I just wanted to know is there any guidelines that are followed like some naming conventions that should be used to name a branch ?

**Comment by vringar** [comment]
Closing this as #760 fixed the problem.
