### ISSUE TITLE
Convert BrowserManager's "check_queue" into the Status object

### ISSUE THREAD

**Issue by Metropass** [mozilla/OpenWPM#761]
As I'm working on #619, I've noticed that `result` is also parsed as a Tuple. Since we're transitioning into using a `Status` object, I would assume we need to change this block of code as well.

https://github.com/mozilla/OpenWPM/blob/c2a700448f31882bf75530eca98f536321b622e8/automation/BrowserManager.py#L127-L137

**Comment by vringar** [comment]
Yes, this would need to be changes as well. Thanks for catching that.
Is there a reason to track this in a separate issue? I'd expect your PR for #619 to fix this as well.

**Comment by Metropass** [comment]
Wow. You're right, I hadn't thought of that. I'll close this issue, and reflect the changes onto #619.
