### ISSUE TITLE
Rename things to follow PEP-8

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#779]
We want to follow [PEP8](https://www.python.org/dev/peps/pep-0008/#naming-conventions)  
This means modules should use snake_case which they currently don't.

**Comment by FukurouMakoto** [comment]
I would like to handle this if possible. 
Just to make sure, the entire project would need to be edited to follow PEP8 correct?

**Comment by vringar** [comment]
Yes. However I mostly meant this for global symbols, so not local variables but anything that can be imported.
In particular these are module and class names as well as free functions.

**Comment by FukurouMakoto** [comment]
Okay just to make sure:

- module names
- class names
- free functions

local variables can be ignored. 

That sound about right?

**Comment by FukurouMakoto** [comment]
Also just to make sure are there any tests that I should run specifically to ensure that I haven't completely broken the system by renaming the modules?

**Comment by vringar** [comment]
The fastest way to do a sanity check is to run `python demo.py` and see if any exceptions pop up.

**Comment by vringar** [comment]
Otherwise just create a PR and see if the CI starts complaining

**Comment by vringar** [comment]
This was almost completely adressed by #806 so I'm closing it for now
