### ISSUE TITLE
Expand profile loading, saving, and recovery tests

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#789]
We have relatively limited profile [test coverage](https://github.com/mozilla/OpenWPM/blob/master/test/test_profile.py). Once the tests are re-enabled (#383), we should define how we expect the `seed_tar` and `profile_tar` profiles to be handled for both stateful and stateless crawls and ensure our tests cover all conditions.

**Comment by boolean5** [comment]
We should also update and reenable [`test_profile_saved_when_launch_crashes`](https://github.com/mozilla/OpenWPM/blob/ab01a2f6bdadcf75fe8c2878bc8d6610f5ed2a7a/test/test_profile.py#L59L80). This test uses the proxy to make the launch fail. Because the proxy is no longer supported, we need to find a different way to make the launch crash.

**Comment by boolean5** [comment]
This is a list of things to test that I can think of. @vringar, @englehardt feel free to add more.

1. Test that for stateless crawls the profile specified by `seed_tar` is reloaded after each command sequence.
2. Test that the correct profile is loaded during crash recovery (a. the profile specified by `seed_tar` when running a stateless crawl, b. the profile specified by `recovery_tar`(i.e., the profile from the most recent page visit pre-crash) when running a stateful crawl)
3. Test dumping the profile as part of a command sequence (`DumpProfileCommand`)

**Comment by vringar** [comment]
This condition is complicated and maybe worth testing or removing. https://github.com/mozilla/OpenWPM/blob/master/openwpm/browser_manager.py#L597

**Comment by vringar** [comment]
This requires a test matrix.
1. operational mode: Stateful, Stateless
2. Seed_profile: Exists, Doesn't
3. Crash types: normal operation, crash during page visit, crash during launch, timeout during page visit

**Comment by boolean5** [comment]
We should also test that [`load_profile`](https://github.com/mozilla/OpenWPM/blob/e20fc6a29e191e9bacc5922ff494a05a922c8587/openwpm/commands/profile_commands.py#L127):
 * leaves the tar file unmodified
 * can handle both compressed and uncompressed tar files
