### ISSUE TITLE
Unnecessary List Unpacking

### ISSUE THREAD

**Issue by ankushduacodes** [mozilla/OpenWPM#800]
In the code snippet: https://github.com/mozilla/OpenWPM/blob/512018f852a2b554b5b08a72936f835adf6b7110/test/test_webdriver_utils.py#L29-L33 
List unpacking is very unnecessary here, I am not sure why `_` is used here, and what the use of it is.

Explanation:
Now, when I tried to debug what the `SELECT` query is returning is a list of two tuples, Now, to my understanding  one is the tuples is for `<class 'openwpm.Commands.Types.InitializeCommand'>` for initialization command and the second one is for `<class 'openwpm.Commands.Types.GetCommand'>`. 
To my understanding, for this test, we are only interested in `command_status` and `error` for `<class 'openwpm.Commands.Types.GetCommand'>`.

Potential fixes:
1. Remove the underscore and assign the result of SELECT command into get_command and in the assertion we can use appropriate indices. Something like:
`assert get_command[1][0] == "neterror"`
`assert get_command[1][1] == "dnsNotFound"`
2. Remove the underscore and assign indicised result to `get_command`. Something like:
```python
get_command = db_utils.query_db(
            manager_params["db"],
            "SELECT command_status, error " "FROM crawl_history ",
            as_tuple=True,
        )[1]
```

**Comment by vringar** [comment]
I'd prefer option 2 over 1. Thanks for pointing this out.
Please also remove the double quotes in the middle of the query string.

**Comment by ankushduacodes** [comment]
@vringar We could also potentially use `WHERE` clause here as well as pointed out by you [here](https://github.com/mozilla/OpenWPM/pull/799#discussion_r525895829)

**Comment by LordReigns** [comment]
I would like to work on this issue. @ankushduacodes .

**Comment by ankushduacodes** [comment]
@LordReigns Have to set up the development environment? If not please do so using [this guide](https://github.com/mozilla/OpenWPM/blob/master/README.md#installation), You should also set up pre-commit configurations using [this guide](https://github.com/mozilla/OpenWPM/blob/master/CONTRIBUTING.md#setting-up-a-dev-enviroment)

Then run demo.py and take a look at the SQLite database file that will be created on your desktop. Take a look at. crawl_history table in the database (use any database workbench that supports SQLite database, I personally use [`DB Browser for SQLite`](https://sqlitebrowser.org/)) and take a look at the columns that we are fetching with `SELECT` statement here: https://github.com/mozilla/OpenWPM/blob/512018f852a2b554b5b08a72936f835adf6b7110/test/test_webdriver_utils.py#L29-L33
Now take a look at the issue statement, it outlines the explanation and some potential fixes.

Also take a look and see how we are using `SELECT` with `WHICH` clause to fetch the required columns here:
https://github.com/ankushduacodes/OpenWPM/blob/0d3bd4bf7aacfdc0c4cabb7df877416ee50f2b32/test/test_timer.py#L20-L24
Now the solution to this should look similar to the above mentioned `SELECT` [statement](https://github.com/ankushduacodes/OpenWPM/blob/0d3bd4bf7aacfdc0c4cabb7df877416ee50f2b32/test/test_timer.py#L20-L24)(changing some columns).

I will be happy to add 3rd potential fix if you would like me to, But if you want to piece the information together yourself, I think it will be great learning opportunity

Don't hesitate to ping me or @vringar if you need any type of help, We would be happy to help

(PRO tip: if you are using PyCharm IDE, Individual tests as easy as running a simple python script)

**Comment by ankushduacodes** [comment]
@vringar just to make sure I am not forgetting anything [here](https://github.com/mozilla/OpenWPM/issues/800#issuecomment-729765046), Would you like to add something?

And just making sure, You do want the `WHERE` clause to be used here as well right?

**Comment by vringar** [comment]
> @vringar just to make sure I am not forgetting anything [here](https://github.com/mozilla/OpenWPM/issues/800#issuecomment-729765046), Would you like to add something?

No this looks good to me :)
> And just making sure, You do want the `WHERE` clause to be used here as well right?

Yes
> And I was using PyCharm's tools to run individual tests, Is there a way to run individual tests via the terminal?

You can use `python -m pytest -vv -s -k test_parse_neterror_integration` from the test folder to run the test from the command line.

**Comment by LordReigns** [comment]
Thank you. I will try my best to figure out how to combine all these information. I have setup the environment. As recommended I will use pycharm since it would make things easier.  I will let you know about any difficulties.

Thank you for your support @vringar @ankushduacodes ❤

**Comment by LordReigns** [comment]
Is this is expected fix @ankushduacodes  ,

get_command = db_utils.query_db( 
     manager_params["db"], 
     "SELECT command_status, error FROM crawl_history WHERE command = \"<class 'OpenWPM.openwpm.Commands.Types.GetCommand'>\" ", 
     as_tuple=True, 
 )

**Comment by ankushduacodes** [comment]
@LordReigns Yes, you are definitely on the right path, try to print debug and see what is being returned into `get_command` variable when you run the test. And then use indices appropriately

You also will have to escape the double quotes here:
`"SELECT command_status, error FROM crawl_history WHERE command = \"<class 'OpenWPM.openwpm.Commands.Types.GetCommand'>\" "`

This is because in the database information for this particular `WHERE` clause is stored as string and you will have to keep in mind that when performing an operation on database this python string will be converted into sql query,  which means in the end there will be no double quotes if you don't escape it.

**Comment by LordReigns** [comment]
This how the final code looks like,
```
get_command = db_utils.query_db(
            manager_params["db"],
            "SELECT command_status, error FROM crawl_history WHERE command = \"<class 'OpenWPM.openwpm.Commands.Types.GetCommand'>\"",
            as_tuple=True,
        )[0]

        assert get_command[0] == "neterror"
        assert get_command[1] == "dnsNotFound"

```
It passed both the test cases. Hope this is okay.
@ankushduacodes

**Comment by ankushduacodes** [comment]
@LordReigns Looks great to me! I would suggest 1 more step before making pull request to run pre-commit install and then pre-commit run --all-files to make sure matches the OpenWPM code organisation convention

**Comment by LordReigns** [comment]
I ran the pre-commit commands and opened a pull request. @ankushduacodes
