### ISSUE TITLE
Make the TaskManager a ContextManager

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#812]
It's currently super easy to forget to close the TaskManager. Making it a ContextManager would allow users to write
```python
with TaskManager(...) as tm:
   tm.execute_command_sequence(cs)

print("TaskManager closed")
```
and the call to close would happen automatically at the end of the scope.

Implementing a ContextManager is super easy, as there are only two methods to implement. https://docs.python.org/3.8/library/stdtypes.html#typecontextmanager

In `task_manager.py`:

```python
def __enter__(self):
    return self

def __close__(self):
    self.close()
```

**Comment by jhabarsingh** [comment]
Could you please assign this issue to me.

**Comment by vringar** [comment]
Thank you for doing this :)

**Comment by jhabarsingh** [comment]
I have to add __enter__ and __exit__ methods in Taskmanager. right ?

**Comment by vringar** [comment]
Yes.
