### ISSUE TITLE
Remove mentions of default_manager_params.json from README.md

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#819]
@Ankushduacodes when merging #807  we forgot to remove to `default_manager_params.json` and `default_browser_params.json` even though they are no longer used anywhere.

We should also remove all references to those two files e.g. in the "Quick Start" section in the README.md. I haven't searched the rest of the codebase, but there may be some more references to it.

**Comment by ankushduacodes** [comment]
For sure, I will fix them. Should i also delete the json files?

**Comment by ankushduacodes** [comment]
@vringar Along with deleting references to default JSON files, I have also updated some documentation on how to instantiate TaskManager and some little things here and there, Let me know how they are looking.
