### ISSUE TITLE
Set up Sphinx

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#820]
I started setting up Sphinx some time back but haven't had the time to get back to it.
Anybody who want to work on this should have a look at https://github.com/mozilla/OpenWPM/commit/2e17baa15e59e5d49549f1d59f3c1ad868995bd9

**Comment by jhabarsingh** [comment]
okay I would love to work on it.

**Comment by vringar** [comment]
Go right ahead!

**Comment by vringar** [comment]
If there is anything you're getting stuck on or want an explanation for please feel to reach out here or on [matrix](https://matrix.to/#/#OpenWPM:mozilla.org?via=mozilla.org)

**Comment by jhabarsingh** [comment]
Sir, I am really sorry but my exams were going on that's why I couldn't
start this but tomorrow my exams would get over so I would be glad to work
on this issue.

**Comment by vringar** [comment]
Please don't feel rushed :) I just wanted to reach out and make sure you are okay.
As you can see the commit is 8 months old and we haven't gotten around to it since. So there is no time pressure of any kind.

**Comment by jhabarsingh** [comment]
Awesome, thank you so much!

**Comment by jhabarsingh** [comment]
Sir I forked the project and looked at 2e17baa

**Comment by jhabarsingh** [comment]
could you please let me know How to commence.

**Comment by vringar** [comment]
I'd suggest pulling the latest master branch, from there creating a new branch and then merging 2e17baa into that new branch.
Next you would add `sphinx` to the `requirements-unpinned-dev.yaml` and then follow the steps described [here](https://github.com/mozilla/OpenWPM/blob/master/CONTRIBUTING.md#managing-requirements).
After that you should be able to run `./docs/generate_docs.sh` and see a bunch of HTML files.

Once you have done that please report back and we'll see how to go from there :)

**Comment by jhabarsingh** [comment]
Sir, I am getting conflicts while merging.
```
Auto-merging openwpm/utilities/cookie.py
CONFLICT (content): Merge conflict in openwpm/utilities/cookie.py
Automatic merge failed; fix conflicts and then commit the result.
```

**Comment by jhabarsingh** [comment]
I resolved the conflict + added the `sphinx` int the `environments-unpinned-dev.yaml`
But when I'm running the  `repin.sh` file I am getting this error.
```
./repin.sh: line 90:  3199 Segmentation fault      (core dumped) "$CONDA_EXE" $_CE_M $_CE_CONDA "$cmd" "$@"
```

**Comment by jhabarsingh** [comment]
Sir I have successfully generated the doc files
```
Running Sphinx v3.3.1
making output directory... done
WARNING: html_static_path entry '_static' does not exist
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 1 source files that are out of date
updating environment: [new config] 1 added, 0 changed, 0 removed
reading sources... [100%] index                                                                                                                                                                                 
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] index                                                                                                                                                                                  
generating indices... genindex done
writing additional pages... search done
copying static files... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 1 warning.


```

**Comment by jhabarsingh** [comment]
Sir,
  One more thing I wanted to tell you that when I tried to run `./docs/generate_docs.sh`, It gave me the Error shown below.

### ERROR
```
Running Sphinx v3.3.1

Extension error:
Could not import extension nbsphinx (exception: No module named 'nbsphinx')
```
### Fixed
>When I installed **nbsphinx** it worked for me so is there any need of adding it in **dev-dependencies** ?

**Comment by vringar** [comment]
Yes, please add it to the dev-dependencies!

**Comment by jhabarsingh** [comment]
Ok sir

**Comment by jhabarsingh** [comment]
Sir, what should I do next ?

**Comment by jhabarsingh** [comment]
Sir, I've added `nbspinx` in the `add it to the dev-dependencies!`.

**Comment by vringar** [comment]
Could you please create a Pull Request with the changes you made.

**Comment by vringar** [comment]
Please also add a [`.readthedocs.yml`](https//docs.readthedocs.io/en/stable/config-file/v2.html#conda) to the PR.

**Comment by jhabarsingh** [comment]
Sir, where would I get `.readthedocs.yml`.

**Comment by jhabarsingh** [comment]
Sir, the link you had attached to the `.readthedocs.yml`. It's redirecting me to a `404 NOT FOUND` page

**Comment by ankushduacodes** [comment]
> Please also add a [`.readthedocs.yml`](https://docs.readthedocs.io/en/stable/config-file/v2.html#conda) to the PR.

@jhabarsingh try this 👆, I think vringer made a little mistake while constructing the url.

**Comment by jhabarsingh** [comment]
Sir, I have added `.readthedocs.yaml` file

**Comment by vringar** [comment]
> > Please also add a [`.readthedocs.yml`](https://docs.readthedocs.io/en/stable/config-file/v2.html#conda) to the PR.
> @jhabarsingh try this point_up_2, I think vringer made a little mistake while constructing the url :)
Thanks @ankushduacodes for fixing my link.

**Comment by vringar** [comment]
@jhabarsingh Thank you for adding the file. I have left some comments on the PR.
Also please just call me @vringar. There is no need for something as formal as sir. :)
