### ISSUE TITLE
Add CI job for Docker builds

### ISSUE THREAD

**Issue by boolean5** [mozilla/OpenWPM#848]
PR https://github.com/mozilla/OpenWPM/pull/838 moved our CI from Travis to Github Actions but did not include a job to build the Docker image and deploy it to DockerHub. We should add one that does this.

**Comment by vringar** [comment]
TODO me: Reach out to @motin to ask for credentials for the dockerhub account so we can put those into GitHub Secrets and publish every merge onto master on Dockerhub.
(This would change from the previous behavior of publishing every commit made to the repo)
