### ISSUE TITLE
Clarify failure_limit behavior

### ISSUE THREAD

**Issue by boolean5** [mozilla/OpenWPM#851]
[`test_profile.py::TestProfile::test_crash`](https://github.com/mozilla/OpenWPM/blob/master/test/test_profile.py#L33L40) (which is currently disabled because it depends on stateful crawling support) is based on the assumption that successive command failures will trigger a `CommandExecutionError`, even if the commands belong to different command sequences.

However, after the [`InitializeCommand` and `FinalizeCommand`](https://github.com/mozilla/OpenWPM/blob/master/openwpm/command_sequence.py#L193L194) were introduced, the [`failure_limit`](https://github.com/mozilla/OpenWPM/blob/master/openwpm/config.py#L110) Task Manager config option is applied per command sequence.

We should do one of the following:

a. Fix this by changing [Task Manager code](https://github.com/mozilla/OpenWPM/blob/master/openwpm/task_manager.py#L568L570) so that it does not reset `failurecount` to `0` when the command is an `InitializeCommand` or a `FinalizeCommand`.

b. Update the documentation to clarify that `failure_limit` is applied per command sequence if this is the desired behavior

Another related issue is what should happen when `failure_limit` is set to `0`. Right now [`0` is treated the same way as `None`](https://github.com/mozilla/OpenWPM/blob/master/openwpm/task_manager.py#L130L133) and changed to the default value of  2 x the number of browsers plus 10.

I think `0` is a valid value for `failure_limit` (meaning that a `CommandExecutionError` should be raised when the first failure is encountered) and should not be reset to the default.

**Comment by englehardt** [comment]
* Move failure limit default into the manager params file, not in TaskManager.
* Clear on the first successful command sequence.

**Comment by boolean5** [comment]
After giving this some thought, it seems that it's more practical to keep setting the default value of `failure_limit` in the `TaskManager`.


My first thought was to make `num_browsers` a property and in its setter method also update `failure_limit` with the correct default value.

This would work in a scenario like this:

```
manager_params = ManagerParams()
# failure_count is 12 (2 * default num_browsers + 10)
manager_params.num_browsers = 2
# failure_count is correctly updated to the new default, which is 14
```

but would not work in a scenario like the following, as the value we give to `failure_count` will be overwritten:

```
manager_params = ManagerParams()
# failure_count is 12 (2 * default num_browsers + 10)
manager_params.failure_count = 5
# we set failure_count to 5
manager_params.num_browsers = 2
# our chosen value gets overwritten by the new default (14)
```

Handling all cases correctly seems rather complicated. It works well to only set the default value for `failure_limit` when we know that `num_browsers` and `failure_limit` are not going to change anymore (i.e., in the `TaskManager`).


@vringar, @englehardt, what do you think?

**Comment by vringar** [comment]
What about using a [property](https://docs.python.org/3/library/functions.html#property)
This way we could calculate the value dynamically if the user hasn't set a default or we return the value set by the user.

**Comment by boolean5** [comment]
Yes, you're right, that works fine. Thanks!
