### ISSUE TITLE
Compare Github Actions to CircleCI

### ISSUE THREAD

**Issue by boolean5** [mozilla/OpenWPM#855]
The purpose of this issue is to keep track of pros and cons of the two CI platforms, in order to help decide which is more suitable for this repo.

**Comment by boolean5** [comment]
Github Actions has a rather strict [log retention policy](https://docs.github.com/en/github/administering-a-repository/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-repository) for public repos - it only stores the logs for 90 days. In my experience, it's quite common for open issues to reference CI logs older than 3 months, so this is an important restriction. It can be mitigated if we are able to retrigger old builds however.

**Comment by vringar** [comment]
As we plan to move into an independent org and won't have a CircleCI subscription available to us anymore, I think we should just stay on GH Actions.
