### ISSUE TITLE
[Discussion]Rotating outgoing IPv6 addresses

### ISSUE THREAD

**Issue by hammas9** [mozilla/OpenWPM#856]
Hi all,
I have a server which is allotted a certain block of IPv6 addresses. I have configured some of the addresses from that pool to my outgoing interface. What is the preferred way of binding my outgoing IP address of choice when a request is made by OpenWPM.

Thanks

**Comment by vringar** [comment]
I don't know the answer to your question but I don't think that the answer to that question is OpenWPM specific. Maybe searching for "Force Firefox to use certain network interface" will yield something useful

**Comment by vringar** [comment]
The other idea that comes to mind would be running OpenWPM in a container and then exploring the networking options of Docker.

**Comment by vringar** [comment]
@hammas9 did you get anywhere with this and do you want to share your findings or should I close this issue?

**Comment by hammas9** [comment]
I did not instrument the webdriver in OpenWPM but I created separate namespaces and allotted different subnets to each of them. So when I ran OpenWPM from within each of these network namespaces I was able to send outgoing requests using different addresses allotted to different namespaces.

**Comment by vringar** [comment]
Thank you for the follow-up
