### ISSUE TITLE
Add `"info": "npm-scripts-info"` under `scripts`

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#870]
We should probably add `"info": "npm-scripts-info"` under `scripts` as described [here](https://www.npmjs.com/package/npm-scripts-info) so that the descriptions under `scripts-info` can be displayed. But it's probably best if I open another PR for that as it's out of the scope of this one.

_Originally posted by @boolean5 in https://github.com/mozilla/OpenWPM/pull/865#discussion_r595074298_

**Comment by Ayushsunny** [comment]
is this still open sir @vringar ?

**Comment by vringar** [comment]
Hey @Ayushsunny,
Yes, this issue is still open. Do you want to work on it?

**Comment by Ayushsunny** [comment]
> Hey @Ayushsunny,
> Yes, this issue is still open. Do you want to work on it?

Hello @vringar can you guide me on this? Yes I want to work on this issue

**Comment by vringar** [comment]
Sure :) 
How familiar are you with Javascript and npm?

**Comment by Ayushsunny** [comment]
> Sure :)
> How familiar are you with Javascript and npm?

Okay I'm familiar with Javascript but "npm" I am still looking for a nice tutorial

**Comment by vringar** [comment]
Okay, so for this change you only need a rough understanding of npm.
npm is a package manager for Node.js which is a program you can use to run Javascript outside of the browser.
We use node to run certain checks and build the WebExtension that powers the data collection in OpenWPM.

The central entry point for node and npm is the `package.json` file. There you define among other thingds your projects metadata, dependencies and  scripts.

Scripts are tasks you want to be able to easily execute as part of your project.
As you can see in our top-level `package.json` we define a bunch of tasks 
https://github.com/mozilla/OpenWPM/blob/cc10baebee4a0f3fbec38eeac17586448c903e60/package.json#L5-L10
And we also document what each task is supposed to do
https://github.com/mozilla/OpenWPM/blob/cc10baebee4a0f3fbec38eeac17586448c903e60/package.json#L11-L16

However right now to see the description of each task we need to look at the `package.json` what we want to be able to do instead is to run `npm run info` and see all available commands.

For this you need to add `"info": "npm-scripts-info"` to the `scripts` object in `package.json` and add `npm-scripts-info` to our dependencies.

**Comment by vringar** [comment]
Please feel free to ask any questions that you have

**Comment by Ayushsunny** [comment]
> For this you need to add `"info": "npm-scripts-info"` to the `scripts` object in `package.json`and add `npm-scripts-info` to our dependencies.

@vringar Sir in this line I didn't get that and **add `npm-scripts-info` to our dependencies.**

**Comment by vringar** [comment]
For that you'll need to run `npm install --save-dev npm-scripts-info` after you have set up the environment.

**Comment by Ayushsunny** [comment]
Hello @vringar I have made the changes and also run this command `npm install --save-dev npm-scripts-info` and suddenly a new `package-lock.json` generated with changes.
Now what to do sir?

**Comment by vringar** [comment]
Please commit both the changes to `package.json` and `package-lock.json` and create a Pull Request with your changes.

**Comment by Ayushsunny** [comment]
Hello @vringar I have made a PR.
could you review please

**Comment by vringar** [comment]
Thank you for your PR. I'll just wait for the tests to pass and then merge it.

**Comment by Ayushsunny** [comment]
> Thank you for your PR. I'll just wait for the tests to pass and then merge it.

np Sir, I wanna work more under you sir.
as a new contributor you helped me in a nice way.
Thank you so much

**Comment by vringar** [comment]
:) I'm always happy to help new contributors!
Do you want to work on #678 next?

**Comment by Ayushsunny** [comment]
> :) I'm always happy to help new contributors!
> Do you want to work on #678 next?

yes sir, Sure
