### ISSUE TITLE
Simulating keys while crawling & user-agent

### ISSUE THREAD

**Issue by pickizme** [mozilla/OpenWPM#880]
Hi,

I wonder if it's possible to send some keys (like DELETE or _ENTER) while crawling. If yes, is there any instruction for that? I could not see anything related to that point.

Edit: I didn't want to create a new issue for that, I also wonder if it's possible to change user-agent?

Thanks!

**Comment by vringar** [comment]
Hey,

For key events or mouse movement please use a [custom command](https://github.com/mozilla/OpenWPM/blob/master/custom_command.py). You can then use the Firefox driver passed to you in the `execute` method to create an [ActionChain](https://www.selenium.dev/selenium/docs/api/py/webdriver/selenium.webdriver.common.action_chains.html#module-selenium.webdriver.common.action_chains) to press all the buttons you want.

As for setting a user agent, after some quick googling I found `general.useragent.override` as the pref that overrides it.
You can set prefs on the browser you're creating by setting the [`prefs` field in the `BrowserConfig`](https://github.com/mozilla/OpenWPM/blob/8030c2c470015350f510af4e42f1389e1ffe1c1c/openwpm/config.py#L97)

**Comment by pickizme** [comment]
Thanks @vringar it just works great :)

**Comment by pickizme** [comment]
@vringar could you also please tell me, how can I change the resolution? I found some parameters in `deploy_firefox.py ` but I didn't find a way to pass a custom resolution.

**Comment by vringar** [comment]
For now this is the only way. But I'd be willing to help you implement this feature if you want to.
Please file a new issue for it, so we can track it.

**Comment by pickizme** [comment]
@vringar I just found a way. I created a custom command and execute it before crawling start. So something like that (maybe it helps somebody):

```

class ChangeRes(BaseCommand):
    """This command logs how many links it found on any given page"""

    def __init__(self) -> None:
        self.logger = logging.getLogger("openwpm")
 
    def __repr__(self) -> str:
        return "ChangeRes"
 
    def execute(
        self,
        webdriver: Firefox,
        browser_params: BrowserParams,
        manager_params: ManagerParams,
        extension_socket: ClientSocket,
    ) -> None:   
        webdriver.set_window_size(400,400)
```

Thanks again!
