### ISSUE TITLE
Connection error NS_ERROR_UNEXPECTED

### ISSUE THREAD

**Issue by shashigharti** [mozilla/OpenWPM#906]
I am trying to run web extension and connect it to the remote server to receive the data. But once the browser starts it can not establish connection to the remote socket server. Code throws this error:

`Exception { name: "NS_ERROR_UNEXPECTED", message: "Component returned failure code: 0x8000ffff (NS_ERROR_UNEXPECTED) [nsIBinaryOutputStream.writeByteArray]", result: 2147549183, filename: "file:///home/shashi/python/OpenWPM/openwpm/Extension/firefox/src/privileged/sockets/api.js", lineNumber: 154, columnNumber: 0, data: null, stack: "sendData@file:///home/shashi/python/OpenWPM/openwpm/Extension/firefox/src/privileged/sockets/api.js:154:34\nrecvAPICall/result</<@resource://gre/modules/ExtensionParent.jsm:956:68\nwithPendingBrowser@resource://gre/modules/ExtensionParent.jsm:489:26\nrecvAPICall/result<@resource://gre/modules/ExtensionParent.jsm:956:24\ncallAndLog@resource://gre/modules/ExtensionParent.jsm:918:14\nrecvAPICall@resource://gre/modules/ExtensionParent.jsm:955:25\n", location: XPCWrappedNative_NoHelper }`

![screenshot-nimbus-capture-2021 04 28-19_42_49](https://user-images.githubusercontent.com/5582809/116421188-56b49700-a85e-11eb-83e1-ee759afb3eb5.png)

And while debugging I found that the issue is in create transport layer code which is as follows(**api.js**, **line no**: 129):

`var transport = socketService.createTransport([], host, port, null);`

However, the the official documentation has this explanation of the function:
```
createTransport(in Array<ACString> aSocketTypes,
                                      in AUTF8String aHost,
                                      in long aPort,
                                      in nsIProxyInfo aProxyInfo,
                                      in nsIDNSRecord dnsRecord);
```
_Reference(https://searchfox.org/mozilla-central/source/netwerk/base/nsISocketTransportService.idl#58)_

So changing the function call worked for me.
`var transport = socketService.createTransport([], host, port, null, null);`

**Comment by vringar** [comment]
Oh interesting, this might explain @bkrumnow's comment that he wasn't seeing any logging from the extension in the OpenWPM logs.
Thanks for digging into this and reporting the issue!
