### ISSUE TITLE
Consider replacing GCSFS with google.cloud.storage for unstructured data

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#914]
Currently the writing of unstructured data for whatever reason keeps throwing the same error:
```
gcsfs.utils.HttpError: Invalid request. The number of bytes uploaded is required to be equal or greater than 262144, except for the final request (it's recommended to be the exact multiple of 262144). The received request contained 559 bytes, which does not meet this requirement., 400 
```
(This is on d09e213)

When using google.cloud.storage we could specify the compression and everything else we want and hopefully eliminate this error.

**Comment by boolean5** [comment]
In two issues mentioning this error the users were able to resolve it by removing a configuration file: see [[1]](https://github.com/googleapis/gcs-resumable-upload/issues/17) and [[2]](https://github.com/googleapis/google-cloud-node/issues/1044). I doubt this will be useful in our setup but I'm leaving them here in case they give you an idea.

**Comment by vringar** [comment]
Steps to still try:
v0.14.0 as it was
v0.14.0 with deps updated
