### ISSUE TITLE
Link to RTD documentation from README

### ISSUE THREAD

**Issue by boolean5** [mozilla/OpenWPM#915]
In order to make our new documentation on readthedocs discoverable, we should add its link (https://openwpm.readthedocs.io) to the `README` and perhaps also embed a docs badge, by adding the following:
```
[![Documentation Status](https://readthedocs.org/projects/openwpm/badge/?version=latest)](https://openwpm.readthedocs.io/en/latest/?badge=latest)
```
Additionally, we could add the `openwpm.readthedocs.io` link to the About section of the repository.

**Comment by vringar** [comment]
@Ayushsunny do you want to do this next?
