### ISSUE TITLE
Undefined custom_params error

### ISSUE THREAD

**Issue by shashigharti** [mozilla/OpenWPM#925]
When I try to run web extension using
`npm run watch`

I get this error
`can't access property "pre_instrumentation_code", config.custom_params is undefined` in index.js file.

![screenshot-nimbus-capture-2021 05 16-20_04_47](https://user-images.githubusercontent.com/5582809/118400819-feb1c900-b682-11eb-9530-b8fc4acd0024.png)

**Comment by vringar** [comment]
Thanks for bringing this issue to our attention!
