### ISSUE TITLE
Move from tslint to eslint

### ISSUE THREAD

**Issue by vringar** [mozilla/OpenWPM#928]
TSLint has been deprecated for a year at this point and we should move to ESLint as the supported alternative. https://github.com/palantir/tslint/issues/4534

They even provide [a tool](https://github.com/typescript-eslint/tslint-to-eslint-config)  that should automate this migration.

@Ayushsunny do you want to try and do this?

**Comment by Ayushsunny** [comment]
@vringar Yes Sir, Sure.
So I have to follow [these steps](https://github.com/typescript-eslint/tslint-to-eslint-config/blob/main/README.md) in our repo for the migration right?

**Comment by vringar** [comment]
Yes, that is what I'd expect you to do.
Please file a PR early, so that I can look at the changes you've done.

**Comment by Ayushsunny** [comment]
@vringar, Sir I'm getting these errors while configuring -


![Screenshot from 2021-05-19 10-16-12](https://user-images.githubusercontent.com/73520373/118757746-502ca480-b88b-11eb-929e-5db6cfaf08a1.png)

**Comment by vringar** [comment]
You ran the command in the wrong directory.
Our typescript code is under `openwpm/Extension/webext-instrumentation`.
Please also make sure to have the conda openwpm environment activated.
