### ISSUE TITLE
Distinguish between timeout and exception while crawling

### ISSUE THREAD

**Issue by nrllh** [mozilla/OpenWPM#932]
I'm trying to find a way to distinguish between timeout and exception. `success` parameter by callback is also then false, if a visiting page takes more than set timeout even if the crawling was successfully. So in my case, `success` parameter should be `true`, if there was no error and additionally I should know if it's timed out or not.

Any thoughts how can I do that? 

I'm appreciated for any help.

**Comment by vringar** [comment]
Do you need to do this at runtime or can you do this when analysing this data?

**Comment by nrllh** [comment]
It actually doesn't matter, It's also fine if I can get it after crawling has been completed.

**Comment by vringar** [comment]
Then I'd suggest doing this analysis on the data afterwards.
How do you save the data as SQLite or in parquet?

**Comment by vringar** [comment]
Then unfortunately I don't have a ready made script for you, but you should be able to look at the `crawl_history` table and group by visit id filtering down to `ok`, `timeout` and everything else.

**Comment by nrllh** [comment]
oh, this helps me too. Thank you!
