### ISSUE TITLE
Include OpenWPM as a module

### ISSUE THREAD

**Issue by Jidbo** [mozilla/OpenWPM#933]
I'm in the process of upgrading our project from OpenWPM version 0.13 to version 0.15, and I have hit a roadblock.

In our project we have OpenWPM included as a git submodule and import the `CommandSqequence` and `TaskManager` classes directly from there. Somewhere in the update from 0.13 to 0.15 the imports seem to have changed. In 0.13 OpenWPM used relative imports, but now all imports are from the `openwpm` module, which is not exposed to our application. If I try to import the `CommandSequence` with a statement like `from OpenWPM.openwpm.command_sequence import CommandSequence` I get an error
```
  File ".../OpenWPM/openwpm/commands/profile_commands.py", line 7, in <module>
    from openwpm.config import BrowserParamsInternal, ManagerParamsInternal
ModuleNotFoundError: No module named 'openwpm'
```
Is there any way I can fix this, or should I just stay on version 0.13? Are there any other ways I can include OpenWPM into our project?

**Comment by vringar** [comment]
Hey,
that's a really clean way to integrate with OpenWPM.
You should be able to fix the import errors you're seeing by adding the `OpenWPM` folder to your [PYTHONPATH](https://docs.python.org/3/using/cmdline.html#environment-variables) environment variable.
Something like
```bash
export PYTHONPATH="<absolute path to your repo>/OpenWPM"
```

**Comment by Jidbo** [comment]
Thank you, I'll try this. :+1:
