### ISSUE TITLE
READ ME file

### ISSUE THREAD

**Issue by MaazBinMusa** [mozilla/OpenWPM#936]
For docker support, the commands are not updated. The current docker run command still has a `python3 op/OpenWPM/demo.py` at the end.

But with `CMD = ["python","demo.py"] `in the Dockerfile, we dont need that in the docker run command

**Comment by vringar** [comment]
Do you want to file a Pull Request to fix this?

**Comment by MaazBinMusa** [comment]
> Do you want to file a Pull Request to fix this?

Sure! Just did.
