### ISSUE TITLE
Add a `tab closed` and `tab loaded` attribute to CommandSequence.py

### ISSUE THREAD

**Issue by englehardt** [mozilla/OpenWPM#99]
Some commands open a tab / load a new site (e.g. `get`), some commands can only be executed after a page is loaded (e.g. `save_screenshot`), and other commands require the tab to be closed / the site visited ended so no new requests are made by the browser (e.g. `dump_flash_cookies`). 

We currently have a flag `contains_get_or_browse` on the CommandSequence instance that marks that a tab is loaded. I think it makes sense to add both a `tab loaded` and `tab closed` boolean to the sequence instance which each command can set depending on its actions and get depending on its requirements. This should prevent the kind of ordering issue we see in #98.

**Comment by svensevenslow** [comment]
Hi! Is this feature still required? Can I work on this @vringar ?

**Comment by englehardt** [comment]
We don't have commands that close the browser tabs anymore, and this hasn't been reported again. Closing.
